### ISSUE TITLE
Option for 1/4 Screen Side-By-Side

### ISSUE THREAD

**Issue by tdrusk** [mate-desktop/marco#101]
First of all, I really appreciate the the new side-by-side implementation and all the work you have done in MATE 1.8.0. Would it be possible to add an option that would allow us to resize the window to 1/4th the screen, assigning this to the corners of the screen?
##

**Comment by tdrusk** [comment]
Where can I find the code to try to implement this myself?

**Comment by Yanpas** [comment]
+1

**Comment by kainhofer** [comment]
+1, particularly useful/required if you have a huge monitor like 2560x1440...

**Comment by flexiondotorg** [comment]
It is possible to assign keybindings to send windows to screen quadrants, this has been enabled by default in Ubuntu MATE for sometime. Here's the extract from the Ubuntu MATE gsettings override:

```
[org.mate.Marco.window-keybindings]
move-to-center='<Control><Alt>KP_Begin'
move-to-corner-ne='<Control><Alt>KP_Page_Up'
move-to-corner-nw='<Control><Alt>KP_Home'
move-to-corner-se='<Control><Alt>KP_Page_Down'
move-to-corner-sw='<Control><Alt>KP_End'
move-to-side-n='<Control><Alt>KP_Up'
move-to-side-s='<Control><Alt>KP_Down'
tile-to-side-e='<Control><Alt>KP_Right'
tile-to-side-w='<Control><Alt>KP_Left'
```

**Comment by raveit65** [comment]
@flexiondotorg 
I agree to make those keybindings enable by default, as using side-by-side-tiling with the keyboard is much better than with mouse.
In fedora i disabled side-by-side-tiling as default with a gsettings override as most user that i know don't like it, if a window goes to maximum size only when you touch the top panel with a window a bit.
So enable that keys as default is amazing.
.........personal i use them in every installation ;-)

Beside from that we should add 'improving side-by-side-tiling' to our roadmap.

**Comment by monsta** [comment]
> It is possible to assign keybindings to send windows to screen quadrants, this has been enabled by default in Ubuntu MATE for sometime. 

Moving windows is possible, but this request seems to be about tiling a window to take 1/4 size of the screen.

**Comment by raveit65** [comment]
will be availabe with 1.20 release.
