### ISSUE TITLE
Windows move from secondary to primary monitor with window snapping enabled 

### ISSUE THREAD

**Issue by cddesja** [mate-desktop/marco#103]
I have two monitors. I then enable window snapping and snap one application to the secondary monitor (i.e. the monitor without mate-panels). If I then click the Mate menu (either Applications, Places, or System), then the snapped window jumps to the primary monitor. This happens 100% of the time.

Also, again with window snapping enabled, if I minimize an application on the secondary monitor, when I go unminimize it by clicking in the mate-panel, the application jumps to the primary monitor. This happens 100% of the time.

I expect in both situations that the window should remain snapped in the secondary monitor.

Perhaps this is a bug in mate-panel instead?

**Comment by monsta** [comment]
Looks like it has been fixed for good.
