### ISSUE TITLE
Add keybindings for tiling windows

### ISSUE THREAD

**Issue by nsemrau** [mate-desktop/marco#104]
After enabling the window tiling feature through the "Windows" dialog in the control center, no entries regarding this feature appear in the "Keyboard Shortcuts" dialog.

Please add the possibility to bind tiling a window to a keyboard shortcut.

Possible labels: "Tile window to the left/right".

Arch Linux
marco 1.8.0-1
mate-control-center 1.8.1-1
mate-desktop 1.8.0-3

**Comment by aPollO2k** [comment]
It is one of the missing major features. I want it, too :)
