### ISSUE TITLE
Bad window states of restored windows from a previous session

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/marco#112]
When restoring windows from a previous session, they are always displayed as "needing attention", which IMO is unnecessary and annoying.

I hope this is related to "marco". I would appreciate any comment on the developers view on this (or if they use that feature at all) and how this can be changed (in case you see this also as a problem).

**Comment by monsta** [comment]
> they are always displayed as "needing attention"

Do you mean taskbar items flashing? I can't reproduce that...

**Comment by muesli4** [comment]
I think it is related to *atril*, so I guess this can be closed.
