### ISSUE TITLE
Running apps via pkexec results in pkexec window not receiving the focus

### ISSUE THREAD

**Issue by monsta** [mate-desktop/marco#117]
Steps to reproduce:

1. Save the script from [this page](http://pastebin.com/c7T5peub), make it executable, run it.
2. Alt-Tab away from it.
3. Alt-Tab back into it.
4. Click on the button.
5. The pkexec window is  not **focused** while it should.

Note: in some cases (e.g. if you run the script with "&") it might require a second consequence of alt-tabbing away/back and the following button clicking in order to reproduce the issue consistently.

This issue can be reproduced in:
* Linux Mint 17 with MATE 1.8
* Linux Mint Debian Edition (LMDE) with MATE 1.6
* Debian Testing with MATE 1.8

This issue can't be reproduced in Cinnamon or Xfce. Moreover, if you replace Marco with e.g. xfwm4, the issue can't be reproduced too. So I concluded this is a bug in Marco.

However, it can be reproduced if you replace Marco with Metacity, which might indicate this is a legacy bug.

**Comment by HuangZhiquan** [comment]
ah, i want to know the cause of the issue,why they can not drag the focus

**Comment by monsta** [comment]
Hehe, if we only knew the cause, we'd probably fix the problem right away... :)

BTW, I found out it also happens when using Gnome's polkit agent instead of MATE's one. Though their code isn't really maintained these days...

**Comment by alecz20** [comment]
For what it's worth I am able to reproduce this in Ubuntu Mate 14.04 with the following simple steps:
1 - Open terminal
2 - enter <code>pkexec pluma</code>
3 - notice that the authentication window is not focused and anything you type appears in the terminal

I don't remember this being an issue in Ubuntu 10.04

**Comment by monsta** [comment]
Ok guys, if you know how to patch & build packages, please check if https://github.com/mate-desktop/mate-polkit/issues/22 fixes the problem for you.
