### ISSUE TITLE
Video screen tearing when compositing is enabled (Intel video)

### ISSUE THREAD

**Issue by ayurchen** [mate-desktop/marco#120]
May be related to #91 
When marco's compositing is disabled screen tearing can be fixed with e.g.
`VDPAU_DRIVER=va_gl /usr/bin/mplayer "$@"`
however enabling compositing brings screen tearing back, even with this fix.

with compositing disabled I have the following lines in mplayer output:

```
VO: [vdpau] 714x572 => 1015x572 Planar YV12 
[vdpau] Got display refresh rate 59.970 Hz.
[vdpau] If that value looks wrong give the -vo vdpau:fps=X suboption manually.
```

with compositing enabled those lines are missing (everything else is identical, including vdpau initialization) which suggests that compositing somehow prevents full usage of VDPAU driver/library.
##

**Comment by monsta** [comment]
Let's move to https://github.com/mate-desktop/marco/issues/326. DRI3 might be a good solution for tearing.
