### ISSUE TITLE
Pointer window placement

### ISSUE THREAD

**Issue by paravoid** [mate-desktop/marco#123]
xfce has a feature where windows are being placed according to the pointer position at the time. It's incredibly nifty and useful, at least to me :)

muffin, a mutter fork, has implemented this as well, with
https://github.com/linuxmint/muffin/commit/325767132d22a008a7b9c397d9ca1751bac41a62

The code looks fairly similar to marco (due to muffin/mutter/metacity common inheritance) and the patch is fairly trivial (basically one function + stitching that to the code with an option).

It could probably very easily be ported to marco and I could give it a stab, although someone with more marco experience would probably tackle it in far less time than I would :)

**Comment by monsta** [comment]
Looks like it's fixed by https://github.com/mate-desktop/marco/pull/219.
