### ISSUE TITLE
Window maximized wrong with seconday screen on top

### ISSUE THREAD

**Issue by n0rad** [mate-desktop/marco#135]
I usually have a secondary screen on top of my primary.

When the seconday screen is active, maximizing a window on the primary does not take into account the bar (which is on top of the primary) anymore, and a part of the window is hidden behind the bar 
##

**Comment by ralesk** [comment]
It still exists and is broken no matter which one is the primary.  As long as there's a screen beyond a panel (and I don't think it's possible to put panels on a non-primary screen), the windows will ignore panels during maximisation.  Here are two screenshots with screens above one another (external display above laptop screen), one with the lower screen being the primary, one with the upper one.

![marco primary bottom](https://cloud.githubusercontent.com/assets/1564502/21428806/2e41263a-c85c-11e6-9cb1-c6d4edafd00a.png)
![marco primary top](https://cloud.githubusercontent.com/assets/1564502/21428805/2e3fa814-c85c-11e6-8c92-a510f3859fea.png)

**Comment by allanlaal** [comment]
bug still present in **1.24.0**:

when one of ≥1 **non-primary** Displays expands below the **primary** Display in the X screen, then a Maximized window on the **primary** Display will hide under the bottom mate-panel (even if Autohide=Off). it will not hide under the top mate-panel. (side panels not tested)

when atleast 1 of **non-primary** Dispays is configured to have its bottom be higher than the **primary* Display, then a Maximized window on the **primary** Display will maximize till the top border of the bottom mate-panel (if Autohide=Off).
However: (presumably) if the top of one of the **non-primary** Displays is higher on the X screen than the **primary** display, a Maximized window on the **primary** Display will now maximize to be covered by the top mate-panel (even if Autohide=Off)

**Comment by raveit65** [comment]
Fixed with
https://github.com/mate-desktop/mate-panel/commit/8a380c3e9af91a726b8ed45ccf9ef64911540595
https://github.com/mate-desktop/mate-panel/commit/79a8279c52e3d0b66985cbbeaeb88bae1522c4c2
https://github.com/mate-desktop/mate-panel/commit/5bd053ad542479eaec4166e45195c5e911472f88
