### ISSUE TITLE
moving window to another workspace usually fails the first time

### ISSUE THREAD

**Issue by brianjmurrell** [mate-desktop/marco#148]
If I want to move a window to a different desktop I right-click on the window's title-bar and then choose one of the "Move to" options.  Almost invariably this fails to actually move the window the first time I try it but succeeds on a second attempt.

Currently using marco-1.8.2-2.fc20.x86_64 but this has happened for as long as I can remember (counting years).

**Comment by NiceandGently** [comment]
@brianjmurrell 
i'm using f20 too but i verver saw this issue.
Does the issue still exists?

**Comment by brianjmurrell** [comment]
@NiceandGently I saw it very consistently for a while.  I'm on F21 now and don't see it much if at all.

**Comment by NiceandGently** [comment]
@brianjmurrell 
If you don't see it in f21, or if you can't remember that you have seen it on f21, can you please close the issue?
......if you agree.......
... don't have the rights for doing that.
