### ISSUE TITLE
[RPMLint]  64bit-portability-issue

### ISSUE THREAD

**Issue by posophe** [mate-desktop/marco#150]
The build fails with version 1.9.3.
E: marco 64bit-portability-issue core/keybindings.c:2355, 2367

**Comment by monsta** [comment]
Do you mean this?

```
core/keybindings.c: In function ‘error_on_command’:
core/keybindings.c:2353:25: warning: passing argument 4 of ‘meta_show_dialog’ makes pointer from integer without a cast
                         screen_number,
                         ^
In file included from core/effects.h:48:0,
                 from core/window-private.h:39,
                 from core/workspace.h:36,
                 from core/keybindings.c:31:
./include/util.h:101:6: note: expected ‘const char *’ but argument is of type ‘int’
 GPid meta_show_dialog (const char *type,
      ^
core/keybindings.c:2365:25: warning: passing argument 4 of ‘meta_show_dialog’ makes pointer from integer without a cast
                         screen_number,
                         ^
In file included from core/effects.h:48:0,
                 from core/window-private.h:39,
                 from core/workspace.h:36,
                 from core/keybindings.c:31:
./include/util.h:101:6: note: expected ‘const char *’ but argument is of type ‘int’
 GPid meta_show_dialog (const char *type,
      ^
```
It's no problem, this code isn't used anywhere. We could correct it to call g_strdup_printf to convert the screen number to string and then pass it to ```meta_show_dialog```, but maybe it's better to simply drop it like it has been done in Metacity (in [this commit](https://git.gnome.org/browse/metacity/commit/src/core/keybindings.c?id=a228546d3cdf3364b82d76b374fb08aae202ab87)).

**Comment by posophe** [comment]
Could be that. The only thing I know is that breaks the build on openSUSE

**Comment by monsta** [comment]
Well, you could check the error/warning messages during the build to see if it's really this issue.

**Comment by posophe** [comment]
Well, here is the reponsible :
"warning: passing argument 4 of ‘meta_show_dialog’ makes pointer from integer without a cast
                         screen_number,"
Causes the failure

**Comment by monsta** [comment]
Yeah, it's that function. You could use less strict compiler flags, it's just a warning :)
Given that the code isn't used anywhere, it does no harm currently.

**Comment by posophe** [comment]
I can't. I just use the default flags to build.

**Comment by monsta** [comment]
Ok, I guess we'll have to remove the offending code (since it's not used anyway, and it's removed upstream as well).

**Comment by monsta** [comment]
Disregard that, I was confused by the weird code that somehow makes static functions available outside the ```keybindings.c``` source file. The code is actually used. I'll correct the argument type and file a pull request later.

**Comment by monsta** [comment]
@posophe: there we go, please test https://github.com/mate-desktop/marco/pull/185 - the build should be fine now.

**Comment by posophe** [comment]
I confirm; it builds successfully :)
