### ISSUE TITLE
Alt-tab to window that is "Always on Visible Workspace" will switch to original workspace

### ISSUE THREAD

**Issue by hugobuddel** [mate-desktop/marco#156]
The window manager might switch workspaces when one alt-tabs to a window that is set to be "Always on Visible Workspace".

To reproduce:
- Open window on workspace 1, e.g. firefox.
- Right click on window title and set "Always on Visible Workspace".
- Go to workspace 2.
- Open another window, e.g. a terminal.
- Alt-tab from the second window (terminal) to the first window (firefox).

Behaviour perceived to be incorrect: The window manager will switch back to workspace 1.

Expected behaviour: The window manager should stay on workspace 2.

Reproducable with this virtual machine: https://virtualboximages.com/linuxmint-17-mate-64bit-VirtualBox

**Comment by dnk** [comment]
already fixed by https://github.com/mate-desktop/marco/pull/121

**Comment by infirit** [comment]
I'll close this, if this can be reproduced after 0ee6f6db3f405c13c88f75760f88296560cf9fd6 do let us know.
