### ISSUE TITLE
Tile preview graphics glitch

### ISSUE THREAD

**Issue by adamjsmith** [mate-desktop/marco#158]
Steps to reproduce bug:

1. Snap a window to the left of the screen
2. Snap a window to the right of the screen
3. Before the tile preview appears the background of the left of the screen appears very briefly (a fraction of a second) at the right of the screen
4. Snap a window to the left of the screen
5. A similar graphics glitch is observed on the left of the screen (i.e. the right hand side background is flashed on the left of the screen).

This is reproducable under ubuntu-mate 12.04 (precise) and 14.04 (trusty).

Marco version: 1.8.2+dfsg1-4~trusty1

This is on a big-endian machine (PowerPC), but I think the slowness of the machine is more significant.

Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/marco/+bug/1406344

**Comment by NiceandGently** [comment]
@stefano-k 
@flexiondotorg 
commit is in marco-1.10.1, can be closed.
