### ISSUE TITLE
Tiling code does not notice compositor switching on<->off

### ISSUE THREAD

**Issue by adamjsmith** [mate-desktop/marco#159]
Steps to reproduce bug:

1.  Check tile preview is working with marco compositor turned on
2.  Turn off compositor
3.  Tile preview still working as expected
4.  Reboot
5.  Tile preview does not appear, although the window still resizes as expected

**Comment by infirit** [comment]
It does but it should show a wireframe instead which it does for me. But.. 

There is a bug that makes the tiling code not notice the compositor switching on<->off which leads to inconsistent behaviour.

**Comment by dnk** [comment]
https://github.com/mate-desktop/marco/pull/162

**Comment by infirit** [comment]
Thanks @dnk for the fix. This will show up in Marco 1.10.
