### ISSUE TITLE
Cannot tab out of Wine fullscreen applications (XIconifyWindow without MWM_FUNC_MINIMIZE)

### ISSUE THREAD

**Issue by stefand** [mate-desktop/marco#166]
Sine version 1.7.32 Wine handles focus loss events (usually Alt-Tab) for fullscreen Direct3D applications. The core part of this is minimizing the game's window and restoring the screen resolution to what it was before the game started. Minimizing the game's window does not work for most of the games because Marco (just like any other Metacity fork) ignores XIconifyWindow requests on windows that do not set MWM_FUNC_MINIMIZE.

The user-visible symptom is a frozen window that does not redraw, cannot be completely minimized and cannot be restored either. For practical purposes the application the application crashes as soon as Alt-Tab is pressed. Interestingly the "Show Desktop" functionality can be used to minimize the window. After this the window can be restored by clicking on it in the panel and it resumes operation.

KDE and FVWM minimize the window without issue. According to my investigations the current behavior of Wine matches that of Windows - applications without WS_MINIMIZEBOX do not have a Minimize item in their system menu, so not setting MWM_FUNC_MINIMIZE without WS_MINIMIZEBOX is the correct thing to do. Unfortunately the Motif Window Manager spec is very vague and says that window managers can do whatever they want with XIconifyWindow. The check in question was added to Metacity in 2001 by patch ec4dfd0c (git://git.gnome.org/metacity). It appears that this was a workaround against accidentally minimizing the gnome panel.

I will try to attach a sample Windows application in C source and / or .exe form that shows the issue. Otherwise pretty much any Windows game can be used to reproduce the issue with Wine 1.7.32 or later. I have tested Half Life 2, Warcraft 3 and World in Conflict.

**Comment by stefand** [comment]
I cannot attach anything except images. I have uploaded the example program to my simple web server:

https://stefandoesinger.ddns.net/~stefan/minimize.c
https://stefandoesinger.ddns.net/~stefan/minimize.exe
(Self-signed SSL cert, and the server may be down every now and then)

The program simply fills the screen with a red color, fading to yellow, going back to red. On Alt-Tab the game should minimize. When going back to the application it should resume drawing its color. Ctrl+C it to quit.

**Comment by tizbac** [comment]
https://github.com/mate-desktop/marco/pull/169 that fixes it

**Comment by stefand** [comment]
#169 works only when the game is running at the desktop resolution. What matters is probably the randr screen resolution, not the CRTC res, but I can't test right now because I am using Nvidia's driver on a laptop. If the game sets the resolution lower window->fullscreen is false.

**Comment by stefand** [comment]
This may be a wine bug, or a side effect of Nvidia's xrandr 1.1 hack. I'll investigate.

**Comment by tizbac** [comment]
Here with opensource drivers it works perfectly, so it is nvidia problem

**Comment by stefand** [comment]
I tested it with the open source radeon driver, and the bug still happens in games. It does not happen with my test application because the test application always runs at the native desktop resolution.

I can adjust my test program if you want, but it doesn't really matter. I believe this is a Wine bug: We do not set NET_WM_STATE_FULLSCREEN after mode changes because we compare the window size against the old screen resolution. I have filed https://bugs.winehq.org/show_bug.cgi?id=38009 to keep track of this problem.

**Comment by tarceri** [comment]
Just FYI the patch [1] also fixes this bug [2][3]

[1] https://github.com/mate-desktop/marco/pull/167
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1190525
[3] https://bugs.winehq.org/show_bug.cgi?id=38064

**Comment by monsta** [comment]
So, guys, should we accept https://github.com/mate-desktop/marco/pull/167 instead of https://github.com/mate-desktop/marco/pull/169?

**Comment by NiceandGently** [comment]
any news?
users waiting for it
https://bugzilla.redhat.com/show_bug.cgi?id=1190525

**Comment by stefand** [comment]
I am happy with either solution. I believe the problem 169 has is a Wine bug. Note that Muffin accepted the equivalent of 167, not sure if that influences your decision.

**Comment by infirit** [comment]
I merged #167 to master just now.

**Comment by monsta** [comment]
I guess this report and https://github.com/mate-desktop/marco/pull/169 can be closed now?
