### ISSUE TITLE
Absolute resolution windows drawn issue. 

### ISSUE THREAD

**Issue by WyRe** [mate-desktop/marco#173]
Hi guys, i'm having this issue and I have asked on many sites (above all in IRC) ... I conclude that could be an WM's issue ... 

I'm using 1024x576 res and seems to be that absolute resolution windows (specially vertical resize) like properties windows of many applications are drawn out of my desktop... this is particulary annoying because some 'Cancel' or 'Apply' buttons are situated here (in bottom side of these windows)

Any idea to solve this issue would be welcome... :D (i'm running on Archlinux and with 1.8.2 Marco's version https://www.archlinux.org/packages/community/i686/marco/ ) 

In this link where i have posted my issue on Intel Video Driver bug tracking https://bugs.freedesktop.org/show_bug.cgi?id=89176
There is more information and descriptive pics like these: 

http://postimg.org/image/e60q36911/

http://postimg.org/image/fl2lcpcf3/

Other windows are drawn but behind bottom panel:

http://postimg.org/image/f7jey26jf/

http://postimg.org/image/fcqxo3q89/

Thanks for ur time and sorry for inconveniences :D

**Comment by WyRe** [comment]
Oh, guys! ... I'm sorry, some people gave me some ideas to surround the issue ... I have resized font and have set autohide in menu bars ... now seems to be that can i see fully windows, ... Can u close the issue and sorry for my incompetence ... xD

http://postimg.org/image/5a97qrlj7/

**Comment by WyRe** [comment]
anyway the real issue is not solved, ... i think that you should be aware.

http://postimg.org/image/q88a0ca2z/

**Comment by monsta** [comment]
The "real issue" won't be solved as it would require too much work redesigning **all** the MATE apps for such a low resolution - and there's only a small number of devices (e.g. netbooks) where it would be worth.

Workaround: hold Alt, click on any place inside the window and move the mouse to drag the window where you wish.

**Comment by WyRe** [comment]
Yes u are right, and thank you so much for the workaround ;D
