### ISSUE TITLE
Add ability to use the Arrow Keys when switching windows with ALT+TAB [$100]

### ISSUE THREAD

**Issue by BrootLee** [mate-desktop/marco#182]
Hello.
Take any popular desktop environment you like. You can use the Arrow Keys when switching windows with ALT+TAB. It's more comfortable and faster than having to press TAB several times with the same finger. Please add this feature.
Thank you.
##

**Comment by imperative** [comment]
Additionally, it should be possible to use mouse to select the application to switch to, within the alt-tab window. (By clicking on the icon of that application.). This is also the default and very useful and userfriendly behavior, which exists in almost any other window manager.

**Comment by BrootLee** [comment]
I'm so glad someone else became interested in this! I agree with the above comment by the way, using the mouse to select the window should also be possible.

**Comment by PapayaMedia** [comment]
I don't remember to have used the arrow keys to move between window thumbnails. But the mouse option to select the needed window is a must have. I really want this feature to be implemented.

**Comment by yoburtu** [comment]
Hello,

Has any of this request been incorporated into Mate Desltop 1.18? I am very interested in it.

Best regards.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/marco/commit/c4750c85961777e6ab00b46fb12b1ba0253796d5
https://github.com/mate-desktop/marco/commit/7c69bcf4d5b195902c770bcbf84bd8b8c3427059

**Comment by imperative** [comment]
Does the mouse work now too? Or should we create another issue?
