### ISSUE TITLE
Resizing issue, dragging wont work when ...

### ISSUE THREAD

**Issue by freed00m** [mate-desktop/marco#183]
1.) Open a terminal window.
2.) Type following command: xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x2, 0x0, 0x0"
3.) Click on any window (a terminal window, for example). Window decorations will be hiden.
4.) Try to resize it by draging the corners.

I often set my WM_HINTS "0x2, 0x0, 0x2, 0x0, 0x0" and then I am unable to resize by dragging, it spawn a menu instead.

**Comment by dnk** [comment]
as workaround you can use "Movement key" ("Alt" by default): press "Alt" + press "mouse left key" and drag window for any window part

**Comment by freed00m** [comment]
@dnk Thanx I didn't knew about such thing :) .. Would still prefer normal rezise via simple mouse.

**Comment by dnk** [comment]
"Movement key" + middle mouse key can resize window :)

**Comment by freed00m** [comment]
@dnk Can you be more specific? The middle mouse button often do other things like pasting selected content or sending window to the bottom. 

By movement key you mean arrows? It doesn't work for me. And I believe I have defaults settings.
