### ISSUE TITLE
Option to disable window outlines on switching with Alt-Tab

### ISSUE THREAD

**Issue by sgtpep** [mate-desktop/marco#184]
When you switch windows using Alt-Tab marco draws nasty (sorry) outlines of currently highlighted window. It would be nice to be able to turn this behaviour off.
##

**Comment by monsta** [comment]
This is now implemented in 1.18 via https://github.com/mate-desktop/marco/pull/290. The border can be turned off via dconf-editor or gsettings tool.

`$ gsettings set org.mate.Marco.general show-tab-border false`
