### ISSUE TITLE
Blue box stays onscreen when snapping windows.

### ISSUE THREAD

**Issue by hendrikwiersma** [mate-desktop/marco#193]
This happens when I normally snap windows or try to open a new tab in Firefox and miss the plus icon. I found a way to trigger it at any point.
Here is how to replicate:
1. Snap a window to the right.
2. Click the titlebar 3 times very quickly.
![marco](https://cloud.githubusercontent.com/assets/6975984/7505466/f03025f0-f452-11e4-9539-38d6aff1c1d0.png)
OS: Arch Linux x86_64
Kernel Release: 4.0.1-1-ARCH
Marco 1.8.3-1
Mate-Desktop 1.8.2-1

**Comment by monsta** [comment]
Does it still happen in latest 1.10.x release?

**Comment by monsta** [comment]
If there won't be any further feedback, I'm closing it as fixed.
