### ISSUE TITLE
Corner tiling for MATE without Compiz as implemented in Xfce 4.12

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/marco#194]
Currently MATE only have left and right tiling. What about MATE having up-dowm, left-right, and corner tiling? Unity has all of them, and they might have used Compiz for that. But I want these in MATE without using Compiz. Xfce 4.12 has implemented left-right, and corner tiling without using compiz. Could you do that for us?

**Comment by raveit65** [comment]
see other report
