### ISSUE TITLE
Massive flickering.

### ISSUE THREAD

**Issue by tsjnachos117** [mate-desktop/marco#195]
Hello, everyone. I'm having a problem with on my system, in which every time I start Mate, I get massive flickering. This is particularly common if certain windows are open. If there are no windows open, there if no flickering. Some of these windows include the "about Mate" window, and xterm. However, other windows like Midori or Konsole work just fine.

Also, when this happens, the titlebars on all visible windows disappear, making them much harder to close. To make matters worse, Mate/Macro can't make up it's mind which window is on top (it seems to switch the order of the windows several times per second), making all buttons difficult to click.

If I switch window managers, the flickering is completely gone (I've tested Mate with xfwm, and metacity). IDK what could be causing this issue.

I just stated an instance of Mate using "xinit /usr/bin/mate-session -- :1 &> ~/Desktop/mate.log" to get some output which should hopefully be useful. See [HERE](http://pastebin.com/iDCav7ip). Thanks in advanced.

PS: I'm using the 32-bit edition of Ubuntu 14.04, Mate was installed using the **ubuntu-mate-dev/ppa** and **ubuntu-mate-dev/trusty-mate** PPAs.

PPS: if anyone is wondering what kind of video hardware I have, the output of **sudo lspci -k | grep -A3 VGA** was:

```
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller     (rev 02)
    Subsystem: Dell Device 040a
    Kernel driver in use: i915
```

Also, I can't change the background on my system. No matter which background I select, I stll see the same grey color. I mention this because the problems might be related.
##

**Comment by tsjnachos117** [comment]
Also, if anyone is wondering what kind of video hardware I have, the output of **sudo lspci -k | grep -A3 VGA** was:
        
    00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller     (rev 02)
    	Subsystem: Dell Device 040a
    	Kernel driver in use: i915

**Comment by raveit65** [comment]
Issue still exists?

**Comment by tsjnachos117** [comment]
> Issue still exists?

I've only seen this issue in Ubuntu 14.04, which is officially end-of-life. Every other system I've used Mate on - including newer versions of Ubuntu- work just fine. That said, I think I'll just close this issue.
