### ISSUE TITLE
Peculiar window raising in MATLAB

### ISSUE THREAD

**Issue by NVoronchev** [mate-desktop/marco#197]
Linux distrib: Ubuntu Mate 14.04
Marco version: marco 1.8.3

This bug was found in the MATLAB environment. The problem is: in some cases already existed window is not raised on top, but the corresponded button at a mate-panel becames blinking. For example, to reproduce it one may proceed the following steps:
1) create a new empty Figure No.1 ("figure(1)" command);
2) select the main MATLAB window back, ensuring that it covers the created figure;
3) execute "figure(1)" one more time.
In case of Compiz or Metacity, the figure window raises on top. In case of Marco, the MATLAB main window looses focus, but figure window is not appears. To show it, one should click on the button at a mate-panel doubly -- to hide and restore window.
This feature, in particular, interferes to debug MATLAB scripts with GUI.

Meanwhile, something like this bug can be reproduced in case of Marco, Compiz or Metacity through Python:
1) Perform the following commands in Python console:

> >>> import gtk
> >>> window = gtk.Window(gtk.WINDOW_TOPLEVEL) 
> >>> window.connect("destroy", gtk.main_quit) 
> >>> window.show()

2) Cover the created window by any other window;
3) Press _Alt+Tab_(!) several times to return to Python terminal;
4) Try the command:

> >>> window.present()

To reproduce the strange behavior, the _Alt+Tab_ must be pressed exactly on the created window at least one time. If one returns back to terminal with help of mouse (step 3), the feature will not appear.
I am not sure, whether it is connected with the bug in MATLAB, but outwardly this two cases look similarly.
##

**Comment by VoronN** [comment]
Oh, excuse me, please. I have build Marco 1.10 from the present repository -- it works fine with MATLAB.
