### ISSUE TITLE
[Regression] Certain fullscreen wine applications are handled incorrectly (by >=1.7)

### ISSUE THREAD

**Issue by dnord** [mate-desktop/marco#213]
What have you did: launched one of the affected applications.
What happend: screen resolution changed, but instead of going fullscreen, application area remained moved aside from visible display area. So application is working, screen resolution is set, but application area is invisible.
What did you expect: Proper start of fullscreen application.

Configuration: Mint 17.2, (mate, marco: 1.10) Video: intel (also reproducible with virtualbox virtual video)

My tests showed, that this is regression was arised due to following commit: mate-desktop/marco@1b638654a247ae17bf0aa3d9d78f8f8e16453810
Metacity is not affected, xfwm4 and kwin also manage to handle these applications properly, so please consider this issue carefully.

How to reproduce: you may run following game in this environment:
Fresh installatinon of linux mint 17.2 mate as virtualbox guest (also reproducible on my hardware which is notebook with intel hd graphics), stable wine 1.6, and the game "Touhou 10 - Mountain of Faith" runned in fullscreen mode. Demo version can be downloaded on from [official site](http://www16.big.or.jp/~zun/html/th10dl.html) ([link](http://mirror.studio-ramble.com/upload/535/200707/th10tr002a_setup.exe)).  Actually all known to me affected applications are games of Touhou Project (games from touhou 06 to touhou 13 were tested) and Koumajou Densetsu II: Stranger's Requiem.

**Comment by monsta** [comment]
Weird... the problem introduced by that commit should've been fixed in https://github.com/mate-desktop/marco/commit/13741f524e5f8b780a96872f534237186fa78741...

**Comment by dnord** [comment]
It fixes problem for most application, but for some reason not for all.

**Comment by dnord** [comment]
Somehow issue is fixed after mate-desktop/marco@4007ca1c695c84a3a82d1fcdf81950d4062ccdf0
Please close.
