### ISSUE TITLE
Add more tiling options

### ISSUE THREAD

**Issue by ciechomke** [mate-desktop/marco#218]
I think that tilling windows to left and right border is not enough. Look at tilling in KWin - by default you can tile windows to right and left borders and also to corners so it expands number of tilled windows at once to four. It also provides more configuration options to tile more than 4 windows like in tilling WM's (awesome for example). Many people use MATE Desktop to work (code, managing remote hosts) due to it's lightweight and responsibility so this feature can improve suitability of MATE to work with many windows at one workspace.
##

**Comment by milankni** [comment]
That is especially usefull on large screens, the window on half screen tiling is still unnecessarily too large.

**Comment by jean** [comment]
My screen is exactly right for three terminals. Two terminals each taking up half the screen are too wide.

**Comment by GiedriusS** [comment]
Similar issue: https://github.com/mate-desktop/marco/issues/194. Perhaps this one or the other one could be closed?

**Comment by raveit65** [comment]
What compiz-0.88 can since a long time is simply genius.
9 positions on screen selectable via keyboard shortcuts +
3 sizes for one position selectable if you press the same shortcut again.

**Comment by reydun** [comment]
This would really be appreciated, I'm seriously contemplating switching away from Marco to openbox just for this. Compiz can do this, but it's too resource heavy for my taste.

I really hope someone is working on this for a future release at least.

**Comment by raveit65** [comment]
> This would really be appreciated, I'm seriously contemplating switching away from Marco to openbox just for this. Compiz can do this, but it's too resource heavy for my taste.

> I really hope someone is working on this for a future release at least.

We are a small theme and we do our best to make users happy, but a day has only 24 hours ;)
Patches are welcome.
Hope you will use marco again if it is done.

**Comment by v1kn** [comment]
What is the current state of implementing this feature?  

To many users corner tiling is a crucial functionality and a deal braker, and since MATE DE has been getting traction, popularity, and a lot of work is being done (looking at ubuntu mate), I thought I would bring back some attention to this. 

Looking forward to this feature, please consider it

**Comment by monsta** [comment]
Corner tiling is implemented now (was also requested at https://github.com/mate-desktop/marco/issues/101). You will get it with 1.20 release.
Not sure if anyone would implement tiling for more than 4 windows on the screen (like 9 positions in compiz mentioned above).
Should we close this or keep it open?

**Comment by flexiondotorg** [comment]
Keybindings are available in MATE to tile to more than just quadrants and quadrant tiling is available via window dragging in 1.20. This can be closed.
