### ISSUE TITLE
Artifacts after going fullscreen in some games with fglrx driver

### ISSUE THREAD

**Issue by Lukypie** [mate-desktop/marco#227]
I'm not able to play in fullscreen games such as minecraft, or opengl applications such as stellarium with the fglrx drivers, marco and compositing enabled
With metacity I don't have this problem.
##

**Comment by monsta** [comment]
So if you disable compositing in marco, the games have no glitches?

**Comment by Lukypie** [comment]
Exactly, and with metacity also with compositing enabled I dont have problems

**Comment by monsta** [comment]
@dnk: can you please take a look at this?

**Comment by monsta** [comment]
This most probably was a problem in driver itself, as tests on nvidia card with their proprietary drivers didn't show any problems. Besides, fglrx is dead upstream, so it can't be fixed.
