### ISSUE TITLE
marco crashes when moving a window with a mouse

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/marco#228]
Here a litle video which describes the issue:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/marco-crash.ogv
Steps to reproduce:
1. enable compositor
2. start a new mate-session
3. open min 2 windows
4. move one window
5 boom, marco crashed

Note, this doesn't happens with gtk3 build and if compositor is off in gtk2 build.
It's reported in all fedora versions, f21/f22/f23
Downstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1258131 (other reports are marked as duplicates)
Stacktrace fom today:
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/marco-backtrace
```
Truncated backtrace:
Thread no. 1 (10 frames)
 #4 split_edge at core/boxes.c:1569
 #5 meta_rectangle_remove_intersections_with_boxes_from_edges at core/boxes.c:1691
 #6 compute_resistance_and_snapping_edges at core/edge-resistance.c:1089
 #7 apply_edge_resistance_to_each_side at core/edge-resistance.c:556
 #8 meta_window_edge_resistance_for_move at core/edge-resistance.c:1172
 #9 update_move at core/window.c:7182
 #10 meta_window_handle_mouse_grab_op_event at core/window.c:7654
 #11 event_callback at core/display.c:2084
 #12 filter_func at ui/ui.c:289
 #13 gdk_event_apply_filters at gdkevents-x11.c:371
```

**Comment by flexiondotorg** [comment]
This is reproducible in Ubuntu MATE 15.10. Also crashed in Animations are enabled when Maximising/Minimising Google Chrome or Chromium, although in this case compositing can be on or off.

**Comment by raveit65** [comment]
yes, in some reports reporter talks about resizing too.

**Comment by raveit65** [comment]
We have a regression introduced somewere between 1.9.2 and 1.9.3.
marco-1.9.2-2.fc22 works well.
marco-1.9.3-1.fc22 crashed.
I will track down it more with git bisect.

**Comment by raveit65** [comment]
Ok, the bad commit is http://git.mate-desktop.org/marco/commit/?h=1.10&id=bcbc109
**add support for _GTK_FRAME_EXTENTS**

**Comment by raveit65** [comment]
reverting those 3 commits via git rebase works cleanly and fixes the issue for me.
http://git.mate-desktop.org/marco/commit/?h=1.10&id=bcbc109
http://git.mate-desktop.org/marco/commit/?h=1.10&id=13741f5
http://git.mate-desktop.org/marco/commit/?h=1.10&id=470fed7
I'm not shure about the consquences and for what GTK_FRAME_EXTENTS is good for.
@monsta 
@dnk 
@flexiondotorg
@clefebvre
@stefano-k 
Any thought?
Can this commits be improved?
Pesonal i give a s...t about csd windows looking in mate, so chances a good that those culprits will die in fedora, to avoid anoying mails in my mailbox about another user which is a victim by this bug.

**Comment by raveit65** [comment]
for master branch reverting http://git.mate-desktop.org/marco/commit/?id=768fdd8 is needed too.

**Comment by monsta** [comment]
Wow that's a lot. Is it really needed to revert more than one commit to fix it?

**Comment by raveit65** [comment]
The removed the other commits because rebase doesn't work w/o removing them, or building failed.
So maybe they need only be adjusted.

**Comment by raveit65** [comment]
I noticed that https://git.gnome.org/browse/metacity/commit/?id=8f699b71bd7e5581ec2f2804ea9650597618dfe1
is missing in marco, maybe that is causing the issue.

**Comment by raveit65** [comment]
seems that reverting http://git.mate-desktop.org/marco/commit/?id=470fed7 isn't needed.
After editing it a bit git rebase runs.

**Comment by raveit65** [comment]
reverting http://git.mate-desktop.org/marco/commit/?id=768fdd8 on master is not needed too, after editing the other one.

**Comment by monsta** [comment]
Ok, should be fixed in master now. No reverts, just some missing initialization added :smile:

**Comment by FabioPedretti** [comment]
Ubuntu bug:
https://github.com/mate-desktop/marco/issues/228

Can this be backported to 1.10?

**Comment by monsta** [comment]
> Can this be backported to 1.10?

It is.
https://github.com/mate-desktop/marco/commits/1.10
