### ISSUE TITLE
composite window borders - too much shadowin'?

### ISSUE THREAD

**Issue by ghost** [mate-desktop/marco#23]
If a user activates composite mode, the windows get a bit of shadowing; I find the default shadow print a bit exagerated; would it be possible we could improve it to a smoother thing more pleasant to the eye ?
##

**Comment by TomaszGasior** [comment]
Problem still exists.

Shadow size is hardcoded in Marco code. In my opinion this should be editable by dconf setting or by window manager theme.

**Comment by raveit65** [comment]
Closing, marco use invisible-borders now (resizing windows with shadow-area).
