### ISSUE TITLE
Gtk3 tracking report

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/marco#233]
This report list only Gtk3 bugs which needs to be fixed before marco can use for production with gtk3.
Please open a single report first if you found a new issue, mention there that you think this is a blocker report, and we will add them here.

MUST:

SHOULD:

NICE TO HAVE:
- GTK3: Alt-Tab switcher does not shows previews
  https://github.com/mate-desktop/marco/issues/232 fixed https://github.com/mate-desktop/marco/commit/9212dacb2bfd5985d8426bf0bdb88f2aca03444e
- GTK3: Some metacity themes are not rendered correctly
  https://github.com/mate-desktop/marco/issues/208 fixed https://github.com/mate-desktop/marco/commit/8f36c551693cb81a386b6f48178189b5eea38d91
- GTK+3: marco-theme-viewer isn't buildable
  https://github.com/mate-desktop/marco/issues/246
##

**Comment by monsta** [comment]
#232 is fixed :smile:

**Comment by raveit65** [comment]
OK, than we can close the tracking report ;)

**Comment by raveit65** [comment]
hmm, why isn't milestone on 100% ?

**Comment by raveit65** [comment]
re-open , this one is left
https://github.com/mate-desktop/marco/issues/246

**Comment by monsta** [comment]
Done with https://github.com/mate-desktop/marco/issues/246 :slightly_smiling_face:
