### ISSUE TITLE
[PATCH] Chromium window leaves traces during resize.

### ISSUE THREAD

**Issue by dnord** [mate-desktop/marco#242]
How to reproduce:
1. Set "Use system title bar and borders" in chromium settings to disabled
2. Try to resize chromium window, it will leave traces on empty desktop
This is https://bugzilla.gnome.org/show_bug.cgi?id=755001 fixed by https://git.gnome.org/browse/metacity/commit/?id=e88707b74f0c504fdd9bf582ea79560a30b6a7f7
so just backport this patch, please.

**Comment by monsta** [comment]
Thanks, patch pushed in https://github.com/mate-desktop/marco/commit/6c1fe100755895272c0165d1c884ade8d464a7be.
