### ISSUE TITLE
Window borders too thin

### ISSUE THREAD

**Issue by mixmastamyk** [mate-desktop/marco#243]
This is a bug that has persisted for a decade?  I was quite disappointed to find that I had to fix this again upon installing a fresh ubuntu mate:

http://askubuntu.com/questions/8498/how-can-i-make-the-draggable-window-border-thicker-without-changing-the-appeara
        
https://bugs.launchpad.net/metacity/+bug/160311

        /usr/share/themes/Ambiant-MATE/metacity-1/metacity-theme-1.xml

        <frame_geometry name="frame_geometry_normal" title_scale="medium" rounded_top_left="true" rounded_top_right="true" roun$
          <distance name="left_width" value="4"/>
          <distance name="right_width" value="4"/>
          <distance name="bottom_height" value="4"/>
          <distance name="left_titlebar_edge" value="10"/>

**Comment by raveit65** [comment]
Sorry, this is related to your theme, Ambiant-MATE is not an official Mate theme.
This has nothing to with marco, marco displays the values of your theme.
Personal i've no probs to select a border with my wirless mouse from a theme which use 1px or 2px border size.

**Comment by mixmastamyk** [comment]
Where would you recommend to file this bug?

**Comment by raveit65** [comment]
It's not a bug, it's more a question of taste by theme artist.
I do not know anything about ubuntu release packages (me: fedora maintainer),
...maybe somewhere in ubuntu bug reporting system?

**Comment by raveit65** [comment]
...or at theme home page

**Comment by alecz20** [comment]
I think the idea would be to have an invisible area around the border that would allow grabbing it regardless of the thickness. This would apply to all themes. So while the border would have the thickness specified in the theme file, it could be grabbed a couple pixels around it.

Is this an enhancement possible in Mate-desktop?
Gnome has a similar suggestion in comment #5 of this bug: https://bugzilla.gnome.org/show_bug.cgi?id=496536

**Comment by mixmastamyk** [comment]
Moved to:  https://bugs.launchpad.net/ubuntu-mate/+bug/1446351

Thanks,
