### ISSUE TITLE
transparency inside file manager

### ISSUE THREAD

**Issue by kasalolek** [mate-desktop/marco#245]
I very like Mate console with transparency to wallpaper - its simple and practical. I realy want this efect in file manager, in oposit way like in KDE:
<img src="http://img10.deviantart.net/bc5d/i/2012/165/6/e/kde_transparent_by_jdgr00-d53fyql.png">
i want only transparent files section to wallper.

**Comment by monsta** [comment]
It should be reported at https://github.com/mate-desktop/caja/issues - and please try to give more details about it.
