### ISSUE TITLE
GTK+3: marco-theme-viewer isn't buildable

### ISSUE THREAD

**Issue by monsta** [mate-desktop/marco#246]
That's why it's currently disabled for GTK+3 build. But eventually we'll have to fix it. It's not very nice to ship a manpage for the app but not the app itself :smile:
##

**Comment by raveit65** [comment]
@monsta 
Do we really need this viewer?
I never use them :smile:

**Comment by monsta** [comment]
Well, it's not critical at all of course... so it's "nice to have" category :smile:

**Comment by raveit65** [comment]
I should add another categories.
SAVE TO DROP
and
WILL BREAK OUR TRANSITION TO GTK3 BECAUSE NOBODY WORKS ON IT

:smile:

**Comment by monsta** [comment]
:laughing:

**Comment by monsta** [comment]
Ok, build is fixed now. Theme viewer actually runs and shows something, though it has some visual issues with GTK+ 3.22. With 3.18 it looks better.
I didn't fix any remaining deprecations yet. Gotta pick some fixes from [here](https://git.gnome.org/browse/metacity/log/src/ui/theme-viewer.c) I think...

**Comment by monsta** [comment]
Let's close it, we can open a new report for the remaining visual issues.
