### ISSUE TITLE
panel tray corruption with Marco 1.13 only

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/marco#247]
https://github.com/mate-desktop/mate-panel/issues/394  turned out to be specific to running Marco 1.13  (EDIT: marco 1.12 also affected )on a slow machine (Intel Atom netbook). Sometimes the panel tray background and icon images are corrupted, interacting with them can stop the corruption but changing workspaces corrupts the tray anew. This happens with or without compositing. Does not happen with Marco 1.12 nor with compiz, thus is a new Marco issue.

Since this does not happen with any git master build of marco prior to the 1.13 transition, I suspect some conditional is changing the build on an odd-numbered (dev) version and creating this issue. Similar conditional had to be fixed to let mate-terminal 1.13 build at all.

**Comment by lukefromdc** [comment]
On further work I found that the last versions of Marco 1.12 also had this problem, but I have to move the tray to invoke it (issue does not always appear with any version so hard to diagnose). More tests coming to get exact first bad version

**Comment by lukefromdc** [comment]
The last version of Marco 1.10 I have (9-24-2015) is good, so far free of this issue. First version of 1.12 I have is bad-but only with recent versions of mate-panel, so it is some kind of interaction and on fast machines does not occur. I think i still have the 1.11 versions elsewhere, will test them when I can get to them. I've got a debian package built for each commit but not sure if I still have the old 1.11 versions saved anywhere. At any rate this issue was not invoked until recent mate-panel changes, LOTS of background fixes there

**Comment by lukefromdc** [comment]
OK,I just tested the 1.11 versions I saved as Debian packages. The version I built on Oct 25, whose last commit was 
https://github.com/mate-desktop/marco/commit/eceb8d7994859c4ebbee493539a6ce6fd2842e50 
window: initialize custom_frame_extents 

was good. The next version I has was an Oct 31 build of 1.11.1. The only actual code changes there (as opposed to NEWS updates) was the combined merge of the "extents" branch from which the previous good commit and those that led to it came and the "window-move crash fix" branch. One way of invoking the panel corruption is in fact to move the tray on the panel, which is moving a window. 

The only commit still shown on the timeline after those branches were merged between the 1.11.1 release and the last good one is
https://github.com/mate-desktop/marco/commit/0303e70565fe5a0ede31c2c4591028ed34cbb3a2

 window: initialize fullscreen to FALSE

Not sure if that had anything to do with the window move bugfix referred to in my changelogs and in the NEWS file

**Comment by monsta** [comment]
Oh, https://github.com/mate-desktop/marco/commit/0303e70565fe5a0ede31c2c4591028ed34cbb3a2 actually does nothing. Back then I completely overlooked the fact that the same initialization already was there 10 lines above. Later I removed this excessive initialization in https://github.com/mate-desktop/marco/commit/a04f17f520ffb8d0282dcc1e3a7094b29edc0471.

**Comment by lukefromdc** [comment]
This now appears to be an Intel driver bug though I am not sure. All mate-panel
versions all the way back to 1.10.0 (oldest I have around) affected, marco versions
back to well before it showed up also affected. Intel x driver updated Jan 2 and the 
but showed up only recently and the laptop has not had much use since then.

Also, setting an image background seems to prevent tray corruption entirely, though
more testing is needed to be sure. Thus, this appears to be a driver bug hit by 
fairly recent versions of marco with any version of mate-panel, with a workaround.

If the driver bug still exists when distros ship MATE 1.14 with gtk3, they might need
to include in in "known issues." a note to user of pre-Poulsbo Intel Atom netbooks
set a panel BG image.

**Comment by monsta** [comment]
Ok... is this still an issue?
Given the previous comments, I really doubt it's Marco misbehaving.

**Comment by lukefromdc** [comment]
I haven't seen this in many months on my netbook, must have been a 
driver issue that came and went, invoking some corner case. As far as 
I am concerned this can be closed

**Comment by monsta** [comment]
Ok, closing it then.
