### ISSUE TITLE
Error when creating 2 new folders without confirm name

### ISSUE THREAD

**Issue by Filipizaum** [mate-desktop/marco#258]
Linux Mint 17.1 'Rebecca' MATE 64-bits

Always when you create a folder and, befora set its name, right click on the white space, create another folder and set the name. Will appear the message 'Does not exists "" on this folder. Maybe it was deleted or moved?'

The correct behaviour would be seting the name of the first folder and show no error message.

**Comment by meequz** [comment]
I think it's Caja issue, not Marco.

**Comment by monsta** [comment]
It is. Please reopen the issue in Caja repo (github doesn't allow to move issues between repos).
