### ISSUE TITLE
Crashing when composition (by software) is enable when I want to watch open windows

### ISSUE THREAD

**Issue by jorgicio** [mate-desktop/marco#262]
Marco crashes when I have composite enabled when I want to go through all open windows (with the TAB key). However with compton and with composite disabled work in both cases, but not with composite by software.

**Comment by raveit65** [comment]
I guess you use non distro and don't don't know the version, and maybe you think you're are the only one who use Mate ;)
Hard to reproduce it w/o this info's.

**Comment by jorgicio** [comment]
Hey! You don't need to be sarcastic, right?

Using MATE 1.14.0 in Gentoo, 64 bit.

**Comment by raveit65** [comment]
Hey! You're really the first one who hides important info's ;)

**Comment by raveit65** [comment]
By the way, did you file out a downstream report first in Gentoo, to be shure that it isn't a packager issue?

**Comment by monsta** [comment]
Sorry, my bad with this one. Fixed it in https://github.com/mate-desktop/marco/commit/758e41a133afb4e95dd91f1cbb66039f7636e4e3.
