### ISSUE TITLE
Main window disappears when messages appear in detached channels

### ISSUE THREAD

**Issue by ThomasWeber** [mate-desktop/marco#265]
I keep the main window and 2 detached channels showing on my second monitor. Ever since updating to the latest version on Win7, whenever a message appears in one of the detached windows, the main window disappears for a brief second then returns.

**Comment by raveit65** [comment]
Win7 ???

**Comment by ThomasWeber** [comment]
Whoops, somehow I managed to post this issue in the entirely wrong place.
