### ISSUE TITLE
Wrap settings are incorrectly assigned

### ISSUE THREAD

**Issue by dhasenan** [mate-desktop/marco#266]
From the description in dconf, setting org.mate.marco.general.wrap-style:

`If set to "classic", the old marco behavior is used: the end of one row leads to the beginning of the next and the end of a column leads to the beginning of the next. If set to "toroidal", workspaces are connected like a doughnut: the end of each row leads to its own beginning and the end of each column leads to its own beginning.`

I have four workspaces, arranged like:

```
  +---+---+
  | 1 | 2 |
  +---+---+
  | 3 | 4 |
  +---+---+
```

I have set wrap-style to toroidal. According to the docs, if I move right from workspace 2, I should land on workspace 1. Instead, I land on workspace 3.

I change wrap-style to classic. According to the docs, if I move right from workspace 2, I should land on workspace 3. Instead, I land on workspace 1.

It looks like someone just swapped 'classic' and 'toroidal' in the code.

Observed in 1.12.1 and several earlier versions. I haven't observed a version without this error.
##

**Comment by raveit65** [comment]
Yes, description doesn't match reality.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/marco/commit/5a92d0b24a661e160c98c7ecfaf7da0b043d4ef6
