### ISSUE TITLE
For CSD widgets, when they are lost focus, gtk3:backdrop style has no effect

### ISSUE THREAD

**Issue by ghostplant** [mate-desktop/marco#267]
.window-frame:backdrop {
    box-shadow: 0 5px 5px rgba(0, 0, 0, 0.4);
}
##

**Comment by monsta** [comment]
@raveit65 @lukefromdc guys, I think you would know more about this than me :smile:

**Comment by raveit65** [comment]
Yes, marco ignore the backdrop state which is the opposite of focus.
Which works with metacity or muffin, but i couldn't found a commit about in metacity.

**Comment by raveit65** [comment]
Btw. this is unreleated to CSD windows, the backdrop state can be used in most other widgets.

**Comment by ghostplant** [comment]
metacity 3.18.4  --  src/ui/theme.c:  meta_frame_layout_sync_with_style() function have some configuration of GTK_STATE_FLAG_BACKDROP

**Comment by raveit65** [comment]
fixed with https://github.com/mate-desktop/marco/commit/42410fe72d0ed2c654631e1755526482a80f4fca

Note, most of our themes needs to be re-worked for this.
