### ISSUE TITLE
WM changes to click to focus mode after using KeepAss

### ISSUE THREAD

**Issue by paulguy** [mate-desktop/marco#268]
When using keepass, usually after copying a password to paste in to another application (but it seems to just happen whenever at random, even just as the main window comes up.), the window manager will switch to having to click windows to focus.  I normally have the "Select windows when the mouse moves over them" option set.  Toggling this option does nothing after it decides to screw up in this way.  The only way to bring it back to sanity is to run `marco --replace` from the run window.  I'm sure this is something that keepass or mono is doing wrong, but the appropriate response isn't to break like that.  This (and the panel disappearing bug) are things that are really making me want to switch to something different, because they are very annoying.

MATE 1.12.0, marco 1.12.0.  I know 1.14 is out but there's nothing in the commit log since then that would indicate that this has been fixed, and updating would be a pain because there's no real clean way to restart MATE that I know of without totally logging out and logging back in.  This also happened with MATE 1.10 and that's as far back as I've used MATE.
keepass 2.32, happened also with keepass 2.31, maybe earlier but I don't recall what other versions I've used.
xsel 1.2.0, not sure if this is relevant but keepass utilizes it.
mono 3.12.1

**Comment by raveit65** [comment]
Hmm, i'm using keepass for myself + "Select windows when the mouse moves over them" option in fedora since 2 years, and i never noticed such a issue with marco.
But my crystal ball as dead so i don't know which distro are you using ;)
I'm so bored about that users forgot to tell important infos like this in 90% of our reports.
Maybe you think your distro is the only one in linux world :smile:

**Comment by paulguy** [comment]
Snarky comments aside, I'm using Gentoo.

With that sort of attitude, I'm honestly more apt to switch anyway.  You can honestly keep your crap broken if that's your attitude.  This sort of response is the problem with open source.  I really want to believe in it but people like you ruin it.

**Comment by raveit65** [comment]
Bad attitude !!
