### ISSUE TITLE
Add an option to enable or disable vertical sync 

### ISSUE THREAD

**Issue by Lukypie** [mate-desktop/marco#271]
Maybe it was already asked but I think that in a modern desktop tearing-free windows and general user experience also into the web browser is required, even if with mate you can change the wm I will prefer having this feature in marco.
##

**Comment by monsta** [comment]
Should be solved now, as https://github.com/mate-desktop/marco/issues/326 is fixed by https://github.com/mate-desktop/marco/pull/350.
