### ISSUE TITLE
Ctrl Alt Delete window is not poped up

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/marco#274]
Ctrl alt delete keyboard combination shows up system exit actions (shutdown hiberntae etc). After pressing Ctrl Alt delete it is unable to navigate in this dialog cause it is not active

**Comment by Yanpas** [comment]
To reproduce issue just press ctrl-alt-del, select cancel, then again press ctrl-alt-delete

**Comment by monsta** [comment]
Do you mean it's not getting focus on the second try? I can reproduce that, yes.

**Comment by Yanpas** [comment]
Yes

**Comment by monsta** [comment]
Ok... but it's not in Marco. It's in mate-session-manager. You can launch this dialog from the terminal:

```
$ mate-session-save --shutdown-dialog
```

GitHub doesn't allow moving bug reports between repos... so please open a new report in m-s-m.
