### ISSUE TITLE
Corrupted decorations with GTK 3.21.3

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/marco#276]
The new develoment GTK 3.21.3 causes Marco to render window decorations always either black or transparent, and in all cases with no min/max/close buttons. Compiz works fine. These warnings show up, don't know if they are related:

$ marco --replace
Window manager warning: Log level 16: g_object_set_valist: object class 'MetaFrames' has no property named 'type'
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.
Window manager warning: Log level 16: MetaFrames 0x2657140 is drawn without a current allocation. This should not happen.

**Comment by albertsmuktupavels** [comment]
https://git.gnome.org/browse/gtk+/commit/?id=40ee61a686826ac8e937af720bc152895b10392b
Might fix your problem...

**Comment by monsta** [comment]
Firefox...?

**Comment by albertsmuktupavels** [comment]
It has nothing to do with firefox if that was about my comment. Read commit message - double buffering that is disabled in firefox. Marco does same thing... Search for gtk_widget_set_double_buffered in frames.c.

**Comment by lukefromdc** [comment]
Firefox was the other of two offenders here. If double buffering turned off is
the problem (you should see what trying that with caja did!), I will try turning it
back on for Marco, and if that works pull FF source and see if I can fix it there
too, It that works in both cases I will keep current GTK 3.21 installed and use
an instance of nautilus-desktop for the desktop icons until I or someone else
find a fix for  

https://github.com/mate-desktop/caja/issues/575

 in Caja

**Comment by lukefromdc** [comment]
This was just fixed in GTK 3.21.3 today, only Caja issue remains. Should I close this or leave it open? This is fixed with GIT master GTK3 but the fix won't reach a tarball (and Fedora Rawhide etc) until GTK 3.21.4 is released.

Marco now works just fine but comments on GTK commit say "let's keep backwards compatibility with the old code for a little while longer."  Hope that means until GTK4, they've only got one more version (3.24) until they say they will branch that. Tonight I will test the double buffer change against the Sunday's version of GTK 3.21.3 just for "future-proofing" as this might only last until Firefox makes changes.

**Comment by lukefromdc** [comment]
I just did some testing with Marco: the new GTK commit only fixes it so long as the  gtk_widget_set_double_buffered in frames.c is kept and set to "FALSE". Setting it to "TRUE" or removing that line brings the problem back.  GTK 3.21 master now uses that "FALSE" for double_buffer to trigger a special case workaround it seems.

**Comment by monsta** [comment]
@albertsmuktupavels: thanks - I didn't realize how it's related at first.

@lukefromdc: I guess you can close it if it's fixed, we can always reopen it if it happens again.

**Comment by lukefromdc** [comment]
Closing unless another GTK change brings this back.  Will almost certainly have to be revisited for GTK3 but estimate 3 years to 1st "stable" release of that.
