### ISSUE TITLE
Remove windows decorations

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [mate-desktop/marco#277]
Hello,

how do I remove window decorations? I do video records and live streams and I need to remove window decorations since resizing/cropping the title would make the window stretched and ugly looking.
Please do not tell me to switch window manager to another product.

Thank you for your time.
##

**Comment by lukefromdc** [comment]
Best approach: fullscreen if the application supports it, as most video players do.

**Comment by Ganjalf-Amsterdoom** [comment]
Hello,

thank you for the quick reply, I've got a pretty complex multi monitor setup and going full screen will make the window span between 3 monitors, not an option. I could waste a week of xorg configuration to have separate monitor tough....

Anyhow thank you for your time, I just found an old issue in which it was told this will not be added to mate.

**Comment by kn00tcn** [comment]
what are you recording with, cant you crop & pan the recording area? which applications are you trying to record?

you might be able to make a custom window border theme that purposely is empty or at most 1 pixel borders as a workaround
