### ISSUE TITLE
Integrate upstream patches from metacity for new-window-always-on-top 

### ISSUE THREAD

**Issue by slseed1969** [mate-desktop/marco#279]
I posted a pull request back in April but have not seen any updates or comments on it so I'm opening an issue to go along with it.  Here are the details...

These changes correspond with the fixes associated with Red Hat Bugzilla #530263

The normal behavior is that if a new window is not given the
focus (since, for example, the user has interacted with another
window after launching an application), then if the window would
be stacked on top of the focus window, the window is instead
stacked beneath and flashed in the taskbar. This behavior can
be annoying on large screens and multihead setups where the
taskbar is hard to notice and difficult to get to, so this option,
if set, disables this behavior, and new windows are always placed
on top, whether or not they get focus.

Note that if this option is set, a new window may completely hide
the focus window but not get focus itself, which can be quite confusing
to users. Also, note that setting this option breaks the normal
invariant in the 'click' focus mode that the topmost window always
has focus, so its most suitable for use with the 'mouse' and
'sloppy' focus modes.

Upstream bug is https://bugzilla.gnome.org/show_bug.cgi?id=599261

**Comment by monsta** [comment]
We'll get to that PR sooner or later, be patient please. Our team is too small these days.
