### ISSUE TITLE
Qt Widget setPalette() in QComboBox confuses marco compositor

### ISSUE THREAD

**Issue by bitness** [mate-desktop/marco#282]
Hello,

We've found that an application using Qt's QComboBox can cause marco's compositor to leave copies of the combo box's menu on the screen. Our test case (attached here) shows this happens if the combo box's palette is changed. If you modify the test case to comment out the setPalette() call, the problem doesn't happen.

The copies of the menus can't be moved. They're transparent to mouse and keyboard events--the events go to the window underneath them.

If the compositing manager is disabled with dconf, the problem goes away immediately: all the incorrect menu copies disappear from the screen and don't return. Toggling the compositor back on lets the test case reproduce the problem again.

This is happening on RHEL7 (Qt 4.8.5) with marco 1.14.2. Interestingly, it doesn't happen with metacity, though the codebases between metacity and marco are very similar.

This bug is making our in-house software suite very difficult to use, as well as some third-party tools whose source we don't control. Any ideas or clues about what might be causing this?

Thanks very much!
-lars

[palette-bug.py.txt](https://github.com/mate-desktop/marco/files/404380/palette-bug.py.txt)
##

**Comment by bitness** [comment]
Here's a crappy little screencast that shows what I'm seeing with this test case.

thanks,
-lars

![marco-compositor-issue](https://cloud.githubusercontent.com/assets/318366/17785531/15d5f30c-6536-11e6-9176-b2e15974a3bc.gif)

**Comment by bitness** [comment]
Turns out this is fixed in Metacity commit 95a568e6ecf9bd6acb6900daa9703916f053a80a. Can we have this simple patch applied to Marco? Thanks!

**Comment by monsta** [comment]
Looks like https://github.com/mate-desktop/marco/issues/324 is a copy of this, and it's fixed now. Closing.
