### ISSUE TITLE
Marco with compton on Ubuntu MATE stops some games launching in fullscreen

### ISSUE THREAD

**Issue by LiamDawe** [mate-desktop/marco#284]
A weird one, but I will try to explain as best as I can.

I am running the latest Ubuntu MATE, I had my Window Manager set to "Marco (Compton GPU Compositor)" in MATE Tweak.

For some reason using that breaks some fullscreen games like Company of Heroes 2. The game will refuse to give me fullscreen.

Switching to Compiz instantly made the game work.

So Marco somehow is interfering with full-screen OpenGL applications.
##

**Comment by kn00tcn** [comment]
you mean compton, which isnt supported by official mate team here i dont think (it MIGHT be by the ubuntu mate team)

compton has quite a few tweaks, i have been testing it out recently on fedora mate & xfce

i never got around to trying steam on linux, do you have the same problem in something like openarena that i can also test?

boy this gave me an idea for a useful package, imagine something that triggers a windowed & fullscreen application across multiple opengl versions, maybe with some 3d object & a benchmark for the purposes of testing

**Comment by LiamDawe** [comment]
Sorry, don't use MATE any more to test and it likely wouldn't happen to non-steam games.

**Comment by kn00tcn** [comment]
compton also runs on xfce & others

if i ever get around to testing steam on linux, i might check this just out of curiosity (i do own coh2)

**Comment by monsta** [comment]
Since it involves running Compton alongside with Marco, it's better be reported at Ubuntu MATE bugtracker.
