### ISSUE TITLE
grave breakage on debian stretch

### ISSUE THREAD

**Issue by JazzMaster** [mate-desktop/marco#285]
the past few days whatever we pushed is broken.
icons have heavy drop shadows, cant be moved, major desktop blurrage..
dont even ask for compton, marco is required to render the windows..even though openbox is there?

I dont get it.
Broken. Beyond all hell.
Unuseable.

Is this is response to an ATI driver mutation? possibly. LiberO is horribly broken also in places such as color text rendering.(but it saves changes?) and the super current edition displays old-school buffer artifacting on the rendered window. Try it and youll see what I mean. Use the version from thier website.

The root cause may in fact be to both, a broken ati driver. And it seems so.
I know I can push 3500fps on this Radeon 6xxx APU and over 5300 on a SINGLE(I have two) 7850. Yes, Ive clocked it.

Open driver gets just under 1k less that this. This was a fudged closed source catalyst hack. Capable, yes. Broken often seems to be the case. (and we SHOULD be depending on 3d/GPU to render..)
##

**Comment by JazzMaster** [comment]
debian team doesnt give a shit about my bugs. despite finding major security flaws in thier os.

**Comment by raveit65** [comment]
> debian team doesn't give a shit about my bugs. despite finding major security flaws in thier os.

Debian Mate maintainer also ignored our strongly advise to use our development releases for stretch.
Adjustments for gtk+3.21.x are in 1.15/16. 
I suggest not use Mate in debian test releases until they use 1.16 builds.
.....try out fedora 25 alpha, here the Mate maintainer is much flexible and fixes issues very fast;)

**Comment by raveit65** [comment]
please wrote here if the bug isn't fixed .
