### ISSUE TITLE
pangoxft dependency

### ISSUE THREAD

**Issue by NP-Hardass** [mate-desktop/marco#288]
Looking over the source and configure.ac, I'm a little confused as to why pangoxft is required.

The only header inclusion form pango is [pango/pango-font.h](https://github.com/mate-desktop/marco/blob/6c5b3375d0562e4244de369c4d365efb90f11e32/src/include/prefs.h#L30) 

Additionally, the pango-font.h header has several ifdefs for if it has a backend, but does not specify what backend.  Those structures, we don't appear to be using AFAICT.  Those are:  PangoFontMetrics, PangoFontFamilyClass, PangoFontFaceClass, and PangoFontClass.  Even if we do need one of those (which I don't think we do), there are several backends (cairo, freetype2, xft), any of which provide that support, so why is pangoxft specifically being checked?
##

**Comment by monsta** [comment]
Looks like it's not needed at all, so I removed that block.
