### ISSUE TITLE
FIX Mouse preference "Show position of pointer when the Control Key is pressed" causes form input to lose focus

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/marco#302]
## How to reproduce:

1. open Mouse preferences
1. enable  "Show position of pointer when the Control Key is pressed"
1.  open a GTK application with forms (like DBeaver)
1.  double click on a text input field to enter edit mode (with blinking cursor)
1.  try to paste something with Ctrl + V

## Expected behaviour:

text is pasted into input field, edit mode and focus remains

## Actual behaviour:

Mouse cursor position effect is displayed and input field looses focus (goes out of edit mode) without pasting anything

**Comment by monsta** [comment]
Should be fixed by https://github.com/mate-desktop/mate-settings-daemon/commit/3e295156e3bd77007984dedf8d326b6c412ff925 (m-s-d 1.18.1, 1.16.2).
