### ISSUE TITLE
crashes when window title is long

### ISSUE THREAD

**Issue by sciamano** [mate-desktop/marco#306]
I'm using debian-testing version 1.16.0-1 and marco crashes every time when a window title becomes "long".
With a simple example:
`xterm -xrm 'XTerm.vt100.allowTitleOps: false' -T 123456789+123456789+123456789+123456789+123456789+1234`
and marco running as
`MARCO_DEBUG=1 MARCO_VERBOSE=1 MARCO_USE_LOGFILE=1 marco --replace`
it has crashed and produced
https://gist.github.com/sciamano/47dc4496592ee77ac272277ae3c318e2

**Comment by twiddle** [comment]
Just arrived at the same conclusion. I have a directory that if I 'cd' into, via MATE Terminal, a split-second later Marco crashes the desktop back to login. MATE Terminal is re-writing the cwd in the title bar. 

Changing the 'window title' font size from 10 to 9 fixes the problem, until I again exceed the window width by going into a deeper directory. Resizing the window width will also trigger the bug.

**Comment by twiddle** [comment]
I found that this problem goes away if I disable sub-pixel rendering in the font settings.

**Comment by sciamano** [comment]
thanks for the hint, the sub-pixel fix seems to work for me as well. I also found, that the crash happens when i use intel video card, but the same setup with an amd video card works.

**Comment by twiddle** [comment]
Yes, I'm on intel too. Looks like Marco is tickling a bug in xserver-xorg-video-intel possibly via the XRENDER extension.
