### ISSUE TITLE
Support for window preview thumbnails?

### ISSUE THREAD

**Issue by kq01526** [mate-desktop/marco#307]
Hi,

@robint99 , the dev behind mate-dock-applet was approached to implement window preview thumbnails into mate-dock-applet, but apparently it doesn't seem to be too easy, see:

https://github.com/robint99/mate-dock-applet/issues/49

Could you possibly give some advice and elaborate if this would even be possible with Marco?

**Comment by kn00tcn** [comment]
it's easy for the compositor since it has direct access to each window, it's harder for an unrelated dock to do it as seen in that thread

**Comment by monsta** [comment]
That's why Compiz exists. We don't have to add that to Marco.
