### ISSUE TITLE
DRI3/Present support to avoid tearing

### ISSUE THREAD

**Issue by ghost** [mate-desktop/marco#313]
Does marco has X Present extension support or plans to have it? It solves tearing issue on DRI3-aware opensource videodrivers. It already implemented in git xfwm4 and currently is the main reason I stick to XFCE on Intel GPU.

**Comment by monsta** [comment]
I don't think we have it, but if it would solve the tearing problem, it would be a good addition. Pull requests are welcome.

**Comment by pasikarkkainen** [comment]
Yep, tearing with marco/mate is very annoying. Is anyone currently working on this?

**Comment by vkareh** [comment]
This is a duplicate of #326 - I suggest closing this one and keep the conversation going in the other one, as it has more relevant information.
