### ISSUE TITLE
[Feature Request]: Show workspaces when moving windows with the keyboard? [$15]

### ISSUE THREAD

**Issue by orschiro** [mate-desktop/marco#314]
Dear all, 

This request originated from the [Ubuntu MATE](https://ubuntu-mate.community/t/show-workspaces-when-moving-windows/12668/2) community.

I love the keyboard shortcuts to switch workspaces and to move the active window across different workspaces. 

However, while I do see on which workspace I am when switching workspaces, I lack this indication when moving the active window across the workspaces. 

Such as indication would be incredibly helpful to place the active window at the appropriate workspace. 

What are your thoughts?

Yours,

Robert

**Comment by orschiro** [comment]
Show this when moving windows across workspaces:

![show workspace switch](https://cloud.githubusercontent.com/assets/170947/25452278/5bd39c38-2ac5-11e7-96af-6a9e71a56ff5.png)

**Comment by orschiro** [comment]
Any further thoughts or opinions on this request?

**Comment by samtygier** [comment]
Sounded simple enough so I had a look at the code. Looks like more than an afternoon project, so here are my notes in case anyone else has time to pick this up before I get back to it.

The popup indicator is called TabPopup, and lives in tabpopup.c.

Workspace switching and window moving are somewhat similar. The respective keybindings call handle_switch_to_workspace() or handle_move_to_workspace(). The can be relative (left, right) or absolute (go to desktop x). switch shows the TabPopup on relative switches. Move only switches desktop on relative moves (flip=True). So it looks like the smart thing to do is to merge the 2 functionalities into say handle_switch_and_move_to_workspace(), which can take an additional bool to say if the window is moving.

This works for the first movement. But if you keep the SHIFT+CTRL+ALT held down, then you stay in the grab, and everything is done by meta_display_process_key_event() calling process_workspace_switch_grab(). This seems to reimplement various things and does things with modifier masks that I have not figured out yet.

**Comment by ozeidan** [comment]
Hi,
I implemented this, see PR #366.
Could you please try if the patch works on your machine, @orschiro? Thanks

**Comment by orschiro** [comment]
@ozeidan thanks so much for your PR! 

I don't have MATE installed at the moment and cannot test. 

Anyone else?

**Comment by TomaszGasior** [comment]
Patch works great! Like it, without issues.

**Comment by orschiro** [comment]
Now it just needs to be merged and you can claim your bounty, @ozeidan :-)

**Comment by sc0w** [comment]
merged with https://github.com/mate-desktop/marco/commit/9e2b7eff713b6881a60538e08e222dad0d364647 and https://github.com/mate-desktop/marco/commit/52701a81d82cd89525ed883cb046f11f384c8d6c
