### ISSUE TITLE
Chrome/Chromium stuck maximised on secondary screen with Marco

### ISSUE THREAD

**Issue by Kallestofeles** [mate-desktop/marco#316]
Hello,

A strange issue which happens only with Marco WM.
When maximising the Chrome/Chromium window on a secondary monitor, I can no longer control the window. Cannot minimise it, resize it, nor move it. I can only close the window.
Best to explain the behaviour with a video:
[https://goo.gl/photos/sLFUgniFs5niVyC66](url=https://goo.gl/photos/sLFUgniFs5niVyC66)
In the video, the Picture in Picture screen is the primary screen1 and the big screen on the background is the secondary screen2. Resolutions are the same and the issue only occurs while using Marco WM. (tested with xfwm, compiz0.9, mutter, all work fine except Marco)

Sidenote: when viewing the video, please don't mind the background picture, it means no offence.

If there is any info or details I could provide, please let me know, I'm happy to help as I wish this to get resolved.

OS: Arch Linux
Kernel: x86_64 Linux 4.10.11-1-ARCH
DE: MATE 1.18.0
WM: Metacity (Marco)
marco 1.18.0-1

Thank you!

Best regards,
Kalle

**Comment by Kallestofeles** [comment]
Update:
Also happens with Steam.
Looks like it's related to non-native window decorations and Marco.

**Comment by muktupavels** [comment]
Did you try Metacity? Does it work? If you test with it, please tell also version that you used for testing.

**Comment by Kallestofeles** [comment]
Hi muktupavels,

Thank you for responding!
Tried now with pure Metacity and the issue persists with that as well. So if I'm right, then Marco is built upon metacity but the issue is with that. Hmmh.
`[kallestofeles@Shoemaster ~]$ metacity --version
metacity 3.24.1
`

**Comment by muktupavels** [comment]
I think I was able to reproduce this bug / problem. Can you please open upstream bug for metacity:
https://bugzilla.gnome.org/enter_bug.cgi?product=metacity

**Comment by Kallestofeles** [comment]
Created the case with Gnome team:
https://bugzilla.gnome.org/show_bug.cgi?id=781946
Issue can be resolved by issuing "--no-force-fullscreen" option when starting Marco/Metacity. This should be the default as I cannot see any drawbacks so far... I'll update if I find anything.

**Comment by deltragon** [comment]
I have encountered the same issue, but I've found a workaround for Chrome: right clicking Chrome's window decorator gives you an option to "Use system title bar and borders", which resolves it (even if it looks a bit ugly).

**Comment by Kallestofeles** [comment]
@deltragon Issue can be resolved by issuing "--no-force-fullscreen" option when starting Marco/Metacity.
That way you can keep the nice non-native decorations.

**Comment by rcaridade145** [comment]
For reference this https://gitlab.gnome.org/GNOME/metacity/commit/1fafd279006ece8cf664fd777143cdfafbefad6d was the commit that fixed the issue on Metacity

**Comment by raveit65** [comment]
I can confirm that it happens with chromium/chrome if "use system titlebar and border" option is unchecked.
I doesn't happen when normal marco/metacity decorations are used.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/marco/pull/581 seems to fix the problem.
