### ISSUE TITLE
unable to parse 'BACKGROUND'

### ISSUE THREAD

**Issue by helicities** [mate-desktop/marco#317]
I am reporting a regression affecting x11 windows that seems to be introduced by the change to GTK3. I am using the latest Mate 18 under RHEL, as provided by raveit65 through Fedora's copr service. 

In x11 applications, like gnuplot or emacs, I get the message 

`unable to parse 'BACKGROUND'. Using black.`

with the obvious result that the background of the x11 window stays black.

The issue is resolved by switching back to Mate 1.16 as provided by epel.

**Comment by raveit65** [comment]
I am not using this apps, i prefer vim, but all this apps are running inside a terminal, right?
In centos7 VM with my gtk3 coprs repo i don't see that warning.
```
[rave@localhost ~]$ gnuplot

	G N U P L O T
	Version 4.6 patchlevel 2    last modified 2013-03-14 
	Build System: Linux x86_64

	Copyright (C) 1986-1993, 1998, 2004, 2007-2013
	Thomas Williams, Colin Kelley and many others

	gnuplot home:     http://www.gnuplot.info
	faq, bugs, etc:   type "help FAQ"
	immediate help:   type "help"  (plot window: hit 'h')

Terminal type set to 'x11'
gnuplot> 
```
Can you please describe more details how do you get this warning?

**Comment by helicities** [comment]
Thanks for your reply. To encounter the warning I need to create a x11 window. In gnuplot that can be done by "pl x" (i.e.  plot the function y=x):

```
[ion ~]$ gnuplot

        G N U P L O T
        Version 4.6 patchlevel 2    last modified 2013-03-14 
        Build System: Linux x86_64

        Copyright (C) 1986-1993, 1998, 2004, 2007-2013
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h')

Terminal type set to 'x11'
gnuplot> pl x

gnuplot: unable to parse 'BACKGROUND'. Using black.
gnuplot> 

```

Please find below a picture showing the resulting gnuplot window:

![screenshot at 2017-05-02 23-32-42](https://cloud.githubusercontent.com/assets/26922890/25640717/f86bc47e-2f90-11e7-8108-67df5f85ff6b.png)

**Comment by raveit65** [comment]
I can confirm this with rhel7, but not with fedora. With f26 it works with MATE-1.18 (gtk3).
Here the gui looks like Qt and there is a command line 'gnuplot-qt'.
Any ways, i 've no idea why this happens but i found a workaround. Use
```
gnuplot -bg white
```
As this is a x11 option it should work with emacs too.

**Comment by helicities** [comment]
Thank you very much for the workaround. I did some further debugging on this issue. It seems that under Mate 1.18 GTK the Xresources are not properly set. These can be displayed by

```  xrdb  -query ```

Under Mate 1.18 all values are invalid (or set to some generic names). See the following file:
[xrdb_mate_1_18.txt](https://github.com/mate-desktop/marco/files/974410/xrdb_mate_1_18.txt)

Especially, for the background, no valid color is set:

```
*background:	BACKGROUND
```

The `xrdb  -query` command under Mate 1.16 gives correct values like (
[xrdb_mate_1_16.txt](https://github.com/mate-desktop/marco/files/974416/xrdb_mate_1_16.txt)
):

```
*background:    #edeceb
*foreground:    #000000
```

The system-wide default values are defined in /etc/X11/Xresources, 
```
[localhost ~]$ cat /etc/X11/Xresources
! This is the global resources file that is loaded when
! all users log in, as well as for the login screen

! Fix the Xft dpi to 96; this prevents tiny fonts
! or HUGE fonts depending on the screen size.
Xft.dpi: 96

! hintstyle: medium means that (for Postscript fonts) we
! position the stems for maximum constrast and consistency
! but do not force the stems to integral widths. hintnone,
! hintslight, and hintfull are the other possibilities.
Xft.hintstyle: hintmedium
Xft.hinting: true
```
Under Gnome 3, only these few values are shown by `xrdb -query`. Therefore, I suspect that all the other values are defined by Mate. And Mate 1.18 falls back to some generic values like 'BACKGROUND' that cannot be parsed by x11. However, until now, I was not able to figure out where the Xresources are defined by Mate.

**Comment by helicities** [comment]
I also found an other workaround. It is possible to overwrite the settings by

``` 
xrdb ./xrdb_mate_1_16.txt
```

and to use by this approach the same  configurations as defined by Mate 1.16. That resolves for now the problem for all x11 applications. However, I think this issue should be fixed because it basically affects all 'legacy' applications.

**Comment by raveit65** [comment]
Sorry, my fault , your debugging gives me enlightenment again.
I forgot to add this patch for gtk3 build
http://pkgs.fedoraproject.org/cgit/rpms/mate-settings-daemon.git/tree/mate-settings-daemon_fix-xrdb-plugin-for-rhel.patch?h=epel7
This was a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1140329
A fixed build is on the run.

**Comment by raveit65** [comment]
Ok, repo is updated with https://copr.fedorainfracloud.org/coprs/raveit65/Mate-GTK3/build/546628/
Do a 'yum clean all metadata' and restart session.
And thanks for reporting this.
Btw. Do you think it's a good idea to update rhel7 to 1.18, i mean switching to gtk3 during a release?
Mate-1.18 can't build with gtk2 any more.
Maybe it's better to wait for a new enterprise release for that?

**Comment by helicities** [comment]
Thank you very much for fixing the issue. It works great.

I also thought about the update to 1.18 under RHEL. But I think most 
users of RHEL/CENTOS are rather conservative, in the sense that things 
don't need to be changed when not really necessary. Mate 1.16 works just 
excellent under RHEL and I don't see an urgent need for an update.  
Maybe, in the future, an argument for updating would be the support for 
HiDPI. And at the moment, users still have the opportunity to update to 
1.18 through your Copr repository.

**Comment by raveit65** [comment]
@helicities 
This is exactly what i am thinking about rhel/centos users and honestly, there are a few things which don't work with MATE gtk3 like before, or will never work with gtk3, ie. color selecting for window backgrounds.
Can post your opinion here at this report, please? https://bugzilla.redhat.com/show_bug.cgi?id=1436260
Sadly, some users want to have always the hottest and newest stuff.....
