### ISSUE TITLE
Multi-monitor keyboard shortcuts [$25]

### ISSUE THREAD

**Issue by 9a3eedi** [mate-desktop/marco#320]
Currently (as of 1.12.1, not sure about newer versions), there aren't any keybaord shortcuts that can be set to move the current window to the next/previous monitor. I'm constantly forced to use my mouse in order to move the window.

This is something I'm really missing from other window managers, and multi-monitor setups have become very commonplace nowadays (compared to the gnome2 days), so I'd really like to see this.

**Comment by vkareh** [comment]
@9a3eedi - while more of a workaround than an actual solution, I find that if you set the `/org/mate/marco/window-keybindings/move-to-side-[e|n|s|w]` keybindings, you can get a reasonably workable approach to moving between monitors. There are certainly a bunch of quirks with it, but I use these shortcuts for my daily workflow with varying levels of success/frustration :stuck_out_tongue:

**Comment by darkpandarts** [comment]
I would love this feature. In it's absence i would settle for being able to move the window to a named monitor. i.e. move window to monitor1, monitor2,.., etc

**Comment by mbkma** [comment]
@darkpandarts this is already implemented since MATE 1.20, see https://github.com/mate-desktop/marco/pull/371

**Comment by darkpandarts** [comment]
@mbkma hi, i see that it can be moved to different monitors using north, east, west, south notation, but this is overly complex for me because it requires x3-4 buttons (on keyboard or mouse) to be configured, and requires a greater amount of cognitive bandwidth to be utilised.

In contrast, it would be great if you could just have move to next monitor or previous monitor, and bind 2 buttons to cycle through a monitor switching order (mon1 -> mon2 -> mon3 -> mon4 -> mon1....). This is way easier to work with in a 2 up 2 down quad monitor setup as one doesn't have to think much about it as much.

**Comment by darkpandarts** [comment]
was double checking this & yes, you would def need KB shortcuts for

1x move-left
1x move-right
1x move-up
1x move-down

Additionally you would have to think about which of those 4 buttons you need to select.

~~~
The other option is
1x move-next
1x move-back

You can have a vague brain-dead idea which way to go, and click one button with a 50/50 chance of success. If incorrect, just press the other one, or if you are super lazy, just keep smashing the one you incorrectly selected. it cycles round anyway and is super quick if you've mapped the shortcuts to your mouse. See attached pic:

![Selection_003](https://github.com/mate-desktop/marco/assets/114529342/7d3966fd-3484-4230-9763-aaa468a1e9e1)

**Comment by darkpandarts** [comment]
in case anyone is looking for something similar, i found something that has the required functionality

https://github.com/calandoa/movescreen

you can run it by 
```shell
./movescreen.py -r next
```

in the (unlikely) event i get some free time, i'll try ad learn some c so that i can submit a pr with this functionality :)

**Comment by balazs-endresz** [comment]
These instructions worked for me too: https://github.com/calandoa/movescreen?tab=readme-ov-file#xfce-setup but had to change the first line to reference `python3` instead of just `python` (on MATE 22.04). The `next` option does cycle through monitors as well, as requested.

I also had a much shorter script that moves all windows to another monitor but somehow I can't seem to get it working for the active window only: 

```py
#!/usr/bin/env python3
import gi  # sudo apt install python-gi
gi.require_version("Gtk", "3.0")
from gi.repository import GdkX11
if __name__ == "__main__":
    screen = GdkX11.X11Screen.get_default()
    current_monitor = screen.get_monitor_at_window(screen.get_active_window())
    next_monitor = (current_monitor + 1) % screen.get_n_monitors()
    g = screen.get_monitor_geometry(next_monitor)
    window = screen.get_active_window()
    window.move(g.x, g.y)
```

**Comment by darkpandarts** [comment]
@balazs-endresz 

hey there! Glad it worked well for you! :)

Interesting you have the focus problem. What version of ubuntu are you on? 

```
┌──[bsgt]─[koma]
│8: > ~ 
└──14:31─X uname -a
Linux koma 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

┌──[bsgt]─[koma]
│8: > ~ 
└──23:20─$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

I don't have the focus problem you described with 22.04. oddly i have a focus problem with things like "save as" dialogues that do not open in the foreground. i.e. focus does not shift to the new window

**Comment by balazs-endresz** [comment]
@darkpandarts I have the same system but actually with a local build of marco 1.27.0 with this line changed to FALSE: https://github.com/mate-desktop/marco/blob/2d3cec67ab41e70479d75beb5f884e1a4551ea92/src/core/window.c#L1920 That makes it focus every new window even when opened by apps in the background (I don't use such apps). I suppose that change might be interfering with the window move too, so I probably shouldn't have mentioned that.

Those lines from my script are only DeprecationWarnings, but that API still works at the moment. Even `move()` does when I'm moving all windows (`screen.get_window_stack()`) between monitors, but not in this context for some reason.

**Comment by darkpandarts** [comment]
Hmmm, your shorter script did not move the window for me. am i right in thinking that if you change the False back to True, it behaves as expected? i.e. it retains focus?
