### ISSUE TITLE
Don't paint windows that aren't viewable

### ISSUE THREAD

**Issue by bitness** [mate-desktop/marco#324]
Hello,

marco suffers from a bug that causes non-viewable windows to get permanently composited on the screen. This was fixed in metacity last June:

https://git.gnome.org/browse/metacity/commit/?id=a0b8c85c4c0cfb9a378d7c5554af15fdd7703155

Can we please have this fix applied?

Thanks!
-lars

**Comment by raveit65** [comment]
Why we have to always ask for valid infos?
Distro?
marco version
Mate general version?
A detailed bug description which can be reproduced by everybody?
We are not a commercial support!

**Comment by bitness** [comment]
My apologies, I didn't mean to waste any of your time.

I can reproduce this on Fedora 25, with the mate-desktop package version 1.16.2, and marco package version 1.16.1.

I'm attaching a python script that reproduces the issue. (You'll need the PyQt4 RPM to run it). Just click the combo box, select something, then move the window. You'll see the image of the menu get left behind. Note that clicks on the menu image go straight through to the windows underneath.

We've been using the patch I linked above to address this issue for ten months or so, and none of my users have seen the problem since. I'm hoping you'll agree to apply it.

[composite-bug.py.txt](https://github.com/mate-desktop/marco/files/1046128/composite-bug.py.txt)

Thanks,
-lars

**Comment by bitness** [comment]
Here's a screencast showing what the bug looks like when using the repro case I posted.
![marco-compositor-issue](https://cloud.githubusercontent.com/assets/318366/26743746/dbc4bdac-4797-11e7-8fdc-36cba439584b.gif)

**Comment by bitness** [comment]
Thanks!
