### ISSUE TITLE
X11 resource leak causes high Xorg CPU usage and sluggish UI

### ISSUE THREAD

**Issue by brad112358** [mate-desktop/marco#329]
After a login session is more than a few days old (currently 8 days), X consumes more and more CPU time and the user interface becomes very sluggish.

Investigating Xorg with gdb showed a lot of time was being spent in GetXIDRange which is known to be inefficient for large numbers of resources.

xrestop showed marco as the larges resource consumer:
0 - marco ( PID: 2772 ):
        res_base      : 0x3000000
        res_mask      : 0x1fffff
        windows       : 24
        GCs           : 51
        fonts         : 2
        pixmaps       : 34
        pictures      : 52
        glyphsets     : 2
        colormaps     : 0
        passive grabs : 1780
        cursors       : 0
        unknowns      : 288940
        pixmap bytes  : 130435987
        other bytes   : ~6982424
        total bytes   : ~137418411

The "unknowns" resource seems to be constantly growing.  Even when the screen is locked.

This behavior was observed on Ubuntu Mate edition version 16.04.2 LTS, marco package version 1.12.1-1

I can't imagine anything unique to my environment which would cause this so I'm very surprise this hasn't been reported in the past.

Restarting marco restores proper performance

**Comment by raveit65** [comment]
@brad112358 
Does the mentioned PR fixes your issue?
But for applying the fix you need to use a aktual ubuntu version.
Btw. i don't think that ubuntu-16.04 with marco-1.12.x  will ever get a MATE update.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/marco/commit/6cf1369769b94165c3360945deb47621e957c603
