### ISSUE TITLE
Context menu of GTK headerbar

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/marco#334]
#### Actual behaviour
Marco is not integrated with GTK3 headerbars.

#### Expected behaviour
Marco should provide context menu for windows with client side decorations.

#### Steps to reproduce the behaviour
1. Start xfwm4, XFCE4 window manager instead of Marco.
2. Run app without CSD and right-click on the titlebar — you will see window manager menu.
3. Run any app with CSD (dconf-editor for example) and right-click on empty area of headerbar — you will see the same menu as in 2. point.
4. Start Marco.
5. Run app with CSD (dconf-editor for example) and right-click on headerbar — you will see fallback context menu from GTK instead of Marco context menu.

#### Package version
any Marco version

**Comment by monsta** [comment]
As https://github.com/mate-desktop/marco/pull/370 is merged, this can be closed.
