### ISSUE TITLE
Marco should ignore GDK_SCALE so primitive HiDPI works

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/marco#335]
#### Expected behaviour

Exporting `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` into the Xsession should cause the entire MATE Desktop and it's suite of applications to correctly pixel double suitable for use on a computer equipped with a HiDPI display. 

#### Actual behaviour

When `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` are exported to the Xsession most of the MATE Desktop and it's suite of applications do scale correctly. However Marco demonstrates several issues where window and screen dimensions are not correctly calculated when these environment variables are exported. 

It is possible for coerce Marco to behave *"correctly"* when `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` are exported to the Xsession by creating the shell script `/usr/local/bin/marco` the overrides `GDK_SCALE` and `GDK_DPI_SCALE`, here is the script:

```bash
#!/usr/bin/env bash
env GDK_SCALE=1 GDK_DPI_SCALE=1 /usr/bin/marco $@ &
```

Therefore Marco should ignore/override `GDK_SCALE` to ensure operates correctly regardless of what the user has exported to the Xsession.

#### Steps to reproduce the behaviour

Export `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` into the Xsession, this can be done by editing `/etc/profile.d/mate.sh` on Ubuntu MATE 17.10 daily. Reboot and your desktop will be 2x scaled but Marco dimension and screen calculations are incorrect. 

#### MATE general version

MATE Desktop 1.18

#### Package version

Marco 1.18.1

#### Linux Distribution

Ubuntu MATE 17.10 daily.

@muktupavels understands this domain well and the hack above was created based on an IRC conversation we had some weeks ago. Tagging @monsta @XRevan86 and @ikeydoherty as they may be interested in this issue.

A similar bug was raised against `mate-panel`:

  * https://github.com/mate-desktop/mate-panel/issues/621

**Comment by muktupavels** [comment]
https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#gdk-x11-display-set-window-scale
