### ISSUE TITLE
Marco with compositor enabled causes huge fps/performance drop

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/marco#341]
#### Expected behaviour
Compositor should only cause a slight fps drop, not such big as this.

#### Actual behaviour
Compositor causes fps to drop to less than half, comparing to marco without compositor.

#### Steps to reproduce the behaviour
Use marco with it's Compositor enabled.

#### MATE general version
1.18

#### Package version
1.18.1

#### Linux Distribution
Ubuntu MATE 17.04, Ubuntu MATE 17.10, Manjaro.

#### Link to downstream report of your Distribution
I have reproduced this on several distributions, so I have no downstream report.

Using **glxgears**, I've seen that when compositor is disabled, then I get arround 2300 fps on a maximized window. However, when compositor is turned on, then I get arround 1050 fps, which is less than half. Xfwm4 which also has Software compositor causes only a minor fps drop which results to 2000 fps average. I've made a video to show the problem, the fps here are 200-300 lower due to simplescreenrecorder:
https://www.youtube.com/watch?v=zznGWGx712g

Xfwm4 will use OpenGL at it's compositor from the next version (which I haven't tested yet but it is supposed to end screen tearing for good and give even better results). Maybe you can recreate the marco compositor with some in order to fix its behavior?

**Comment by jhasse** [comment]
While 2300 FPS (a complete unrealistic scenario) drops to 1050 FPS, I doubt that anything <250 FPS will show such a performance decrease. Can you test with a game or something similar?

**Comment by monsta** [comment]
I don't see any difference in actual games with and without compositing.
