### ISSUE TITLE
Color tab in Theme Preferences missing

### ISSUE THREAD

**Issue by scytho** [mate-desktop/marco#345]
There is a menu entry _Appearance Preferences_ (under _System > Preferences > Appearance_ or something similar, I’m not using an english installation). That entry openes a dialogue which allows to change the desktop’s theme. Upon clicking on a theme, a button _Customize Theme_ is activated, which openes another dialogue. In Mint 18.1 there used to be a Tab _Colors_ which offered the very useful possibility of changing some of the theme’s colors, one of them being the color of windows’ title bars.

In Mint 18.2 or Mate 1.18.0 the color tab is gone. Why? Was its usefulness deemed to be too much of an ordeal to be unleashed upon the user?

Why is it that software developers every know and then obliterate good and useful stuff from their software? Firefox, Nautilus, Gnome in general, now Mate?

Sorry for this post sounding crossed, but that’s exactly what I am.

**Comment by flexiondotorg** [comment]
It is not possible to implement that feature using GTK+3 so, sadly, we had to remove it.

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-control-center/issues/170
