### ISSUE TITLE
First window title char hidden when too little space

### ISSUE THREAD

**Issue by basicmaster** [mate-desktop/marco#348]
#### Expected behaviour
When the width of a window is too small to display the complete window title, (solely) the end of the title shall be truncated/dimmed.

#### Actual behaviour
When the width of a window is too small to display the complete window title, the end of the title is truncated - but also the very first character of the title is not shown (but occupies space).

Complete title:
![window_title_complete](https://user-images.githubusercontent.com/7103991/30238399-483abbc4-9547-11e7-8035-8707bbbc23c3.png)

Shortened title:
![window_title_shortened_bug](https://user-images.githubusercontent.com/7103991/30238402-544603ba-9547-11e7-8dcb-e8ec7d218de1.png)

#### Steps to reproduce the behaviour
- open a window with a longer title (e.g. a video with long name)
- resize the window to have a smaller size as needed to show the complete title

Tested with Crux theme, but also occurs with e.g. Clearlooks or Radiant-MATE.

#### MATE general version
1.12.1

#### Package version
1.12.1-1

#### Linux Distribution
Ubuntu MATE 16.04 LTS

#### Link to downstream report of your Distribution
(none yet)

**Comment by jhasse** [comment]
For me, the first character will turn bold, when there's  too little space. Strange.

**Comment by monsta** [comment]
This doesn't happen with 1.18, and 1.12 is too old and unsupported.

I suggest using the official PPA with 1.16:
https://ubuntu-mate.community/t/mate-desktop-1-16-for-ubuntu-mate-16-04/11047
https://ubuntu-mate.community/t/mate-desktop-1-16-2-for-ubuntu-mate-16-04-2/13264

**Comment by basicmaster** [comment]
Thanks for pointing to the PPA. I updated to 1.16.2 and restarted my system, but unfortunately the problem persists. With Ubuntu MATE 17.10 and 1.18.0 it does not occur, so I will wait for Ubuntu MATE LTS 18.04 then.

**Comment by monsta** [comment]
Interesting. I've tested in Mint 18.1 (with MATE 1.16), it doesn't happen there.

**Comment by basicmaster** [comment]
Hmm, strange. Which files/folders do I have to copy, to try my config with the other system with 1.18.0?

**Comment by monsta** [comment]
Most settings are actually stored in dconf, which is accessible via dconf-editor.
