### ISSUE TITLE
Marco memory leak

### ISSUE THREAD

**Issue by CliveMcCarthy** [mate-desktop/marco#353]
#### Actual behaviour Marco grabs memory and does not free it. It can accumulate GB's of memory
I switched to Compiz and the problem goes away.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/marco/commit/6cf1369769b94165c3360945deb47621e957c603
https://github.com/mate-desktop/marco/pull/358
was merged well after the release of 1.18, which came out in March 2017.  Was it ever backported to 1.18?

**Comment by vkareh** [comment]
1.18 is no longer supported and the fix has been commited since 1.19.2. Closing...
