### ISSUE TITLE
Pressing Tab more than once when switching windows via the Alt-Tab dialog cause shadows to draw in front of them

### ISSUE THREAD

**Issue by dsilvestrini** [mate-desktop/marco#354]
When switching windows via the Alt-Tab dialog, pressing Tab more than once causes the shadow to draw in front of the window, instead of behind it.
Screenshots:
- [When switching once](https://user-images.githubusercontent.com/31263057/31575699-d6491008-b0ec-11e7-9214-8e53cf4463cf.png)
- [When switching more than once](https://user-images.githubusercontent.com/31263057/31575698-d0b9eb9e-b0ec-11e7-95f9-20c5a8f3198f.png)

Happens with:
- MATE Desktop Environment 1.18.0
- Marco 1.18.1
- Ubuntu MATE 17.10 beta 2

**Comment by ozeidan** [comment]
Hm, I'm trying to figure this out atm. This apparently only happens when you use marco's compositing. Any more hints on this would be appreciated.

**Comment by cccplex** [comment]
I don't know if it is of any help but I'm using compton compositor now and at it solves this issue if I use the following setting:
`shadow-ignore-shaped = true;`

**Comment by vkareh** [comment]
This is actually a feature that was broken and now is fixed: The shadow should show on the first Tab as well.

The entire behavior can be disabled with
```
gsettings set org.mate.Marco.general show-tab-border false
```
