### ISSUE TITLE
Alt-tab Application switcher should allow clicks [$50]

### ISSUE THREAD

**Issue by nddipiazza** [mate-desktop/marco#364]
the alt-tab application switcher does not allow clicks

https://github.com/mate-desktop/marco/pull/330 fixes it so that you can use keys so that you do not have to cycle things linearly. but it should also support clicks. windows, mac and gnome all support this so we should add it to mate.

#### Expected behaviour
If you have lots of apps, application switcher should allow you to click the applications to show them

#### Actual behaviour
You must use tab or shift tab to cycle linearly which is not useful when you have many apps open 

#### Steps to reproduce the behaviour
Hit alt tab with many windows open. notice clicking a window in the switcher just closes the switcher.

#### MATE general version
tested on ubuntumate 16.x and 17.x both show this missing feature

#### Package version
n/a

#### Linux Distribution
Ubuntu 16.x and 17.x

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1739242

**Comment by ghostplant** [comment]
This feature is outside original GNOME 2/3, so not all people want to change its original behaviors. But I think it is okay to provide these kinds of features with some dconf options, all of which are disabled by default.

**Comment by nddipiazza** [comment]
@ghostplant I can see that and :+1: to the dconf option idea... but in this case in order for mate desktop to be as functionally useful for laymen's users as possible, you'd think it would be a good idea to turn this option *on* by default - purely due to the fact that other major OS do this and Mate doesn't.

**Comment by imperative** [comment]
But this is not a change, this is an addition. There is an asymptotically zero chance that anyone would be bothered by this behavior, because it is only activated if the user actively does something (moves the mouse and clicks) while an Alt-Tab window is shown.

**Comment by phocean** [comment]
Let's sponsor this:

https://www.bountysource.com/issues/52896480-alt-tab-application-switcher-should-allow-clicks

**Comment by phocean** [comment]
Isn't it supposed to be in Ubuntu 19.10?

I am surprised to see that clicks are not supported.

**Comment by vsilvestre-accenture** [comment]
Even on 18.04 this feature exist, it's actually not

**Comment by vkareh** [comment]
this feature is part of the current development branch of marco - next MATE release will include it
