### ISSUE TITLE
Marco only loads metacity-1 themes

### ISSUE THREAD

**Issue by bbcreatv** [mate-desktop/marco#365]
When I try to use any gtk2.0/gtk3 themes they are not recognised it only looks for metacity-1 theme and if that folder is not there it will not load the theme. I thought Marco is only gtk3.0?

#### Expected behaviour
Supports GTK3 themes

#### Actual behaviour
Only loads metacity-1 theme

#### Package version
v1.19.1

#### Linux Distribution
Arch

**Comment by monsta** [comment]
Marco can load `metacity-theme-1.xml` and `metacity-theme-2.xml` files.

```
$ find /usr/share/themes -name metacity-theme-2.xml | sort
/usr/share/themes/BlackMATE/metacity-1/metacity-theme-2.xml
/usr/share/themes/BlueMenta/metacity-1/metacity-theme-2.xml
/usr/share/themes/Bright/metacity-1/metacity-theme-2.xml
/usr/share/themes/Crux/metacity-1/metacity-theme-2.xml
/usr/share/themes/GreenLaguna/metacity-1/metacity-theme-2.xml
/usr/share/themes/Menta/metacity-1/metacity-theme-2.xml
/usr/share/themes/Mint-X/metacity-1/metacity-theme-2.xml
```

**Comment by bbcreatv** [comment]
Yes, but no GTK2/GTK3 themes work. Its just Metacity. So if I don't have a Metacity theme it doesn't work.
