### ISSUE TITLE
 Unable to use <Ctrl+Shift+key> shortcuts with <Ctrl+Shift> keyboard layout switcher

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/marco#368]
#### Expected behavior
<Ctrl+Shift> switches keyboard layout, shortcuts starting from <Ctrl+Shift+> work normally.

#### Actual behavior
<Ctrl+Shift> switches keyboard layout, shortcuts starting from <Ctrl+Shift+> do not work.

#### Steps to reproduce the behavior
1. Install ubuntu-mate-desktop on Ubuntu 16.04 LTS with HWE, or 17.10 or 18.04 LTS.
2. Set-up two keyboard layouts - English and Russian
3. Set <Ctrl+Shift> as keyboard layout switcher
4. Try to use shortcuts starting from <Ctrl+Shift>:
4.1. Open Firefox, open new tab, go to some site in it, close tab, try to click <Ctrl+Shift+T> to restore closed tab.
4.2. Open mate-terminal, try to open new tab with <Ctrl+Shift+T>, or copy (<Ctrl+Shift+C>), or paste (<Ctrl+Shift+C>).
4.3. Open pluma, write some text, try to navigate in it with <Ctrl+Shift+arrow>.

#### MATE general version
1.12 on Ubuntu 16.04 LTS with HWE
1.18 (see [at packages.ubuntu.com](https://packages.ubuntu.com/artful/mate-desktop-environment-core))

#### Package version
marco 1.12.1-1 on Ubuntu 16.04 LTS with HWE
marco 1.18.1-3ubuntu1

#### Linux Distribution
Ubuntu 16.04 LTS with HWE, 17.10 and 18.04 LTS (alpha)

#### Link to downstream report of your Distribution
It is [bug 1720364 on LaunchPad](https://bugs.launchpad.net/bugs/1720364).

#### Notes
1. Ubuntu 16.04 LTS without HWE (MATE 1.12.1) with Marco and Compton work normally with <Ctrl+Shift> keyboard layout switcher.
2. This problem was discovered before on 13.10, 14.04 and other modern versions with GNOME desktop (Metacity and Compiz) - see [bug 1245473](https://bugs.launchpad.net/bugs/1245473).

**Comment by vkareh** [comment]
Hi @N0rbert, which one was the last version that worked for you in either marco or metacity? Also, does it work at all with compiz?

**Comment by N0rbert** [comment]
Thank you for reply, **@vkareh**! 

I'm writing this post from Ubuntu 16.04.4 LTS without HWE (kernel 4.4, xserver-xorg 1:7.7+13ubuntu3). 
Here it works as expected on MATE 1.12.1 with Marco 1.12.1-1 and Compiz 1:0.9.12.3+16.04.20171116-0ubuntu1.

But if I install HWE with `apt-get install --install-recommends linux-generic-hwe-16.04 xserver-xorg-hwe-16.04` on 16.04 LTS I get into this bug first time.
And as I wrote before 17.10 and 18.04 LTS have this bug too because of newer Xorg (I think).

How I can help to discover the root of the problem?
As far I can understand MATE is not the problem here, but really [Xorg is the problem](https://bugs.freedesktop.org/show_bug.cgi?id=865).
How we can determine what was changed between Xorg in normal 16.04 LTS and Xorg in 16.04 LTS with HWE installed?

**Comment by N0rbert** [comment]
I did some research. It seems that problem real problem comes from [old Xorg bug 865](https://bugs.freedesktop.org/show_bug.cgi?id=865).
Ubuntu 16.04 LTS was lucky and it does not have this bug because of Xorg 1.18.4, but newer releases with newer Xorgs have this problem.

So we can close this bug here. It is not bug in MATE DE.
