### ISSUE TITLE
CSD window's titles bug in Mutiny layout

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/marco#376]
#### Expected behaviour
Window decorations of CSD windows must off on maximized windows (if that option is enabled in MATE Tweak)

#### Actual behaviour
Decorations still shown

#### Steps to reproduce the behaviour
1) Choose Mutiny panel layout
2) Open any CSD application (for example GNOME Disks)
3) Maximize it

#### MATE general version
1.8.0
#### Package version
1.18.2

#### Linux Distribution
UbuntuMATE 18.04 alpha

**Comment by raveit65** [comment]
Mutiny panel layout and mate-tweak are ubuntu-mate downstream applications. so please file out a report there.
Thank you.
