### ISSUE TITLE
Random crash (with trace from Linux Mint "System Reports" app)

### ISSUE THREAD

**Issue by DeeDeeG** [mate-desktop/marco#380]
#### Actual behaviour

Crashed.
#### Steps to reproduce the behaviour
Not sure.

I was trying to do a bunch of things, including use my web browser, authenticate to update packages with MintUpdate, run a Docker instance in terminal... Not sure if any of those things have to do with it.

#### MATE general version

`apt list mate-desktop` gives me: `1.18.0-1+sonya`

#### Package version

`apt list marco` gives me: `1.18.2-1+sonya`
#### Linux Distribution

Linux Mint 18.3
#### Link to downstream report of your Distribution
None, I am only reporting here, directly.

### Trace

See this Gist: https://gist.github.com/anonymous/a12e3c5e9f8c311543ebd9f81e9ba048

**Comment by monsta** [comment]
The backtrace shows the crash happens somewhere deep inside libcairo. We can't fix that. It should be reported to libcairo developers.
