### ISSUE TITLE
No visual difference for unfocused CSD windows

### ISSUE THREAD

**Issue by bwat47** [mate-desktop/marco#383]
Expected behaviour
When a window is inactive there should be a visual difference compared to an active window (e.g. different font color in the titlebar)

Actual behaviour
This works as expected for non-csd apps, but for csd apps (e.g. gnome disks) there is zero visual difference between a focused and un-focused window

NOTE: I'm not sure if marco even has any control over this or not... (as these are csd apps). However, I noticed that if I switch from Marco to Compiz, it does work as expected with compiz (the un-focused gnome disks window gets a faded font color in the titlebar)

Steps to reproduce the behaviour
1. Install gnome disks (or any other gnome app with a csd)
2. open another window next to gnome disks and put focus on that new window

MATE general version
1.20

Package version
Marco 1.20

Linux Distribution
Solus

**Comment by bwat47** [comment]
For comparison:

Compiz: https://i.imgur.com/rMvHrED.png

Marco: https://i.imgur.com/81XA2UB.png

**Comment by monsta** [comment]
What you see is a problem in a window manager theme. Try another theme.

**Comment by bwat47** [comment]
just to more clearly illustrate what I mean, non-csd windows always work as expected (see screenshot), the problem is specific to windows using csd decorations.

this is the case which each theme I've tried (including any of the default 
![windows](https://user-images.githubusercontent.com/1442520/36400396-a380ee36-159e-11e8-92e5-077a6588bf07.png)
mate themes)

For any given theme I've tried, it *does* work as expected with csd apps when the theme is used under compiz or under gnome-shell.

**Comment by lukefromdc** [comment]
I can confirm this here with marco 1.20, AND with compiz-reloaded build against marco 1.20 and GTK 3.22.27. In GtkInspector I am finding that neither the :background nor the :focus state is coming up on CSD windows, thus theme changes for these are not applied

**Comment by monsta** [comment]
Ok, I guess it's in Marco then. Wonder if Metacity is affected too.

**Comment by lukefromdc** [comment]
Metacity, IceWM, and compiz 0.9 branch are NOT affected, 
Marco and compiz 0.8 branch ARE affected, the :backdrop state flag is not set so themes do not respond

**Comment by raveit65** [comment]
old known issue, the **.backdrop** state is still broken with marco.
On the other side @flexiondotorg told me to disable this state in ubuntu themes a while a go.
To avoid this weird theming with compiz in ubuntu-mate, not everyone like this......
But i agree this should work with marco in general.
I promised you that will get us a lot of work in our themes as this state was still ignored since years.


Btw. Personal i would force an integreation/switch-to metacity, as fixing every little issue which works with metacity since a long time.

**Comment by lukefromdc** [comment]
_NET_WM_STATE_FOCUSED also does not exist in compiz 0.8 nor in marco

**Comment by raveit65** [comment]
Because compiz-reloaded is based on marco.

**Comment by lukefromdc** [comment]
Only the window-decorator in compiz-reloaded in based on Marco, I don't know if that does anything when GTK is drawing CSD decorations.

Metacity got 
https://github.com/GNOME/metacity/commit/4ccb99a50c54f345c4c7d9ac77f1ea76bc6c7c74
to support  _NET_WM_STATE_FOCUSED

and compiz 0.9 got https://bazaar.launchpad.net/~compiz-team/compiz/0.9.13/revision/2919 
and these are both very complex to port to marco and compiz-reloaded respectively due to the volume of other changes

**Comment by monsta** [comment]
So is it backdrop or background? Because we already have https://github.com/mate-desktop/marco/issues/267 which is said to affect not only CSD windows.

**Comment by raveit65** [comment]
It is the backdrop state which is the opposite to focus state, and the problem exits will normal windows too, not only csd...

**Comment by raveit65** [comment]
At least we have 2 reports about the same problem.

**Comment by monsta** [comment]
However, here it is said that...

> This works as expected for non-csd apps, but for csd apps (e.g. gnome disks) there is zero visual difference between a focused and un-focused window

**Comment by lukefromdc** [comment]
In conventional ssd (not csd) windows, the window manager is responsible for drawing the decorations and responds to the state of the window with or without setting _NET_WM_STATE_FOCUSED or anything else that is exported. In csd windows by comparison, GTK draws the decoration and apparently relies on _NET_WM_STATE_FOCUSED to know what the window manager is doing. GTK then sets the appropriate state flag and that tells it how to interpret the theme

**Comment by monsta** [comment]
I've ported that Metacity commit (see `net-wm-state-focused` branch), but nothing changed. Either I've made some mistake, or that commit alone isn't enough.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/marco/commit/76343fe63860c935efa1b7ef006fffa9eaee08a8 works in my UbuntuStudio_Legacy theme, Adwaita, BlackMATE, all the high contrast themes, and in GreenLaguna (minimal difference but visibly responding at the buttons)
DOES NOT WORK in the rest of the mate-themee, but a lot of titlebar:backdrop stuff is commented out in menta. I found it was necessary to specify 

headerbar:backdrop, .csd headerbar:backdrop,.csd .titlebar:backdrop {
}

to ensure this worked with current GTK 3.22, even with IceWM and compiz 0.9 branch. With https://github.com/mate-desktop/marco/commit/76343fe63860c935efa1b7ef006fffa9eaee08a8
Marco behavior becomes consistant with those on my system
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy/commit/b490e97c166fbca95a3d6fdc404fea0ea1bcae61
fixed a bug in my theme necessary for this to work right, can be a prototype for other themes

**Comment by lukefromdc** [comment]
To clarify: GtkInspector shows that with this change, the :backdrop state now appears on unfocussed CSD windows

**Comment by lukefromdc** [comment]
Opened a PR for the branch, because it works if themes support it and that change is simple

**Comment by monsta** [comment]
Confirmed, it works with Adwaita. Yesterday I only did a quick test with TraditionalGreen and found no changes. So we need some changes in the themes too.

**Comment by raveit65** [comment]
Yes, in most of our themes the backdrop state doesn't exists or is comment out.

**Comment by muktupavels** [comment]
While you work on this, I suggest to do also this:
https://git.xfce.org/xfce/xfwm4/commit/?id=0feb29e78bb3b36387950dc2fb8d991ac875a374

I plan to do that in `metacity` and `compiz`.

**Comment by raveit65** [comment]
I just tested the PR with Adwaita and BlueMenta with that commit reverted.
http://git.mate-desktop.org/mate-themes/commit/?id=32a139134af1231418f6b6db631eb16b703dd787
Don't expect too much with BlueMenta, especially with our own apps.
For CSD apps you see some differences.
All this theme code is old and needs a rework, btw. we need a clear concept for what should be different in backdrop state.

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy@b490e97

includes code on how to use this

**Comment by monsta** [comment]
Ok, what should we do with https://github.com/mate-desktop/marco/issues/267?
