### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by alexaandru** [mate-desktop/marco#385]
#### Expected behaviour
I would expect the window manager not to crash randomly.

#### Actual behaviour
It does crash randomly.

#### Steps to reproduce the behaviour
It's random... Boot, use the desktop for a while, then bye bye window manager. It can work days... or hours... no idea what drives it.

#### MATE general version
1.18.0 (read from `mate-about`)

#### Package version
marco 1.18.2

#### Linux Distribution
Linux Mint 18.3 Sylvia

#### Link to downstream report of your Distribution
?

Ever since I installed the latest Linux Mint I experience random crashes of the window manager. Got so bad that I am now running it from a terminal in a while loop, so that if it crashes I can still work...

It dies with this:

```
marco: ../../../../src/cairo-surface.c:953: cairo_surface_destroy: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
Aborted (core dumped)
```

**Comment by monsta** [comment]
Same crash as https://github.com/mate-desktop/marco/issues/380

**Comment by muktupavels** [comment]
Any chance that crash happens when you Alt+Tab between windows? What windows / apps are open when marco crash?

**Comment by alexaandru** [comment]
Now that you mention it does seem related to Alt+Tab! :)  But that only happens after it crashes the 1st time. So it goes like this: new session, work, work, work... (Alt+Tab works just fine), then crash, run marco manually in terminal in a while loop, and then indeed, every time I hit `Alt+Tab` it crashes. I have no idea if the initial crash is related to that or not, but I'll keep an eye on it.

As for windows: 99% of the time I will have Chrome+VS Code+mate-terminal open. Oh, and I use the "Avant Window Navigator" panel, though IIRW, the crashes were there before as well (when I was using the regular, mate-panel).

Last but not least, sorry for the double report. I did search for this issue, but somehow I missed the other one.

**Comment by muktupavels** [comment]
May I ask you to try to find which app is causing crash?

If you say that it crash every time after marco restart, then you can restart marco after session start with `marco --replace &` and try to find which app is causing crash.

Knowing which app is causing crash might help to understand if bug is in marco, gtk+ or cairo.

**Comment by alexaandru** [comment]
Gonna have to wait for the next crash, replacing it as above does not lead to Alt+Tab crash, everything continues to work just fine.
