### ISSUE TITLE
[1.20.0] [HiDPI] marco doesn't scale with window-scaling-factor

### ISSUE THREAD

**Issue by clayfreeman** [mate-desktop/marco#386]
#### Expected behaviour

Marco should scale according to `org.mate.desktop.interface.window-scaling-factor` so that close, maximize, minimize, etc. match the interface DPI.

#### Actual behaviour

Marco appears as if it is using a scale of 1 (original size), which could be different than the desired scale factor.

#### Steps to reproduce the behaviour

1. Acquire an installation of MATE on a HiDPI monitor.
2. Set the `window-scaling-factor` to a value larger than `1` (i.e. `2` to double the interface scale).
3. Click apply; observe no change in the scale of the window frame on certain applications (e.g. MATE Terminal, Caja, among others).

#### MATE general version

`1.20.0`

#### Package version

`master` branch using Gentoo eBuild `>=mate-base/mate-9999`

#### Linux Distribution

Gentoo Linux

#### Link to downstream report of your Distribution

**Comment by clayfreeman** [comment]
See #335 for a possible explanation of why this might occur.

**Comment by raveit65** [comment]
I see the same if i use scale=2 in a fedora 27 VM with a non-hdpi monitor for testing.
But it depends on metacity themes.
With Menta themes and most others the icons for min/max/close/window-menu aren't scaled.
Same for the icons in context (right-click-menu) of window-menu icon.
But with Traditional themes the min/max/close/ icons are scaled well, only window-menu icon and icons from the menu aren't scaled.
For Menta themes we use real svg/png icons, eg. https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Menta/metacity-1/metacity-theme-2.xml#L264
The traditional themes use 'gradients' for drawing the icons, see https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/metacity-1/metacity-theme-1.xml#L363
So it looks like that scaling for an icon image doesn't work.

**Comment by tidux** [comment]
SVG *should*.  The format name is Scalable Vector Graphics.  If it doesn't, that's a bug.

**Comment by clayfreeman** [comment]
Also - this might be related to another package, or possibly a theme issue - but I noticed that the mouse cursor doesn't scale either.

**Comment by tidux** [comment]
The cursor is probably related to theming support or Marco itself.  Go into appearance -> customize -> pointer and slide the cursor size bar all the way to the right and then back to the left.  This apparently initializes something in hidpi mode that isn't by default on Marco startup so the next time you start an application, your cursor resizes to fit your DPI and stays so resized until you log out.

**Comment by clayfreeman** [comment]
Your suggestion about sliding back and forth didn't seem to take affect, however the cursor looks normal when the largest size is selected.

**Comment by Safari77** [comment]
What about icons which are displayed when alt-tab is pressed?
Those are blurry with ```mate-desktop 1.21.0``` ```mate-panel 1.21.1``` ```marco 1.20.1```

**Comment by vkareh** [comment]
Indeed they are... This is somewhere in my backlog to address. Maybe we should file a bug so that it can be tracked better
