### ISSUE TITLE
Title bar is ignored after alt-tab if moving windows with shortcuts

### ISSUE THREAD

**Issue by l3nn4rt** [mate-desktop/marco#394]
#### Expected behaviour
Every part of the window should be visible
![schermata a 2018-03-01 00-07-31](https://user-images.githubusercontent.com/20030650/36818314-c7de8098-1ce4-11e8-9dda-369dc2bcebaa.png)

#### Actual behaviour
The title bar is hidden; behind top panel if present, else outside the screen
![schermata a 2018-03-01 00-07-37](https://user-images.githubusercontent.com/20030650/36818318-cc6fd3b4-1ce4-11e8-8b20-2ab8298fa86d.png)

#### Steps to reproduce the behaviour
- Set keyboard shortcut for *Move window to north (top) side of screen* ¹
- Set keyboard shortcut for *Move window to center of screen* ²
- Open any (non gnome-style) window (*caja*, *pluma*, ...) in non-maximized mode
- `Alt`+`Tab` (you don't need more windows, just do this at least once)
- Use the first shortcut
- *Where is the title bar?*
- Use the second shortcut

Now you should see the title bar again
- Click on title bar
- Use the first shortcut

Now the bug did not happen: the click made `marco` recognise the title bar

¹ *Move window to north-west (top left) corner* and *Move window to north-east (top right) corner* affected too
² *Move window to south-west (bottom left) corner*, *Move window to south-east (bottom right) corner* and *Move window to south (bottom) side of screen* are fine too
NB: Tiling shortucts are working properly, moving ones affected only

#### MATE general version
1.20.0

#### Package version
 1.20.0-1

#### Linux Distribution
Arch Linux

**Comment by lukefromdc** [comment]
Looking at this I see this is the top decoration of a normal non-CSD app rather than a CSD header bar (also called a titlebar) that is not being rendered. It looks like it's being rendered behind the top panel or otherwise cut off by it.

Can you try this with the panel on the bottom and see if it still occurs?

**Comment by raveit65** [comment]
OMG, use a transparent top panel and you see where the metacity decoration is,
....under the top panel.
It happens with
*Move window to north (top) side of screen*
*Move window to north-west (top left) corner*
*Move window to north-east (top right) corner*
And i can trigger this behaviour with one open window too, if i touch that window with the *alt+tab* keyboard shortcut first.
Edit:
Bottom panel isn't affected.

**Comment by lukefromdc** [comment]
This is an old bug, I've seen it with compiz too with windows that can open with the top decoration hidden or easily be moved to such positions, then have to be moved back in Expo mode. I suspect it's some kind of issue with struts (which set space to exclude things) in mate-panel itself

**Comment by raveit65** [comment]
Good hint, i need to install panel with latest PR with changes for struts here.

**Comment by raveit65** [comment]
We have a regression with marco. Using marco-1.19.2 + https://github.com/mate-desktop/marco/commit/7e2aea33a6fa5ba3bed740b65aaafb872551c150
from fedora 27 release, doesn't have the issue.
So, the issue was somewhere pulled in between 1.19.2 and 1.20.0 release.

Note: fedora 27 use development versions for all packages before HIDPI support was introduced.
I didn't update f27 to 1.20 yet as this is a stable release.

**Comment by raveit65** [comment]
'git bisect' points me to that commit as first bad commit.
https://github.com/mate-desktop/marco/commit/e43cf41d6f029af8c3e8c656a70f22ab386b2f89
And reverting only this line fixes the problem for me.
```
--- a/src/core/keybindings.c
+++ b/src/core/keybindings.c
@@ -2558,7 +2558,7 @@ handle_move_to_corner_backend (MetaDisplay    *display,
   }
 
   meta_window_move_resize (window,
-          FALSE,
+          TRUE,
           new_x,
           new_y,
           window->rect.width,
```
But it seems that reverting that line causes other problems with north/north-west/north-west keybindings.
I am just testing this fix on top of master.
https://gist.github.com/raveit65/cbef90cc2adff14ade8c8f28b7bc0a56

@ozeidan 
Can you please take a look at this?

**Comment by ozeidan** [comment]
I think the 'TRUE' option is still correct here, the problem probably lies deeper within the function. I will try to debug this next week.

**Comment by l3nn4rt** [comment]
> Can you try this with the panel on the bottom and see if it still occurs?

@lukefromdc  this happens with panel on bottom, left or right sides too.

> #### Actual behaviour
> The title bar is hidden; behind top panel if present, else outside the screen

I can confirm this was not happening with 1.19.x

**Comment by ozeidan** [comment]
I think the windows dimensions are just calculated wrongly. The frame is not added onto the window dimensions before moving. On the other hand the screen workspace dimensions are correctly calculated (- the panel height). Why this only happens after alt-tabbing remains a mistery

**Comment by raveit65** [comment]
yes, that it only occurs after alt+tab is weird.

**Comment by raveit65** [comment]
It looks like that https://github.com/mate-desktop/marco/commit/03cffa36b4c89532873848064ef595e5d0ac9b9c
fixes this issue too.
Can someone confirm that?

**Comment by ozeidan** [comment]
It's still there for me.

**Comment by raveit65** [comment]
@ozeidan 
Did you make some progress to find the course of this issue?

**Comment by l3nn4rt** [comment]
I think this is related.
While the topic bug happens with any SSD app, CSD apps seem to have their own problems too.

After using _Move window to center of screen_ on chromium and gnome-calculator:
![schermata a 2018-07-17 11-32-12](https://user-images.githubusercontent.com/20030650/42809115-1900cc1e-89b5-11e8-8f08-fda46748aa9c.png)
Chromium is positioned correctly, while gnome-calculator isn't.

All the _Move SOMEWHERE_ shortcuts are affected.
E.g., _Move window to north-east (top right) corner_ results in:
![schermata a 2018-07-17 11-32-23](https://user-images.githubusercontent.com/20030650/42809121-1d80b970-89b5-11e8-8060-0168401dffa2.png)
Where chromium is, again, positioned correctly, and gnome-calculator doesn't touch the panel on top and is partially outside the screen on the right.

Moving windows with mouse is not affected: the resistance on border is performed correctly.
Any CSD app from gnome-desktop is affected.

**Comment by raveit65** [comment]
I am using mate-calc....

**Comment by l3nn4rt** [comment]
Me too (or python). I was testing gnome apps vs chromium, since are all supposed to be CSD.

**Comment by ozeidan** [comment]
It seems to me that #531 also fixes this bug.

**Comment by raveit65** [comment]
@ozeidan 
thanks for don't forgetting this issue :)
I can confirm that https://github.com/mate-desktop/marco/pull/531 fixes this issue.

**Comment by ozeidan** [comment]
@raveit65 
No problem, sorry for taking so long.
I have some time on my hands in the next days, are there any other related issues that you would like me to take a look at?

**Comment by raveit65** [comment]
@ozeidan 
:)
There is one open issue with using HIDPI and windows are in corner-tiling mode, see https://github.com/mate-desktop/marco/issues/496#issuecomment-491600837
Not sure if you are using HIDPI and you can see the border glitches.
