### ISSUE TITLE
Lock screen can (sometimes) be bypassed if the display configuration is changed while idle

### ISSUE THREAD

**Issue by clayfreeman** [mate-desktop/marco#410]
One of my two DisplayPort-based monitors has a tendency to become soft-disconnected after MATE enters the idle state and display output ceases. This has led me to discover the following bug:

When MATE is locked and the displays are asleep, if the primary monitor is disconnected (or more generally; if the display configuration is altered?) and the computer subsequently resumes display output, MATE has the likely tendency to allow unauthenticated access to the logged-in user's desktop as if the computer were unlocked.

#### Expected behaviour

MATE should always show the lock screen when the computer is locked.

#### Actual behaviour

Sometimes, MATE fails to present the lock screen and instead acts as if the computer is unlocked.

#### Steps to reproduce the behaviour

1. Lock the screen manually with `Ctrl` + `Alt` + `L` hotkey.
2. Wait for the computer to suspend display output after becoming idle.
3. Disconnect the primary display, which should interrupt the idle state.
4. Optionally<sup>1</sup> wait for the idle state again.
5. Observe that the computer is in a pseudo-unlocked<sup>2</sup> state.

*Footnote 1* &mdash; Most often when I observe this issue, it is after I have left my computer for an extended period of time. I assume MATE enters the idle state while the screen saver is on, then my primary display is erroneously soft-disconnected, and the computer eventually enters the idle state for a second time before I have the chance to wake it up and find the lock screen completely bypassed.

*Footnote 2* &mdash; If the display configuration is returned to its original state, the lock screen will reappear.

#### MATE general version

`1.20.1` as reported by *About MATE*.

#### Package version

`marco_1.20.1-2ubuntu1_amd64`

#### Linux Distribution

Ubuntu MATE 18.04 LTS

**Comment by clayfreeman** [comment]
I might also like to add that when this issue occurs, if I alter the display configuration back to its original state, the lock screen will reappear like should be expected.

**Comment by clayfreeman** [comment]
@vkareh @raveit65 cc

Should I file this issue elsewhere? This is somewhat of a security issue that should probably be patched quickly.

**Comment by raveit65** [comment]
Please take a look at repos...... it's is already fixed.
https://github.com/mate-desktop/mate-screensaver/issues/155
https://github.com/mate-desktop/mate-screensaver/pull/167
https://github.com/mate-desktop/mate-screensaver/commit/dbd37df02231b8f2fb57b064c05c4a6886ee0357
https://github.com/mate-desktop/mate-screensaver/commit/465734b765fcfa28a8b63a877bedd65cd2de959e
http://pub.mate-desktop.org/releases/1.20/mate-screensaver-1.20.2.tar.xz
