### ISSUE TITLE
Gnome apps moved with shortcuts are incorrectly positioned if compositor enabled

### ISSUE THREAD

**Issue by l3nn4rt** [mate-desktop/marco#414]
#### Expected behaviour
- What using *Move window to east (right) side of screen* and *Move window to south (bottom) side of screen* should do:
![schermata a 2018-07-19 22-41-20](https://user-images.githubusercontent.com/20030650/42968924-f8f459a8-8ba4-11e8-828a-58545875cb77.png)
- What using *Move window to west (left) side of screen* and *Move window to north (top) side of screen* should do:
![schermata a 2018-07-19 22-41-33](https://user-images.githubusercontent.com/20030650/42968938-00f7a3ee-8ba5-11e8-9770-cfc908b5cb33.png)

#### Actual behaviour
- What using *Move window to east (right) side of screen* and *Move window to south (bottom) side of screen* does:
![schermata a 2018-07-19 22-41-24](https://user-images.githubusercontent.com/20030650/42968966-100febac-8ba5-11e8-9f42-8dde68d217ca.png)

- What using *Move window to west (left) side of screen* and *Move window to north (top) side of screen* does:
![schermata a 2018-07-19 22-41-36](https://user-images.githubusercontent.com/20030650/42968978-154109da-8ba5-11e8-9d1f-ca2109663a81.png)

#### Steps to reproduce the behaviour
- Enable Adaptive or Compoton compositor
- Set keyboard shortcut for *Move window to north (top) side of screen*
- Set keyboard shortcut for *Move window to east (right) side of screen*
- Set keyboard shortcut for *Move window to south (bottom) side of screen*
- Set keyboard shortcut for *Move window to west (left) side of screen*
- Open a Gnome app (`gnome-calc`, `gnome-disk`, ...) in non-maximized mode 
- Try the previous shortcuts

Some more details:
- Chromium seems to be a CSD app too, but it is not affected
- *Move window to center of screen* is affected too

#### MATE general version
1.20.3

#### Package version
1.20.3-1

#### Linux Distribution
Arch Linux

**Comment by ozeidan** [comment]
Hi, I attempted to fix this bug with my pull request #531 . 
The problem was that our calculation did not account for the case when the client renders shadows itself, thus making the X window technically larger than it appears. The patch tries to move windows by calculating the difference from the screen borders instead of setting an absolute positions.

Please try it out and let me know if something doesn't work correctly.

@l3nn4rt @raveit65

**Comment by raveit65** [comment]
I can confirm that https://github.com/mate-desktop/marco/pull/531 fixes the issue.
