### ISSUE TITLE
Feature request: Desaturate and reduce contrast on inactive windows.

### ISSUE THREAD

**Issue by mlinchits** [mate-desktop/marco#415]
Modern GTK3 apps with CSD have text that turns grey when a window is out of focus. This makes it easier to see which window is active and reduces eye strain. Mate doesn't use many of such apps (and when it does, Macro doesn't send the hint to the app - inactive and active apps look the same).

But Mate could do it even better my simply desaturating and reducing contrast on inactive windows.

**Comment by raveit65** [comment]
Already in master branch, and you ignored template, so closing.
