### ISSUE TITLE
Macro does send active and inactive state to CSD/GTK3 windows.

### ISSUE THREAD

**Issue by mlinchits** [mate-desktop/marco#416]
#### Expected behaviour

Out of focus windows have gui elements greyed out (etc), like under Gnome shell or Compiz. Window drop shadows should be consistent for CSD and regular windows

#### Actual behaviour

All CSD/GTK windows look the same regardless of focus. Drop shadows  look different for CSD windows.

#### Steps to reproduce the behaviour

Observation

#### MATE general version

1.20.1-2ubuntu1: amd64 arm64 armhf i386 ppc64el s390x

#### Linux Distribution

Ubuntu Mate / Mint Mate

**Comment by vkareh** [comment]
This is already done: https://github.com/mate-desktop/marco/commit/42410fe72d0ed2c654631e1755526482a80f4fca

Unfortunately we haven't backported this, so it will be officially released for MATE 1.22 - If you want to file a downstream distro bug, you can get the distro maintainers to patch for their respective releases.
