### ISSUE TITLE
Feature request. Drag from top panel to unmaximize

### ISSUE THREAD

**Issue by mlinchits** [mate-desktop/marco#417]
On Gnome Shell, the top panel acts effectively as a window border for maximized windows. You can just drag from the top and start moving the resized window. This is pretty useful in conjunction with hiding the top bar. 

On MATE you can't do that. Handy feature.

**Comment by vkareh** [comment]
@mlinchits - agreed. There's already a feature request open for that: https://gitlab.com/vala-panel-project/vala-panel-appmenu/issues/224 - that's for the applet that provides the global menus. I'll close this as we should track it over there.
