### ISSUE TITLE
Tiled windows become maximized when you drag them out of the (right/left) tiled/snapped position.

### ISSUE THREAD

**Issue by ghost** [mate-desktop/marco#418]
#### Expected behaviour

A tiled window (snapped to one side of the screen) should not become maximized when you drag it out the tiled position. It should be the same size as an unmaximized window.

#### Actual behaviour

The tiled window acquires the size of a maximized window when you try to drag it.

#### Steps to reproduce the behaviour

Open any window and maximize it. Then drag that window's titlebar to the side so it fills up half the screen. Now drag the titlebar again. You'll now dragging a huge a window  that is as big as your desktop.

#### MATE general version

Ubuntu MATE latest.

**Comment by vkareh** [comment]
I may have seen this issue sporadically in the past. Does it happen for you on any window? In my case, as soon as I drag the maximized window, it goes back to unmaximized size before I can even tile it (which is expected).

**Comment by raveit65** [comment]
> Ubuntu MATE latest.

Not every body use ubuntu .....
Honestly, what is so hard to find out correct versions before you file out reports.

### Link to downstream report of your Distribution

Why empty? Are you lazy ?  :)

**Comment by mlinchits** [comment]
@vkareh the window goes into the "maximized" state when you drag it *out* of the tiled position. If you don't see this problem, I assume it might have been fixed upstream.

@raveit65 i don't have access to the machine with the installation atm.

**Comment by vkareh** [comment]
@mlinchits I'm sorry I can't reproduce. I know I've seen this issue in the past, but never consistently. Do you have mate-maximus running by any chance?

**Comment by mlinchits** [comment]
As I recall, yes. I am currently on a gnome desktop, so can't test. The behavior was observed on Linux Mint  Mate.

**Comment by vkareh** [comment]
Ok, I'll test with maximus then. That might be the culprit

**Comment by vkareh** [comment]
alright, enabled mate-maximus and here's what I got:
1. Open a window, unmaximize it
2. Maximize window
3. Drag from titlebar to edge for tiling
4. Drag from titlebar to un-tile
5. Window retained same size as when it was tiled <-- so this was pretty annoying, but it only happened with mate-maximus. So the problem might be there. Could you try to reproduce and see if removing/disabling mate-maximus fixes it for you?

**Comment by vkareh** [comment]
This is not an issue in marco, if issue persists, file a bug against mate-maximus
