### ISSUE TITLE
window_state_event is not sent for toplevel window when focus changes, it's missing backdrop state flag, application looks active

### ISSUE THREAD

**Issue by stransky** [mate-desktop/marco#427]
#### Expected behaviour
Gnome sends window_state_event when application focus changes. Gtk reacts to is by setting GTK_STATE_FLAG_BACKDROP flag (ensure_state_flag_backdrop at gtkwindow.c) to the window which is picked by theme to correctly shade the window.

#### Actual behaviour
Gtk applications with CSD enabled (gedit, firefox for instance) does not get window_state_event with focus change so the application looks active even when it's on background.

Also default MATE theme does not work well with the "backdrop" state and the theme does not render some elements (scrollbar thumb for instance - https://bugzilla.mozilla.org/show_bug.cgi?id=1491374)

#### Steps to reproduce the behavior
1) Open gedit
2) Open another application, make gedit partially visible
3) switch to gedit and back - gedit titlebar does not change its color although it should

#### Package version
marco-1.20.2-1.fc28.x86_64

#### Linux Distribution
Fedora 28

#### Link to downstream report of your Distribution
https://bugzilla.mozilla.org/show_bug.cgi?id=1491374

**Comment by raveit65** [comment]
What element is scrollbar thumb?
`scrollbar thumb { }` in css language?
And how is firefox examinable with gtk3-inspector?
I thought firefox don't use gtk-widgets in favor of own code.
Backdrop state is already done in marco master and will come with MATE-1.22.
https://github.com/mate-desktop/marco/commit/42410fe72d0ed2c654631e1755526482a80f4fca
But it should be possible to recompile my fedora marco SRPM with marco-1.21.0 for testing.
http://pub.mate-desktop.org/releases/1.21/marco-1.21.0.tar.xz

**Comment by raveit65** [comment]
Btw. i can do a marco-1.21.0 koji scratch build for f28 if you want.

**Comment by stransky** [comment]
Thanks, but I'm more interested in fixed default MATE theme. Firefox already sets the backdrop state for and that causes a scrollbar regression on MATE.

Firefox can't be inspected by gtk3-inspector as it uses direct styles instead of widget hierarchy. I use gedit as a reference application and update Firefox code along it. For the debugging I use:

$export GTK_OVERLAY_SCROLLING=0
$GTK_DEBUG=interactive gedit 

so If you get working gedit with backdrop state on MATE it will also fix Firefox and if not I'll fix that on Firefox side.

**Comment by stransky** [comment]
> What element is scrollbar thumb?
> `scrollbar thumb { }` in css language?

It's "scrollbar contents trough slider" css path, AFAIK themes usually omit the contents node.

**Comment by raveit65** [comment]
I added backdrop settings to  BlueMenta theme for testing a while a go to this branch as prove of concept.
https://github.com/mate-desktop/mate-themes/commits/menta-backdrop
But i am waiting for gsettings key to enable/disable backdrop state, because i am pretty sure that some MATE user won't like this gtk3 feature.
For this reason the branch isn't pushed  for the moment.

Thanks, i know how to use gtk3-inspector in general, the question was more to use gtk3-inspector for ff-gtk3, because we had a lot of trouble to find the right css settings for them in the past ;)

**Comment by raveit65** [comment]
> It's "scrollbar contents trough slider" css path, AFAIK themes usually omit the contents node.

So, the issue is that `trough` and  `slider` aren't visible, btw. transparent, in backdrop state with BlueMenta theme?

I can't reproduce that here with marco  from master branch and last mate-themes release (without extra backdrop settings) from fedora f28.
```
[rave@satellite ~]$ rpm -qa mate-themes
mate-themes-3.22.18-1.fc28.noarch
```
Sorry, i can't test normal f28 mate-1.20 version as my box with all VMs are broken at the moment, and my old laptop is a bit limited.

**Comment by raveit65** [comment]
Hmm, also with marco-1.20.2-1.fc28.x86_64 from fedora repos the ff scrollbar looks fine her in backdrop state with BlueMenta theme.
![bildschirmfoto zu 2018-09-19 19-29-50](https://user-images.githubusercontent.com/961604/45770359-7022ea80-bc42-11e8-95e8-53d06d5b2b00.png)

Maybe i don't understand the problem........
Can you provide a screenshot please?

**Comment by stransky** [comment]
It may be a combination of Firefox & MATE bugs, maybe some theme bug. If you manage to fix gedit to work fine with the backdrop state, I can fix Firefox to also behave correctly under MATE.

For testing I use "Clearlooks" theme where the scrollbar thumb is missing in latest nightly (Firefox 64 alpha). Firefox 62 does not contain this "backdrop" feature yet.

**Comment by stransky** [comment]
![firefox-scrollbar](https://user-images.githubusercontent.com/544475/45774521-75d1fd80-bc4d-11e8-8ce4-97ad48e68b26.png)
There's the missing scrollbar thumb, Firefox 28, Clearlooks theme, Firefox 64alpha (it's a flatpak build from https://firefox-flatpak.mojefedora.cz/)

**Comment by stransky** [comment]
Yes, some themes work fine already.

**Comment by raveit65** [comment]
Ok, i will test firefox 64alpha.
But `clearlooks` isn't from Mate desktop. Our fork of `clearlook-phenix` called `TraditionalOK`, and our default theme in fedora called `BlueMenta`.
Ubuntu-Mate is different , they use their own themes as default, they call Ambiant-/Radiant-MATE.

I assume that your clearlook theme is gtk2 only , in result we see the gtk+ fallback theme (adwaita) for gtk3 applications in your screenshot.
The scrollbar from the focused window looks like from adwaita theme.

**Comment by raveit65** [comment]
Ok, i just managed to install the flatpak repo.
But it seems that i 've to install a bunch of stuff which i don't like to see on my system.
Eg.
```
Do you want to install it? [y/n]: y
Installing in system:
org.gnome.Platform/x86_64/3.24                  gnome                   bcb47fddc250
```

**Comment by stransky** [comment]
> Ok, i just managed to install the flatpak repo.
> But it seems that i 've to install a bunch of stuff which i don't like to see on my system.
> Eg.
> 
> ```
> Do you want to install it? [y/n]: y
> Installing in system:
> org.gnome.Platform/x86_64/3.24                  gnome                   bcb47fddc250
> ```

Yes, it's because flatpak sandbox. You can get nightly as tarball directly from mozilla at https://www.mozilla.org/en-US/firefox/channel/desktop/

Just untar the ball somewhere and run ./firefox -ProfileManager to create a new profile for nightly and then run the nightly as ./firefox -P your_profile -no-remote

**Comment by raveit65** [comment]
That's better, thanks. But is this the right version with backdrop support?
![bildschirmfoto zu 2018-09-19 22-24-36](https://user-images.githubusercontent.com/961604/45779627-c94b4800-bc5b-11e8-926f-01f992da6cc7.jpg)

**Comment by raveit65** [comment]
Beside from that i see only missing minimize/maximize/close buttons in headerbar with our default theme (BlueMenta) -_-

**Comment by raveit65** [comment]
Ok, got it . I need to use the nightly version.

**Comment by raveit65** [comment]
I can reproduce the issue with firefox-64.0a1, but only with adwaita theme.
Adwaita-dark and all our MATE themes are working fine.
And i doesn't matter if i use marco-1.20.2-1.fc28 from fedora repos or marco from master with backdrop support.
The ***only one*** theme with this issue is adwaita.

Here is a scratch build from marco with working backdrop state for testing.
https://koji.fedoraproject.org/koji/taskinfo?taskID=29768396

**Comment by raveit65** [comment]
The missing minimize/maximize/close buttons in firefox headerbar with BlueMenta i don't get with gedit.
firefox:
![firefox-64alpha](https://user-images.githubusercontent.com/961604/45781699-049c4580-bc61-11e8-8915-3b7ae58ad091.png)
gedit:
![gedit](https://user-images.githubusercontent.com/961604/45781731-21387d80-bc61-11e8-9a17-9f503739375e.png)

firefox issue?

**Comment by stransky** [comment]
> I can reproduce the issue with firefox-64.0a1, but only with adwaita theme.
> Adwaita-dark and all our MATE themes are working fine.

That's great new.

> And it doesn't matter if i use marco-1.20.2-1.fc28 from fedora repos or marco from master with backdrop support.
> The _**only one**_ theme with this issue is adwaita.

That's interesting than the theme works fine in gnome-shell but it's broken on MATE...do you have any idea why?

> Here is a scratch build from marco with working backdrop state for testing.
> https://koji.fedoraproject.org/koji/taskinfo?taskID=29768396

Thanks, I'll use that for testing.

**Comment by raveit65** [comment]
> Most likely. Do you mind to file it and other theme bugs at http://bugzilla.mozilla.org/ component widget:gtk ? I can look at it. When it works on gedit we should fix that on Firefox side as well.

Yes, i can file out a report. But we are using images for the buttons with BlueMenta theme to have the same button look as with metacity theme decoration.
See https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/window-controls.css#L39
Looks like a problem with displaying PNG images?

> That's interesting than the theme works fine in gnome-shell but it's broken on MATE...do you have any idea why?

It's possible to run `mutter` WM in mate session. You can switch WMs easily via fusion-icon notification-area-applet from compiz. It is already available in default mate installation.
I will test this.

**Comment by raveit65** [comment]
> Looks like a problem with displaying PNG images?

Or do i have to correct the css path for firefox?
```
headerbar .right button.minimize.titlebutton:backdrop:hover,
headerbar .right:dir(rtl) button.minimize.titlebutton:backdrop:hover,
headerbar .left button.minimize.titlebutton:backdrop:hover,
headerbar .left:dir(rtl) button.minimize.titlebutton:backdrop:hover,
headerbar .right button.minimize.titlebutton:hover,
headerbar .right:dir(rtl) button.minimize.titlebutton:hover,
headerbar .left button.minimize.titlebutton:hover,
headerbar .left:dir(rtl) button.minimize.titlebutton:hover {
	background-image: url('window-controls/minimize_focused_prelight.png');
}
```
To whatever firefox use?

**Comment by stransky** [comment]
Firefox uses a custom code to load and draw the styled icons:

https://dxr.mozilla.org/mozilla-central/rev/a9e339b3e5d8dc3b108d3dc8b85f72b2235fafb2/widget/gtk/WidgetStyleCache.cpp#587

I see it already on my MATE desktop/Fedora 28 when I select BlueMenta theme so I'll look at it.

**Comment by stransky** [comment]
I filed the missing scrollbars here https://bugzilla.mozilla.org/show_bug.cgi?id=1492761

**Comment by stransky** [comment]
Missing icons are reported here https://bugzilla.mozilla.org/show_bug.cgi?id=1492764

**Comment by raveit65** [comment]
I see the same missing scrollbar thumbs with running `mutter` WM and adwaita theme in mate-session.
![mutter-firefox](https://user-images.githubusercontent.com/961604/45809583-d2263300-bcc8-11e8-878e-3900bb17a401.png)

Are you sure that the issue doesn't exists in gnome-shell?
I am still wondering what is different in gnome-shell session?
Also we have different results with adwaita-dark.
Comparing adwaita and adwaita-dark css should give us a hint.

**Comment by stransky** [comment]
I think I have a hint. I see the backdrop change is animated and the animation begins with a transparent state. Firefox does not support animated themes so it may render just the first frame of the animation which is transparent. Can I disable theme animations on MATE?

**Comment by stransky** [comment]
Confirmed. When I enable the animation the thumb is also invisible on gnome-shell.

**Comment by raveit65** [comment]
> Can I disable theme animations on MATE?

Is this done with a gsettings key in gnome-session?
Not sure if we have such a gsettings key, i will search for it.

**Comment by raveit65** [comment]
```
[rave@satellite ~]$ gsettings get org.mate.interface enable-animations
true
```
This one?
... testing....

**Comment by stransky** [comment]
"gsettings set org.gnome.desktop.interface enable-animations false" fixes that on gnome-shell

**Comment by raveit65** [comment]
No, setting the gsettings key to false doesn't help in mate-session.
```
[rave@satellite ~]$ gsettings get org.mate.interface enable-animations
false
```
This is a very old key which was never changed in mate since forking gnome2.
I am in doubt that this key supports modern css transition effects,
and i guess that the gnome gsettings key was updated to support transition effects.

**Comment by stransky** [comment]
I think this issue can be closed as it's a bug at Firefox.

**Comment by stransky** [comment]
You're right, disabling the animations does not help - it's a bug in Firefox when setting wrong style for the thumb element, Adwaita theme does not pick it.

**Comment by stransky** [comment]
> > Looks like a problem with displaying PNG images?
> 
> Or do i have to correct the css path for firefox?
> 
> ```
> headerbar .right button.minimize.titlebutton:backdrop:hover,
> headerbar .right:dir(rtl) button.minimize.titlebutton:backdrop:hover,
> headerbar .left button.minimize.titlebutton:backdrop:hover,
> headerbar .left:dir(rtl) button.minimize.titlebutton:backdrop:hover,
> headerbar .right button.minimize.titlebutton:hover,
> headerbar .right:dir(rtl) button.minimize.titlebutton:hover,
> headerbar .left button.minimize.titlebutton:hover,
> headerbar .left:dir(rtl) button.minimize.titlebutton:hover {
> 	background-image: url('window-controls/minimize_focused_prelight.png');
> }
> ```
> 
> To whatever firefox use?

It's because Firefox does not set .left/.right classes to box element (https://bugzilla.mozilla.org/show_bug.cgi?id=1492764)
