### ISSUE TITLE
CSD applications gain second decoration if started maximized, then unmaximized.

### ISSUE THREAD

**Issue by Cpt-Derp** [mate-desktop/marco#428]
#### Expected behaviour
CSD apps stay with their own decoration upon unmaximizing.

#### Actual behaviour
Marco decorates them twice upon unmaximizing.

#### Steps to reproduce the behaviour
Start any CSD application maximized, then unmaximize it.

#### MATE general version
1.20.1

#### Package version
1.20.1-2ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04.1 amd64

#### Link to downstream report of your Distribution
None

The decoration also seems to come with a new border that is wide and transparent. The app in the background for instance is Discord and not anything Firefox.

![image](https://user-images.githubusercontent.com/3199836/45923034-a3ff4980-bea8-11e8-9d47-b487e5bbc729.png)

**Comment by lukefromdc** [comment]
I was unable to confirm this with marco 1.21.0 current as of 8-20-2018 and switching Firefox over to CSD mode after switching from compiz to marco, not sure why.

**Comment by Cpt-Derp** [comment]
Tested on a second machine, MATE 1.20.1. Bug occurs there as well. 

Probably unintentionally fixed in some commit if it's not reproducible in the latest build?

**Comment by Cpt-Derp** [comment]
I compiled Marco 1.21 from source on my Ubuntu machine (left the rest of Ubuntu MATE alone). The bug is indeed non-reproducible. Fantastic.

**Comment by Cpt-Derp** [comment]
@lukefromdc Found out the bug can be reliably reproduced using the same steps, only if Firefox is started maximized. It persists in 1.21 for me, compiled from master. It doesn't seem to occur for the entire life of the Firefox process if it's started unmaximized.

**Comment by lukefromdc** [comment]
Well that would explain it, as I never ever start Firefox maximized. I run browsers in RAM, with the .mozila directory etc set up as desired and copied to RAM by a script that starts the browser, always at its default window size and location. I can kill the terminal (or the session) and leave this in RAM and restart Firefox but have never done so maximized as I only use Firefox that way for screenshotting things like openstreetmap.org maps

**Comment by Cpt-Derp** [comment]
@lukefromdc Oh, heh. 

Also, it's actually worse than I thought. I can reproduce this bug on any CSD application if it's started maximized.

![image](https://user-images.githubusercontent.com/3199836/46242430-1daaa200-c397-11e8-91e4-b0f6b4acde8d.png)

![image](https://user-images.githubusercontent.com/3199836/46242438-4468d880-c397-11e8-9d63-2c115bb1515f.png)

![image](https://user-images.githubusercontent.com/3199836/46242501-ee486500-c397-11e8-9031-e3f2b19016ea.png)

![image](https://user-images.githubusercontent.com/3199836/46242527-120bab00-c398-11e8-95f4-d1368456070c.png)

**Comment by raveit65** [comment]
Does it happen with another window manager, eg. metacity, compiz?
Did you filed out a report for firefox?
Firefox itself is under heavy development since they switched to gtk3.

**Comment by raveit65** [comment]
I don't see a second titlebar with CSD-windows.

**Comment by Cpt-Derp** [comment]
I can try installing Ubuntu MATE fresh to rule out a configuration problem on my end. If you can't reproduce it, chances are it's something along those lines. I haven't filed a bug report with Firefox because it isn't the only affected application, and Compiz exhibits the same behavior but without the thick transparent border.

**Comment by raveit65** [comment]
I really would like to see someone with ubuntu installed here, for reproducing the issue.
Maybe the ubuntu maintainer?
@flexiondotorg ^^^

**Comment by Cpt-Derp** [comment]
@raveit65 Reproducible on Ubuntu MATE 18.04.1 LiveCD.

![bsmktvf](https://user-images.githubusercontent.com/3199836/46243103-39657680-c39e-11e8-92b7-19363f4d92f8.png)

**Comment by raveit65** [comment]
So the issue is that you see the normal marco window decoration for a short moment during switching from maximize to normal window state?

**Comment by Cpt-Derp** [comment]
Nope. If the application is started in the maximized state, it has only its CSD at first. When it's unmaximized afterwards, it gains that extra window decoration and it stays there for the duration of its runtime. It does not occur if the application is started in the unmaximized state.

**Comment by raveit65** [comment]
Ok, how do you start a csd application into maximize state, eg. dconf-editor?
And do you have mate-netbook installed which can cause weird issues like this?
https://github.com/mate-desktop/mate-netbook

**Comment by Cpt-Derp** [comment]
I close the application when it's maximized and relaunch it. Window state is remembered.

And yeah. The LiveCD also has it installed, so I assume it comes with Ubuntu MATE.

**Comment by raveit65** [comment]
Sadly, mate-netbook is quite buggy , for that reason i never used/include it for/in official fedora. 
We can't move reports here at github. Can you please file out a new report at https://github.com/mate-desktop/mate-netbook/issues
?
Filing out a downstream report is necessary to inform ubuntu maintaner.
Maybe ask him to drop that buggy package? Your issue isn't the only issue.......

Thank you

**Comment by Cpt-Derp** [comment]
Sure thing. Also, thanks for pointing out that package. Wouldn't have figured otherwise.
