### ISSUE TITLE
[RFC] would it be worthwhile to change 'meta' to 'marco' in the source?

### ISSUE THREAD

**Issue by gtnuux** [mate-desktop/marco#433]
#### Expected behavior
When reading the marco source code, the names of subroutines, variables, etc, specific to the window manager should indicate this by including 'marco' or 'MARCO' as a prefix or component of the name.

#### Actual behaviour
One actually finds that 'meta' and "META' are used instead, which is clearly leftover from Metacity.
For example, the non-static sub in place.c is meta_window_place, not marco_window_place

####
Fixing this would  be helpful to someone (like me) who is new to the code and trying to understand  it.  However, a simple find-and-replace  (perl -pi -e s/meta/marco/g ) won't quite work.  Unfortunately, the term 'meta' is used (overused, imho)  in many other contexts.  So, for example, you'll break things if you try to refer to the 'meta' key on the keyboard as the 'marco' key.  It shouldn't be all that hard to sort those cases out, though.  Is it worth doing?

**Comment by vkareh** [comment]
Yes, and no. It would be great to have our own marco prefixes. On the other hand, it would make backporting things a bit harder.

The real issue, though, is that doing that effectively hides a lot of the git history. So if I do it, every single line that I change will now point to that commit through the entire code base, making it much harder to see who did what and why

**Comment by gtnuux** [comment]
Thanks for the quick response.  You are correct, of course that this wouldn't be a great idea.  I didn't realize that metacity is still being maintained, at least for bug-fixes.  Also, I didn't realize that mutter shares quite a bit of code with marco/metacity as well.  So, changing the variable names would be an obstacle to sharing anything between these projects.

The git-history issue would be a problem as well.  I have great respect for Torvalds, but I often find git pretty frustrating.  Couldn't there be a way to mark a commit such as "changing a variable name" as "editorial" (even if it is a large change), so that it wouldn't cloud the history (unless you ask to see it)?  Of course, you also wouldn't be able to easily split/merge things from before/after such a change, but often that wouldn't matter.  But hey, I'm definitely not a git-expert by any stretch.

**Comment by vkareh** [comment]
There's no such thing in git, as far as I know. We could manually check for the history of each line we change and ammend it, effectively rewriting the git history on Marco, but yeah that would be crazy :P

Metacity is actually still being actively developed and improved :)
