### ISSUE TITLE
Constant writing to xorg.log when Adaptive Compositor is used

### ISSUE THREAD

**Issue by meanoldmartin** [mate-desktop/marco#438]
#### Expected behaviour
'Normal' output to Xorg.log suring start up, but then quiet

#### Actual behaviour
Normal start up logging, but then constant re writing of same two lines to log:

(EE) modeset(0): Failed to get GBM bo for flip to new front.
(EE) modeset(0): present flip failed

This has stopped when changing Marco to "No Compositor" in MateTweak

#### Steps to reproduce the behaviour
Happens everytime when any mode other than No Compositor is used.

#### MATE general version
1.20.3

#### Package version
1.20.2

#### Linux Distribution
ParrotSec 4.4 64bit
Kernel Linux 4.18.0-parrot10-amd64 x86_64

#### Link to downstream report of your Distribution

If you are already aware of this, please delete. I searched, but couldn't find anything - this is my first bug report, so I hope it's useful.

**Comment by lukefromdc** [comment]
I don't have mate-tweak or compton installed, just marco and compiz-reloaded. By "adaptive compositing" do you mean GPU enabled compositing with compton and Marco? If so this could be a video driver issue, as "flip" and "modeset" issues normally refer to video drivers.

**Comment by vkareh** [comment]
I have not seen this error before, but the Xpresent extension should automatically disable itself on any errors... Sounds like a bug in the compositor code (the infinite logging part).

As for the actual error message, I would need to research, it does seem like a driver issue.

**Comment by zhangn1985** [comment]
this happens on Debian Testing (buster), not on Stretch.
same mate-desktop version, but Xorg version is different.

so I guess, marco is not compatable with new Xorg.

Xorg on Stretch (with stretch-backports enabled)
1.19.2
Xorg on Buster
1.20.3

----
my debuging:
on stretch, modeset driver is fine.
on buster, when disable pageflig for modeset driver or change to intel driver, this issue gone.
on buster, when disable marco composite, this issue gone.

**Comment by raveit65** [comment]
> #### Link to downstream report of your Distribution


If you are already aware of this, please delete. I searched, but couldn't find anything - this is my first bug report, so I hope it's useful. 

Why not filing out an downstream report if there is no report?  :wink:

**Comment by lukefromdc** [comment]
If this is a bug in the xorg modesetting driver, we should be able to close this, as it cannot be fixed in marco short of detecting a bad Xorg version and driver and disabling xpresent in that case.

**Comment by sibyakin** [comment]
I can see similar behavior on Ubuntu 19.10 / Mate 1.22.2 with amdgpu.
```
(WW) AMDGPU(0): Page flip failed: Resource temporarily unavailable
(EE) AMDGPU(0): present flip failed
```
^^^ a lot of these lines.
For now, I'm just using
```
Option "EnablePageFlip" "off"
```
in my xorg.conf

**Comment by vkareh** [comment]
Definitely an issue with Xpresent. I don't have an AMD GPU, but I can check whether there are any errors that we're not trapping and add them, then use the error check to disable flips (like we already do with BadWindow errors)

**Comment by kas7yler** [comment]
> I can see similar behavior on Ubuntu 19.10 / Mate 1.22.2 with amdgpu.
> 
> ```
> (WW) AMDGPU(0): Page flip failed: Resource temporarily unavailable
> (EE) AMDGPU(0): present flip failed

This was fixed in amdgpu DDX driver: https://gitlab.freedesktop.org/xorg/driver/xf86-video-amdgpu/commit/bf61e6d7ac1a5754b1026d7f80acf25ef622c491. Should be in the latest release 19.1.0.

**Comment by zhangn1985** [comment]
please update Xserver to git master, I dont remenber which commit fix this issue, but this is not marco's issue.

**Comment by zhangn1985** [comment]
upstream bug: https://gitlab.freedesktop.org/xorg/xserver/issues/68

**Comment by lukefromdc** [comment]
Closing as this is not a marco issue but (as described above) an xorg issue
