### ISSUE TITLE
segfault on alt-tab if composited and thumbnails enabled

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/marco#445]
#### Expected behaviour
alt-tab should work with or without compositing and with or without the window thumbnails in the alt-tab popup

#### Actual behaviour
If compositing is enabled and compositing-fast-alt-tab (disable thumbnailing) is not selected an immediate segfault results on alt-tab

#### Steps to reproduce the behaviour
With marco running as window manager press alt-tab. Marco segfaults 
`[ 4067.330536] marco[26505]: segfault at 8 ip 0000562ea813a350 sp 00007ffeda723128 error 4 in marco[562ea8124000+59000]
`
An attempt to run marco in gdb to get a backtrace did not work, as the entire session then became nonresponsive on alt-tab, gdb did not display any new text but marco had stopped. Had to kill Xorg to get out of that

#### MATE general version
1.21 from git master

#### Package version
marco 1.21.0 locally compiled from git master pulled 2019-1-7

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as these are local builds

**Comment by lukefromdc** [comment]
My guess is the August alt-tab popup work may have played a role in this

**Comment by raveit65** [comment]
Same here. This isn't good.

**Comment by raveit65** [comment]
marco-1.21.1 release doesn't have the issue. So, there are only a few new commits.

**Comment by raveit65** [comment]
Issue is caused by 
https://github.com/mate-desktop/marco/commit/b4dcd38a04c6ab44da5d8ac63b386419c9bda7a4
I can't test if https://github.com/mate-desktop/marco/commit/4940310cda91a4bea223deb7568fb77829518ded is OK, because build fails without the first commit from PR.

@sc0w ping

**Comment by sc0w** [comment]
I will take a look later...
