### ISSUE TITLE
Compositing shadow artifacts

### ISSUE THREAD

**Issue by xxxxme** [mate-desktop/marco#47]
With compositing enabled, shadowed tooltips sometimes leave their shadows behind when they disappear.  See the attached image.  I hovered over one of the links, which brought a tooltip showing the link's destination.  When I moved my mouse, the tooltip disappeared, but the shadow did not.
![marco shadow artifact](https://f.cloud.github.com/assets/3073154/406621/aaa839be-aaa8-11e2-87b2-4b51245c9913.png)

Arch Linux x86
mate-window-manager 1.6.1 from the Arch Maté repo
the shown program is evince 3.6.1

**Comment by monsta** [comment]
MATE 1.6.x is history. Does it still happen in 1.8.x?
If not, you can safely close this issue.

**Comment by xxxxme** [comment]
Sorry, I don't know. I haven't used Maté for quite a while. I guess I'll close the issue and let someone else reopen it if it still happens.
