### ISSUE TITLE
Resize window with mouse only works from top (title bar)

### ISSUE THREAD

**Issue by kyrios123** [mate-desktop/marco#474]
#### Expected behaviour
Ability to resize a window by dragging window border with the mouse cursor

#### Actual behaviour
This only works from the top of the window (perhaps it's related to #356 ?)

#### Steps to reproduce the behaviour
Here is the behaviour in MATE 1.20 (before upgrade)
![mate120](https://user-images.githubusercontent.com/7815316/54087333-1e862d80-4352-11e9-8db5-61ce10747693.gif)
And after (on the same system after update to MATE 1.22)
![mate122](https://user-images.githubusercontent.com/7815316/54087352-407fb000-4352-11e9-9d2b-86f27e5b2db2.gif)

#### MATE general version
1.22.0

#### Package version
1.22.0

#### Linux Distribution
Solus

#### Link to downstream report of your Distribution
https://dev.getsol.us/D5656

**Comment by kyrios123** [comment]
@raveit65 sorry to bother but do you have any idea of what could be the cause of this problem or perhaps point some directions on how I could troubleshoot this?

**Comment by raveit65** [comment]
Hmm, i can resize terminal window with MATE 1.22 with my metacity theme.
I am using Blue-Submarine from mate-themes which use only metacity-theme-1.xml version.
Which theme are you using?
marco-1.22.0 supports now metacity-theme-3 version.
I guess the border-width is zero in your metacity-theme-3.xml.
Check those values in your theme.
(left_width, right_width and bottom_height)
```
<frame_geometry name="normal" title_scale="medium" rounded_top_left="4" rounded_top_right="4">
    <distance name="left_width" value="6" />
    <distance name="right_width" value="6" />
    <distance name="bottom_height" value="6" />
    <distance name="left_titlebar_edge" value="4"/>
    <distance name="right_titlebar_edge" value="1"/>
    <distance name="title_vertical_pad" value="12"/>
    <border name="title_border" left="2" right="2" top="0" bottom="0"/>
    <border name="button_border" left="0" right="0" top="1" bottom="2"/>
    <aspect_ratio name="button" value="1"/>
</frame_geometry>
```
From BlueMenta theme.

Marco use always the highest existing `metacity-theme` version from a theme folder.

**Comment by kyrios123** [comment]
That was it, thanks!
I am using Plata-Noir there is a `metacity-theme-2.xml` and a `metacity-theme-3.xml` and in the version 3 the borders width was 0, which explains why the problem only occurred when I updated.

Thanks a lot @raveit65 without you I guess I would have searched for a long long loooonnng time!
