### ISSUE TITLE
Marco ignores the alpha channel in semi-transparent bitmaps

### ISSUE THREAD

**Issue by baer63** [mate-desktop/marco#486]
#### Expected behaviour
If a metacity theme is using semi-transparent bitmaps to draw window decorations, these window decorations are expected to be rendered semi-transparent.

#### Actual behaviour
Semi-transparent bitmaps are rendered opaque.

#### Steps to reproduce the behaviour
Try the metacity theme out of this package: https://www.gnome-look.org/p/1014762/
Inactive Windows should be rendered dark gray and semi-transparent but they are rendered as black. For comparison: try the same theme using the metacity-theme-viewer and you can immediately see how an inactive window **should** be rendered.

#### MATE general version
1.20.4

#### Package version
1.20.3-1~bpo9+1

#### Linux Distribution
Debian 9.8

**Comment by raveit65** [comment]
> Inactive Windows should be rendered dark gray and semi-transparent but they are rendered as black.

I don't see that description at https://www.gnome-look.org/p/1014762/ or a screenshot of it.

**Comment by raveit65** [comment]
Ok, it should use light pngs from the theme.
```
<draw_ops name="frame-bottom-unfocus">
  <image filename="bottom-left-unfocus.png" x="0" y="0" width="8" height="object_height"/>
  <image filename="bottom-middle-unfocus.png" x="6" y="0" width="width - 12" height="object_height"/>
  <image filename="bottom-right-unfocus.png" x="width - object_width" y="0" width="object_width" height="object_height"/>
</draw_ops>
```
No idea, why this doesn't work.
Btw. with metacity WM this theme doesn't display.
Looks like this old theme needs an update.
Did you filed out a report against authors repo?
Which WM does it display correctly?

**Comment by baer63** [comment]
Since there is no screenshot of an inactive window for that theme on gnome-look.org, let me show you. I am running Marco but I also have metacity (Debian) version 1.3.22 installed. Marco is the active window manager.
This is a screenshot of metacity-theme-viewer running the theme - focused window. You can see that the renderings (Marco renders the window decoration for metacity-theme-viewer and metacity-theme-viewer renders a focused window in its client area) are identical.
![Screenshot at 2019-04-19 08-38-21](https://user-images.githubusercontent.com/49685699/56425189-2dc99680-6281-11e9-9699-9721f8be5d3a.png)

Now ... setting metacity-theme-viewer to render an unfocused window and also making sure that the metacity-theme-viewer window does not have focus. Can you see the difference? metacity-theme-viewer draws a gray semi-transparent border, Marco draws it black opaque.
![Screenshot at 2019-04-19 08-41-12](https://user-images.githubusercontent.com/49685699/56425286-8ef16a00-6281-11e9-810e-713366d5bbf1.png)

Marco used to display this theme correctly, but that was back in the days of MATE 1.14 when Marco was gtk2 based.

**Comment by raveit65** [comment]
Ok, this is with metacity-theme-viewer. But does it work if metacity is active WM?
Here with metacity-3.30.1-3.fc30.x86_64 the theme won't display and metacity fallback to gtk+ decorations.
Well, this theme use pngs to write the decoration, but for some reasons the images for unfocus won't read.
```
[rave@mother ~]$ ls .themes/bisoft-light/metacity-1/ |grep unfocus
bottom-left-unfocus.png
bottom-middle-unfocus.png
bottom-right-unfocus.png
frame-left-unfocus.png
frame-right-unfocus.png
left-top-unfocus.png
right-top-unfocus.png
top-middle-unfocus.png
```

**Comment by muktupavels** [comment]
@raveit65 How did you test it? I just tried and theme works for me...

**Comment by baer63** [comment]
@raveit65 Yes I also tested it by switching to metacity as a window manager. Theme works perfect. Again - the problem is with Marco. There is nothing wrong with the theme.

**Comment by raveit65** [comment]
![Bildschirmfoto zu 2019-04-20 10-05-25](https://user-images.githubusercontent.com/961604/56454635-18716c80-6354-11e9-9334-4bae2b7ab366.png)
Same result if iuse metacity-theme name from index.theme
```
[rave@mother ~]$ cat .themes/bisoft-light/index.theme 
[X-GNOME-Metatheme]
Name=bisoft-light
Name[bg]=осветеност
Name[en_GB]=bisoft-light
Type=X-GNOME-Metatheme
Comment=Attractive Usability
Comment[bg]=Привлекателна лекота
Comment[en_GB]=Attractive Usability
Encoding=UTF-8
GtkTheme=bisoft-light
MetacityTheme=bisoft-win7
IconTheme=bisoft-icons
```
Why the hell is that different?

**Comment by muktupavels** [comment]
`gsettings get org.gnome.metacity.theme type` should return `metacity` not `gtk`. Name is relevant only if type is set to metacity.

**Comment by muktupavels** [comment]
I put themes in `.local/share/themes`.

**Comment by muktupavels** [comment]
Metacity does not read themes from `./themes`:
https://gitlab.gnome.org/GNOME/metacity/blob/master/libmetacity/meta-theme-metacity.c#L4563

**Comment by raveit65** [comment]
Do you really think i don't use it?
```
[rave@f30 ~]$ gsettings get org.gnome.metacity.theme type
'metacity'
[rave@f30 ~]$ gsettings get org.gnome.metacity.theme name
'bisoft-light'
```
>> Metacity does not read themes from ./themes:

.....another gnome limitation :)

**Comment by muktupavels** [comment]
Yeah, such a big limitation...

https://gitlab.gnome.org/GNOME/metacity/commit/52a524ee4a7e14d99451ea3f596b353ddf7957d4
4 years this change is in metacity and you are first to complain.

https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkcssprovider.c#L2075
GTK still loads from user's home directory so feel free to open bug if you care about this.

**Comment by raveit65** [comment]
> 4 years this change is in metacity and you are first to complain.

Honestly, i don't use gnome :)

**Comment by raveit65** [comment]
fixed https://github.com/mate-desktop/marco/commit/0c2baf71f18f39058edc8459990da27c4d448d81

**Comment by raveit65** [comment]
for  1.24 https://github.com/mate-desktop/marco/commit/17b7c90b471ab049c3860a0fcfcd8aa9580467e7
