### ISSUE TITLE
[Feature request] Edge-maximization only with a modifier held

### ISSUE THREAD

**Issue by dark-penguin** [mate-desktop/marco#489]
Maximizing a window by dragging it to a screen edge is a wonderful feature, and I want to use it. I would not use it very often, however I do drag my windows to the top or to the side very often, which causes them to maximize when I don't want that.

I suggest adding an option to engage edge-based maximization only when holding Shift (or some other key). Or at least the opposite - disable edge-based maximization and allow me to place my window normally, if I hold a modifier key.

**Comment by vkareh** [comment]
This is only for keyboard, as far as I remember, but there are shortcuts available for tiling top/down/right/left vs just moving the window to either of those directions. So the capability is definitely there and I wonder if having shortcuts set up for whichever of those you use less frequently would work for you. Then you could just disable the edge maximization and use the shortcut when you need it occasionally

**Comment by dark-penguin** [comment]
Oh! Thank you! I did not think it was called "tile window to the ...". Indeed, this is not only sufficient, but I would say preferable!
