### ISSUE TITLE
Make alt+tab window layout customizable/wider

### ISSUE THREAD

**Issue by stefanct** [mate-desktop/marco#492]
Since we got configurable icon sizes with #482 maybe someone familiar with the code already wants to fulfill a wish of mine ;) This is also somewhat related to  #68 depending on how we want to resolve this issue.

#### Expected behaviour
An alt+tab selection window that is large enough to properly display window titles if there is enough (horizontal) space to make the selection window bigger.

#### Actual behaviour
I think there is a hard limit of numbers of icons per row in the alt+tab window (5 in my version). Even with properly sized icons this is unnecessarily small and on high resolutions the alt+tab window is ridiculously small in comparison to the overall screen. This would be not an issue in itself (apart from aesthetics) since it uses a multi-row layout for the icons. However, it reduces the functionality because the title of the currently selected application/window could have way more space and is abbreviated if they are too long.

#### Steps to reproduce the behaviour

Open a lot of windows with long title texts and press alt+tab

#### MATE general version

1.16.2

#### Package version

1.16.1

#### Linux Distribution

Debian stable/stretch

#### Link to downstream report of your Distribution

Can do but I think think this should rather be discussed upstream since it is a design decision not a bug...

**Comment by vkareh** [comment]
Fixed by #497 

Since this change you can configure the number of columns, the icon size, and whether the popup expands to fit the title.
