### ISSUE TITLE
Missing meson buildsystem support

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/marco#522]
#### Expected behaviour
meson build system for using `ninja -C build dist` for creating taballs from master branch

#### Actual behaviour
`make distcheck` produces broken tarballs with .gmo files in /po dir.
This is the result of porting to gettext https://github.com/mate-desktop/marco/pull/494
See https://github.com/mate-desktop/mate-desktop/issues/382
or https://lists.gnu.org/archive/html/bug-gnu-utils/2006-11/msg00139.html
for more details

#### Steps to reproduce the behaviour
Run `make distcheck` on master and check po dir in tarball.

#### MATE general version
1.23.x

#### Package version
1.23.0 / master

#### Linux Distribution
all

#### Link to downstream report of your Distribution
no need of it , fedora maintainer is informed ;)

**Comment by yetist** [comment]
OK, I will do it.

**Comment by yetist** [comment]
Close it and finish with #527.
