### ISSUE TITLE
Does Marco support super+arrow key window snapping?

### ISSUE THREAD

**Issue by ifoolb** [mate-desktop/marco#524]
I installed marco alone on Arch Linux to use with LXQT. Does marco support window snapping via super key + arrow key as in Gnome shell, Windows?

**Comment by vkareh** [comment]
What do you mean by window snapping? Tiling? I have my tiling configured to use Super+Arrows to tile windows right and left, so yes it should work. You might need mate-settings-daemon to handle the key shortcut configuration...

**Comment by ifoolb** [comment]
sorry, my mistake. the setting  daemon is unnecessary. I thought '<Meta>' meant super key, and it's actually alt key. what is the key name for super key in Marco's gsettings?

**Comment by vkareh** [comment]
> what is the key name for super key in Marco's gsettings

Either `<Super>` or `Super_L` or `<Mod4>`, depending on your keyboard layout...

Is this still an issue? can this be closed or is something still broken on your side?

**Comment by ifoolb** [comment]
thanks, this works!
