### ISSUE TITLE
Undecorated and maximized window covers everything when moved between monitors

### ISSUE THREAD

**Issue by epsilontheta** [mate-desktop/marco#556]
#### Expected behaviour
Moving a maximized window from one monitor to another one will not lead to everything being covered by the window.
Holding alt and dragging or using the context menu and clicking unmaximize the window will change the state to unmaximized.

#### Actual behaviour
The window will cover panels, docks, etc. and there is no way to change the state of the window to unmaximized.

#### Steps to reproduce the behaviour
* create panel on top on primary monitor
* set org.mate.maximus undecorate = true
* create window on second monitor (no panels at all)
* maximize
* move window to primary monitor using shortcut

#### MATE general version
1.22.2

#### Package version
1.22.2-1

#### Linux Distribution
Arch Linux

#### Link to downstream report of your Distribution
n/a

**Comment by lukefromdc** [comment]
Any chance this is a bug in mate-netbook (maximus etc) and not marco? This looks like maximus is trying to create a maximized but not fullscreen undecorated window, and when there is nothing else on the monitor this is the same as a fullscreen window so perhaps it then tells the WM to fullscreen it? Moving a fullscreen window between monitors normally covers all of each monitor you move it to, so if anything is telling marco these are fullscreen windows this is exactly what you would get. 

On the other hand, if marco itself can't tell the difference between an undecorated maximized window and an undecorated fullscreen window and maximus is calling it maximized only, then we do in fact have a bug in marco.  Are there any good test cases for this with mate-netbook not installed?

Normally, a fullscreen undecorated window seems to be the only common case of a maximized and undecorated window excluding the desktop window (which moves to accomodate panel struts) and the root window.  Firefox, pluma, or mate-terminal maximized with F-11 cover and are supposed to cover panels and everything onscreen, and for a fullscreen video or game not to use all of the screen is a nasty bug.

**Comment by epsilontheta** [comment]
To be honest I don't know the mate stack so well, because I just switched from another DE.
I performed a little test using this script:
```
#!/usr/bin/env python

from ewmh import EWMH
ewmh = EWMH()

# get every displayed window
wins = ewmh.getClientList()
for w in wins:
	print (ewmh.getWmName(w))
	print (ewmh.getWmState(w, True))
```

The result for a window that was maximized on the monitor without panels:
```
_NET_WM_STATE_FULLSCREEN
```

When maximizing another window on the monitor with panels:
```
_NET_WM_STATE_MAXIMIZED_HORZ
```

So I guess your hypothesis is correct and it is a mate-netbook bug in maximus?

**Comment by epsilontheta** [comment]
Workaround:

Create panel on second monitor as well and change state of application to maximized with this script:
```
#!/usr/bin/env python

import sys
from ewmh import EWMH
ewmh = EWMH()

# get every displayed windows
wins = ewmh.getClientList()
argvwins = filter(lambda w: sys.argv[1] in w.get_wm_class()[1], wins)
for w in argvwins:
	print ("Setting state of {} to maximized".format (ewmh.getWmName(w)))
	ewmh.setWmState(w, 0, '_NET_WM_STATE_FULLSCREEN')
	ewmh.setWmState(w, 1, '_NET_WM_STATE_MAXIMIZED_HORZ')
	ewmh.setWmState(w, 1, '_NET_WM_STATE_MAXIMIZED_VERT')

ewmh.display.flush()
```

```
./change-winstate.py <application window title>
```

Then everything works as expected.

**Comment by lukefromdc** [comment]
I would guess that indicates a maximus bug, though I am not 100% sure as I'm not sure where exactly the window state is being assigned

**Comment by epsilontheta** [comment]
Stumbled over this line: https://github.com/mate-desktop/marco/blob/1.22/src/core/main.c#L320
Seems like there is an option to disable this behaviour in marco.
Closing bug.
