### ISSUE TITLE
Tooltips persist across virtual desktops

### ISSUE THREAD

**Issue by mrj** [mate-desktop/marco#56]
If an application is made to display a tooltip, and the virtual desktop (workspace) is switched using a keyboard shortcut that doesn't have a side-effect of turning off that tooltip, the tooltip will be inappropriately displayed on all workspaces, and can only be removed by returning to the original workspace.

For me this most commonly happens with tooltips displayed by the Chrome browser when workspaces are switched by CTRL-LEFT and CTRL-RIGHT key combos.

**Comment by monsta** [comment]
Does it still happen in 1.12?

**Comment by mrj** [comment]
No, appears to be fixed.
