### ISSUE TITLE
Shortcuts to move windows between workspaces

### ISSUE THREAD

**Issue by piranna** [mate-desktop/marco#567]
~Add keyboard shortcuts to allow to move currently focused app window between screens in a multi-monitor environment. A plus would be to also allow to move it to other workspace and set focus on the next app window in current workspace :-)~

Add keyboard shortcuts to allow to move currently focused app window to other workspace,  and set focus on the next app window available in current workspace.

Since you can move between workspaces with some shortcuts, to move windows to them would have similar based ones. Another non-incompatible alternative would be, since workspaces have some kind of "spatial layout" similar to multi-monitor environments, I think the most easy way to implement it would be by using the same shortcuts to move windows between monitors, and when reaching the last "real world" monitor, fall to the first virtual monitor in the first workspace next to that. It depends about what behavior do you want to be it more inspired on, multi-monitor windows move or workspace switching :-)

**Comment by vkareh** [comment]
This already exists. Go to the Keyboard Shortcus app and scroll until you find these:
![Screenshot at 2019-10-23 07-59-21](https://user-images.githubusercontent.com/259780/67390682-22766100-f56b-11e9-9892-11af02eb9016.png)

**Comment by piranna** [comment]
When was this added? Last time I tried in a multi-monitor system was less than a year ago and was not available...

By the way, what key is "Mod4"?

**Comment by vkareh** [comment]
Mod4 is the Super key (or Windows key)

**Comment by piranna** [comment]
> Mod4 is the Super key (or Windows key)

Nice, good to know, I need to try it then :-)

Is the request for multiple workspaces still valid? I don't have my linux laptop here to check it myself.

**Comment by vkareh** [comment]
Yes, that would be a new feature. If you could update the description to be more specific about what behavior you want and how you would use it, I can go over it and tag it :)

**Comment by piranna** [comment]
Updated description :-)

**Comment by vkareh** [comment]
I just tried these two methods and they seem to work:

![Screenshot at 2019-10-24 07-57-27](https://user-images.githubusercontent.com/259780/67483646-40f45f00-f634-11e9-9c78-e40beca150b3.png)

![Screenshot at 2019-10-24 07-59-17](https://user-images.githubusercontent.com/259780/67483647-40f45f00-f634-11e9-9ce9-fe4b866a5122.png)

Is this the functionality you're looking for? It sounds as though you want a keyboard shortcut for the "Move to Workspace Left/Right" functionality, correct?

**Comment by piranna** [comment]
> Is this the functionality you're looking for? It sounds as though you want a keyboard shortcut for the "Move to Workspace Left/Right" functionality, correct?

Seems to be that ones, yes. Honestly I didn't found them on Ubuntu Mate the other times I tried it, not sure if it goes too much back compared to upstream version...

**Comment by piranna** [comment]
That, or a lack of easy to find documentation about these features :-)

**Comment by piranna** [comment]
Not sure if it was added recently, nor if it's the same thing, but if so, not only they are disable by default (fair enough), but the translation is totally a disaster... It's not understable, grammar is confuse, and in some cases it's plainlo wrong. Maybe that's the reason I didn't find the options before?

![Captura de pantalla -2019-10-24 20-38-48](https://user-images.githubusercontent.com/532414/67515253-982f1980-f69e-11e9-8302-9944c354c666.png)

**Comment by raveit65** [comment]
> but the translation is totally a disaster... It's not understable, grammar is confuse, and in some cases it's plainlo wrong. Maybe that's the reason I didn't find the options before?

We use transifex website for our translations.
https://www.transifex.com/mate/MATE/dashboard/
Open an account, become a member of your language and please fix the translations.
We always pull new translations from time to  tom from transifex before we release new application versions.
I assume we can close this issue?
If you dont agree i will re-open it.

Thanks

**Comment by piranna** [comment]
Great, I'll take a look on the translations :-)
