### ISSUE TITLE
Decoration edge glitches with HIDPI, window is in tililing mode and a vertical panel is used

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/marco#573]
#### Expected behaviour
Clear and sharp edges with HIDPI, window is in tililing mode and a vertical panel is used.

#### Actual behaviour
Decoration edge glitches with HIDPI, window is in tililing mode and a vertical panel is used.
It happens only when i use a third vertical panel which is my default.
When using only top and bottom panel, or moving the third panel away from monitor edges, than the top right corner of the window looks OK for me.

With third vertical panel: (bad dark line and a step at the edge)
![marco-border-bad](https://user-images.githubusercontent.com/961604/68330591-cfa4b980-00d3-11ea-8c41-43a12d90a2de.png)

Without third vertical panel:
![marco-border-good](https://user-images.githubusercontent.com/961604/68330637-e2b78980-00d3-11ea-9027-910ca1f47e9b.png)

For some reasons the issue isn't there for all window sizes when you cycle the window. New feature from https://github.com/mate-desktop/marco/pull/568
(row cycles the window through different sizes (1/2 -> 1/3 -> 1/4 -> 3/4 -> 2/3 -> Untiled)
1/2 -> bad
1/3 -> bad
1/4 -> good
3/4 -> good
2/3 -> good

Note, you only see that with HIDPI and a light theme without a dark borders like Menta themes.
With a theme with dark borders, eg. BlueSubmarine you don't see the issue.

#### Steps to reproduce the behaviour
Use a vertical panel, Hidipi and use tiling mode for a window.

#### MATE general version
Master, 1.22, 1.20 since HIDPI support

#### Package version
Master, 1.22.x, 1.20.x since HIDPI support.

#### Linux Distribution
fedora

#### Link to downstream report of your Distribution
Not needed.

original report from https://github.com/mate-desktop/marco/issues/496

**Comment by raveit65** [comment]
For some reasons the behaviour is different now with 1.240 when in tiling mode.
With the main window size for quarter-tiling the issue is gone :)
(row cycles the window through different sizes (1/2 -> 1/3 -> 1/4 -> 3/4 -> 2/3 -> Untiled)
1/2 -> good
1/3 -> bad
1/4 -> good
3/4 -> good
2/3 -> bad

I will close the issue because i am not using 1/3 or 2/3 windows-size usually, in result i don't care any more;)
We can always re-open the issue when someone is bother by this issue or someone likes to fix it.

**Comment by lukefromdc** [comment]
The different sizes affecting this look like what would be expected from rounding errors in calculating decoration sizes, and imply theme choices could also effect this.
