### ISSUE TITLE
marco crushes whenever a window closes

### ISSUE THREAD

**Issue by kwanzapili** [mate-desktop/marco#576]
#### Expected behaviour
Window closes cleanly

#### Actual behaviour
Consistent crashes by marco

#### Steps to reproduce the behaviour
Open any window then close it

#### MATE general version
1.22

#### Package version
marco-1.22.4
glib2-2.62.4 (or glib2-2.62.3)
cairo-1.16.0
gtk-3.24.13
mate-desktop-1.22.2

#### Linux Distribution
Mate is compiled from source but base OS is openSUSE Leap 15.1

Backtrace attached:
[mate-bt.txt](https://github.com/mate-desktop/marco/files/4022536/mate-bt.txt)

**Comment by pasikarkkainen** [comment]
I'm seeing similar behaviour on Fedora 30, with marco 1.22.4, but for me it happens randomly, not all the time.. most often marco crashes when I close some window of firefox.

**Comment by pasikarkkainen** [comment]
in kernel dmesg I see:
traps: marco[11544] general protection fault ip:7f2d6ccbdad4 sp:7ffc76e39c18 error:0 in libcairo.so.2.11600.0[7f2d6cc6a000+cf000]

**Comment by raveit65** [comment]
Closing this in favour of https://github.com/mate-desktop/marco/issues/598,
which has same backtrace.
