### ISSUE TITLE
Switching Workspaces

### ISSUE THREAD

**Issue by AngeloGomes** [mate-desktop/marco#58]
Examples:
1) If one window is maximized in a workspace, when you go to other workspace, that maximized windows is carried together to other workspace
2) If two or more windows maximized in a workspace, when you go to other workspace, that maximized and with focus windows is carried together to other workspace. 
3) If you have two maximized windows, when you switch to another workspace, one of the is carried as I said and the other is minimized.

**Comment by monsta** [comment]
Does it still happen in 1.10?

**Comment by monsta** [comment]
Well, if there won't be any more feedback about 1.10 or 1.12, I'll consider this already fixed at some point.
