### ISSUE TITLE
Window switcher selection border hard to see in dark theme

### ISSUE THREAD

**Issue by trongthanh** [mate-desktop/marco#603]
#### Expected behaviour

The selection border of window switcher should use some highlight color from GTK theme so that it stands out regardless of light or dark theme.

#### Actual behaviour

The selection border is always black which is very hard to distinguish in dark theme and low back light. See photo for example:

![Screenshot 2020-03-04 22:41:38](https://user-images.githubusercontent.com/234226/75899609-51cca100-5e6e-11ea-81ab-0cdb83bbe133.png)

#### Steps to reproduce the behaviour

- Change to Ambiant-MATE-Dark controls and window border
- Enable Redshift
- Try switching windows with Alt-Tab

#### MATE general version
Ubuntu 19.10
MATE 1.22.2

**Comment by protivinsky** [comment]
I am having the same issue - for instance with "High Contrast Inverse" theme, the border is completely invisible.
Trongthanh suggestion to use some highlight color from theme would be great; even just being able to override the border color via theme's CSS would be helpful.

**Comment by raveit65** [comment]
The alt-tab-switcher is already re-worked with MATE 1.24, you should update....
Screenshot with our default and reference theme Menta (Blue-Menta) which shows the highligt color from Gtk-theme, which is blue, with the new alt-tab-switcher
![Bildschirmfoto zu 2020-03-07 16-34-53](https://user-images.githubusercontent.com/961604/76146334-10b4d680-6092-11ea-997e-597471b79301.png)
I guess the small dark edge in my screenshot is another error by using the new feature invisible-borders and should be fixed.
@vkareh ^^^^

Btw. fedora 32 and Ubuntu-20.04 will come with MATE 1.24.

**Comment by trongthanh** [comment]
Awesome. Anyway, I guess there's some glitch to fix before this can be closed. I can't wait to try Ubuntu MATE 20.04

**Comment by protivinsky** [comment]
Great, thanks - sadly I am stuck on Amazon Linux with Mate 1.20, with no easy option to upgrade. But good to hear it had been already improved.

**Comment by raveit65** [comment]
I think it's better to have a new report which describes the glitches with new UI better than this report.

Btw. MATE 1.20 is EOL since more than 2 years. You will never get updates or fixes.
