### ISSUE TITLE
[PATCH] popup workspace selector hard to read when compositing is disabled

### ISSUE THREAD

**Issue by william8000** [mate-desktop/marco#622]
#### Expected behaviour

The pop-up workspace selector should make the currently selected workspace easy to identify.

#### Actual behaviour

When Fedora 31 updated from mate 1.22 to 1.24, the colors of the pop-up workspace selector changed, and the selected workspace became hard to identify when compositing is disabled.
The currently selected workspace is now marked by a thin white border.
The thin white border works well against the black background when compositing is enabled but is hard to see against the light gray background when compositing is disabled.

#### Steps to reproduce the behaviour

Use "Menu -> System Preferences -> Windows -> Window Preferences -> Enable software compositing window manager" to disable the compositing window manager and then use the keys to switch workspaces. (I changed mine to control+arrow key. I think that the default is shift+control+arrow key.)

#### MATE general version

1.24.0

#### Package version

marco-1.24.0-1.fc31

#### Linux Distribution

Fedora 31

#### Link to downstream report of your Distribution

The downstream report has screen captures and my proposed patch.
https://bugzilla.redhat.com/show_bug.cgi?id=1836408

![marco-diff-25may20](https://user-images.githubusercontent.com/1887814/82842787-c3971280-9ed2-11ea-83b7-824fb4124d8b.png)

```
--- marco-1.24.0/src/ui/tabpopup.c-     2020-02-10 11:26:47.000000000 +0000
+++ marco-1.24.0/src/ui/tabpopup.c      2020-05-25 21:01:59.792425348 +0100
@@ -1126,7 +1126,16 @@
       gtk_style_context_set_state (context,
                                    gtk_widget_get_state_flags (widget));
 
-      meta_gtk_style_get_light_color (context, GTK_STATE_FLAG_SELECTED, &color);
+      if (meta_prefs_get_compositing_manager ())
+        {
+          /* compositing manager creates a dark background: show the selection in a light color */
+          meta_gtk_style_get_light_color (context, GTK_STATE_FLAG_SELECTED, &color);
+        }
+      else
+        {
+          /* non-compositing creates a light background: show the selection in a dark color */
+          meta_gtk_style_get_dark_color (context, GTK_STATE_FLAG_SELECTED, &color);
+        }
 
       cairo_set_line_width (cr, SELECT_OUTLINE_WIDTH);
       cairo_set_source_rgb (cr, color.red, color.green, color.blue);
```

**Comment by raveit65** [comment]
Can you do a pull request please?

**Comment by raveit65** [comment]
@vkareh 
Looks like this is a leftover from your code change.
https://github.com/mate-desktop/marco/pull/566

**Comment by raveit65** [comment]
Fixed with https://github.com/mate-desktop/marco/commit/6bd23de6529ede9e8626263ecc39db3bf8aeb568
