### ISSUE TITLE
marco with mate-maximus issues

### ISSUE THREAD

**Issue by dasebastian78** [mate-desktop/marco#626]
#### Expected behaviour
All windows should be forced to open maximized. No window decoration (title bar, buttons). Menu in the Global Application Menu in top panel.

#### Actual behaviour
Programs open in 49% wrong, this means, they are maximized, use the Global Application Menu BUT have title bar with buttons under the top panel. I have to press Alt+F10 (or any other set keybinding) to maximize them as wished. See screenshot below:

![Marcostatistik Screenshot](https://user-images.githubusercontent.com/66718450/84238629-a0d44300-aafb-11ea-96a6-b41544a3702f.png)

![NO](https://user-images.githubusercontent.com/66718450/84239469-d168ac80-aafc-11ea-855d-f7bbddf7fd15.png)

BTW: tried Compiz, did it right, as expected. But don't want to use Compiz.

#### Steps to reproduce the behaviour
Mate Tweak - Windows - set hook at "Don't decorate maximized windows", deselect hook at "Do not maximize new windows automatically", Marco adaptive.
Mate-Maximus in Autostart.

#### MATE general version
Mate 1.24.0

#### Package version
Marco 1.24.0

#### Linux Distribution
Ubuntu MATE 20.04

**Comment by raveit65** [comment]
> #### Link to downstream report of your Distribution


Mate tweak is a ubuntu production. Please file out a report there.

**Comment by dasebastian78** [comment]
Sorry, I am not experienced in that. Where? On launchpad?
