### ISSUE TITLE
marco compiz conflict

### ISSUE THREAD

**Issue by Temujin0** [mate-desktop/marco#627]
#### Actual behaviour i get two windows previews while running compiz one from compiz the other marco. Running f32 and have 
No control of marco using dconf-editor. I always get 2 previews unless using marco then just 1

#### MATE general version
1.24.0

#### Package version
No idea

#### Linux Distribution

Fedora 32
#### Link to downstream report of your Distribution
Umknown

**Comment by lukefromdc** [comment]
Compiz has the "window previews" option that can be turned on or off from CCSM, and mate-panel's window list applet (part of wncklet) has in its preference dialog(right click the applet handle to bring it up) the "show thumbnails on hover" option under "Window Thumbnails." On changing that you will need to restart mate-panel for it to take effect at this time. That is simple: run "killall mate-panel" and the panel will restart.

To see one set of previews you need to have one of these on and the other off of course when running compiz.

**Comment by Temujin0** [comment]
Thank you .one of the other devs email me this last night.

I use to know this lol. Its been 7 years since I ran a linux distro. I have
to catch up and remember.

Thank again.
