### ISSUE TITLE
meta_rectangle_edge_aligns: Process /usr/bin/marco was killed by signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/marco#63]
Orginal report at fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=1011869

 glad08 2013-09-25 05:53:15 EDT

Description of problem:
I close my programs and logout, then log in again and marco crashes. In general, I use compiz, bat afaik marco starts before compiz and after that compiz replaces it.

Version-Release number of selected component:
mate-window-manager-1.6.2-3.fc19

Additional info:
reporter:       libreport-2.1.7
backtrace_rating: 4
cmdline:        marco
crash_function: meta_rectangle_edge_aligns
executable:     /usr/bin/marco
kernel:         3.11.1-200.fc19.x86_64
runlevel:       N 5
type:           CCpp
uid:            1000
var_log_messages: Sep 25 13:33:13 localhost abrt[29721]: Saved core dump of pid 29090 (/usr/bin/marco) to /var/tmp/abrt/ccpp-2013-09-25-13:33:12-29090 (20348928 bytes)
```
Truncated backtrace:
Thread no. 1 (10 frames)
 #3 meta_rectangle_edge_aligns at core/boxes.c:1159
 #4 apply_edge_resistance at core/edge-resistance.c:391
 #5 apply_edge_resistance_to_each_side at core/edge-resistance.c:610
 #6 meta_window_edge_resistance_for_move at core/edge-resistance.c:1162
 #7 update_move at core/window.c:7010
 #8 meta_window_handle_mouse_grab_op_event at core/window.c:7450
 #9 event_callback at core/display.c:2039
 #10 filter_func at ui/ui.c:209
 #11 gdk_event_apply_filters at gdkevents-x11.c:356
 #12 gdk_event_translate at gdkevents-x11.c:946
```
backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=802671
core_backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=802673

**Comment by NiceandGently** [comment]
The issue still exists with 1.10, see
https://bugzilla.redhat.com/show_bug.cgi?id=1226530
@flexiondotorg 
please re-open

**Comment by NiceandGently** [comment]
maybe trhis metacity bugs are related
https://bugs.launchpad.net/ubuntu/+source/metacity/+bug/437139
https://bugzilla.gnome.org/show_bug.cgi?id=603632

**Comment by NiceandGently** [comment]
@infirit 
@flexiondotorg 
the issue still exits in fedora 22
https://bugzilla.redhat.com/show_bug.cgi?id=1226530
please re-open

**Comment by monsta** [comment]
This bug is inherited from metacity, so all other WMs from the family (marco/mutter/muffin) are affected as well.

The details are in [this mutter bug report](https://bugzilla.gnome.org/show_bug.cgi?id=608800).
The patch has been pushed into mutter code (see [this commit](https://git.gnome.org/browse/mutter/commit?id=2a823ef3e4861d795ec22a93aaaf8ce6a660934e)), but I can't find it in metacity. Maybe they forgot it...

**Comment by infirit** [comment]
Please confirm https://github.com/infirit/marco/commit/e2d95495f6c67446cfc642c238f05201eb9d0744 solves the problem.

**Comment by NiceandGently** [comment]
@infirit 
Thanks
I'ts a bit hard to test as i never got this crash for myself, and i don't know to trigger the crash.
```
 Kamil J. Dudek 2014-12-04 08:46:23 EST

Description of problem:
Moving the window across the monitors on the same desktop.

Version-Release number of selected component:
marco-1.8.2-5.fc21
```
And i don't have a second monitor to test this description.
But i can do a scratch build and ask reporters to test it.

**Comment by infirit** [comment]
No hurries :smile_cat:

**Comment by NiceandGently** [comment]
Ok, the fix runs here since a day without any **Collateral Damage**.
I've done scratch builds and asked reporter in reports to test it.

**Comment by monsta** [comment]
GTK+2 build runs fine for me. Unfortunately, I can't reproduce the issue, so I can only state there are no regressions here.

**Comment by NiceandGently** [comment]
@infirit 
Can you please do a PR?
I found no regressions here in gtk3 version since 15 days.
I got no feedback from reporters but i want to close the downstream reports.

**Comment by NiceandGently** [comment]
fix with
https://github.com/mate-desktop/marco/commit/105c6eb2116ab5db0157b272a22243bba1ae50ef
