### ISSUE TITLE
Marco undecorate

### ISSUE THREAD

**Issue by Ygarr** [mate-desktop/marco#659]
#### Expected behaviour
Undecorate functionality

#### Actual behaviour
Undecorates ONLY fullscreen windows

#### Steps to reproduce the behaviour
Any way. Feature request. e.g. Right mouse click option or another tool like wmctrl

#### MATE general version
last

#### Package version
mate-desktop-1.24.1-1

#### Linux Distribution
Any

**Comment by Cyrille37** [comment]
Hi
Do you mean all windows without title bar like with gnome3 ?

Actually there are 2 horizontal bars: one for the window title & buttons, one for application menu. Like with gnome 3 (I think), window buttons could be on left or right of the application menu to save vertical space.

**Comment by Ygarr** [comment]
Hi I mean one specified chosen window like in ... openbox.

It`s all about the horizontal bar  for the window title & buttons.

It would be great to have such functionality, if you please
![marcoScreenshot_2021-05-19_02-21-05](https://user-images.githubusercontent.com/14309871/118735512-471ae380-b849-11eb-91be-8b55d5eba151.png)
:

**Comment by Ygarr** [comment]
then 
![marcoScreenshot_2021-05-19_02-21-40](https://user-images.githubusercontent.com/14309871/118735536-50a44b80-b849-11eb-9a98-a4279b03f170.png)

**Comment by lukefromdc** [comment]
A fullscreen window of course is undecorated by definition, and many of the (heavier) compositing window managers such as Compiz, Mutter, Cinnamon etc offer an option also to unredirect them (render straght to screen presumably) and save resources. A MAXIMIZED window if undecorated becomes a de facto fullscreen window but can be different in code. As I recall this has generated some issues from time to time with unmaximizing such windows-and probably in many window managers

**Comment by Cyrille37** [comment]
Hi,
I like the idea to keep window control buttons to help unadvanced users, but place them at menu level to save vertical space like in 2) or 3) in this picture:
![image](https://user-images.githubusercontent.com/368965/118764753-51090a80-b87a-11eb-97d8-346b1ca3cc64.png)

**Comment by Cyrille37** [comment]
> so such UI changes are out of the question.

Thanks for your really clear answer :-)

MATE desktop is really great, i still use it for a long. Thanks a lot for this nice job <3

**Comment by Cyrille37** [comment]
Perhaps this issue could be closed ;-)
