### ISSUE TITLE
Compositor Broken in ways humanity needs to keep secret

### ISSUE THREAD

**Issue by ata-star** [mate-desktop/marco#665]
#### Expected behaviour
Not being chunk side shifted

#### Actual behaviour
being like this 
![IMG_20210205_042049](https://user-images.githubusercontent.com/62115669/106986004-c38e2880-676a-11eb-8510-15d229b3910a.jpg)

#### Steps to reproduce the behaviour
use a bad tv requiring the 1360×768 res
Turn on compositor

#### MATE general version
1.24 i guess
Not sure tbh

#### Package version
Uff, where?

#### Linux Distribution
Ubuntu MATE 20.04

#### Link to bugreport of your Distribution (requirement)
Like the message on discord?

#### actual important information

The compositor is like shifting the screen for some reason.
Im not that good at the stuff but other resulutions work fine but most lower ones and well ... dunno

Pls fix or i get my mom and she yells at you >:[

Ps: crusty kwispy redmond xp cloning in bottom here

![IMG_20210205_043847](https://user-images.githubusercontent.com/62115669/106986755-5380a200-676c-11eb-921b-2b165eec9bd1.jpg)

**Comment by lukefromdc** [comment]
This is almost impossible to understand, needs to be rewritten and get a new description. Feel free to reopen it after fixing those
