### ISSUE TITLE
Vertical Alt-Tab window

### ISSUE THREAD

**Issue by epitron** [mate-desktop/marco#68]
Hi there!

I'm really loving Mate. Switching back to a Gnome2-style desktop after using XFCE4 for over a year feels really good. :)

I wanted to suggest a feature for Marco's Alt-Tab window -- vertical layout:
http://www.ntwind.com/software/vistaswitcher/screenshots.html

I'm a big fan of this layout -- it lets you see the full window titles, and there's something more intuitive about the recently used windows being on the top of a stack, instead of on the left of a row of icons.

Would this be reasonably simple to implement, given Marco's current codebase?
##

**Comment by sgtpep** [comment]
I hope to see this feature one day, too. Got used to it from Openbox.

**Comment by epitron** [comment]
xfwm4 has this option now, if you don't mind using it instead of mate's WM... It's in Window Manager Tweaks / Cycling / Cycle through windows in a list.

**Comment by vkareh** [comment]
This can be accomplished by setting the max columns to 1:
```
gsettings set org.mate.Marco.general alt-tab-max-columns 1
```
![Screenshot at 2019-10-31 12-57-57](https://user-images.githubusercontent.com/259780/67968663-2eeb6100-fbde-11e9-9918-e7b490f17684.png)
