### ISSUE TITLE
Firefox 89 Webrender rendering issue with "marco + compositing" window manager

### ISSUE THREAD

**Issue by jgmm81** [mate-desktop/marco#687]
#### Expected behaviour

Runs normally Firefox 89 with proton UI and rendering with "marco + compositing" window manager and Firefox hardware acceleration option enabled

#### Actual behaviour

The web browser firefox 89 with on new "Proton user interface" and hardware acceleration enabled cannot run (crash) on linux mint mate version 20x using window manager set to (Marco + Compositing)

#### Steps to reproduce the behaviour

Update to Firefox 89 with Proton UI and run

#### MATE general version

Mate 1.24.0

#### Package version

Ulyssa 64-bit

#### Linux Distribution

Linux Mint Mate 20.1

#### Link to bugreport of your Distribution (requirement)

https://bugzilla.mozilla.org/show_bug.cgi?id=1715429

**Comment by jgmm81** [comment]
I have found the root of the problem and its solution

    I use an HP EliteBook G1, Intel i5 i5-4300U (With Haswell-ULT Integrated Graphics Controller GPU)

    I installed lunux mint 20.2 with the Intel screen tearing setting (to correct a problem when displaying graphics)
    URL: https://askubuntu.com/questions/1066722/intel-screen-tearing-ubuntu-18-04

2.1 Settings are
File: /etc/X11/xorg.conf.d/20-intel.conf

Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "TearFree" "true"
EndSectio

By not specifying the option (Option "AccelMethod") it defaults to the acceleration "sna"

The "sna" acceleration works well until Firefox 88, with version 89 and the new graphical interface starts the problem

3 how did i fix them?
I added the (Option "AccelMethod" "uxa") section as follows:

File: /etc/X11/xorg.conf.d/20-intel.conf

Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "AccelMethod" "uxa"
Option "TearFree" "true"
EndSection

More info
http://cynic.cc/blog/posts/sna_acceleration_vs_uxa/
https://manpages.debian.org/testing/xserver-xorg-video-intel/intel.4.en.html

**Comment by jgmm81** [comment]
For those who use the DisplayLink drivers on the computer, the interface error with Firefox89 + is also represented

URL DisplayLink Drivers
https://github.com/AdnanHodzic/displaylink-debian

When installing them, the option ("AccelMethod" "uxa") must be indicated in the following file

File: /etc/X11/xorg.conf.d/20-displaylink.conf

Section "Device"
     Identifier "Intel"
     Driver "intel"
     Option "AccelMethod" "uxa"
EndSection

Note: If in the installation of the Displaylink drivers there is a chmod error and interrupts the installation

1. edit the displaylink-debian.sh file
2. Find all of the following matches (without quotes) "displaylink-driver - $ {version}."
3. change the dot (.) To the symbol (-) closing the key symbol
Example
Before:
displaylink-driver - $ {version}. [0-9] *

After
displaylink-driver - $ {version} - [0-9] *

I tried again

**Comment by jgmm81** [comment]
*UPDATE*

I found that the acceleration by (Option "AccelMethod" "uxa") on my laptop (HP EliteBook G1, Intel i5 i5-4300U) has an issue when it comes back from sleep that the screen is black and only shows the mouse pointer

How did I solve it?
I changed the parameters by activating DRI3 and now it works much better as when it was in (Option "AccelMethod" "sna") by default

Note: Just specify these options in the file: "/etc/X11/xorg.conf.d/20-intel.conf"

Section "Module"
    Load "dri3"
EndSection

Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
    Option "DRI" "3"
EndSection

If you are using the drivers for the DisplayLink ports, do the following:

URL DisplayLink Drivers
https://github.com/AdnanHodzic/displaylink-debian

1. Leave blank or comment everything related to (DRI3) in the file "/etc/X11/xorg.conf.d/20-intel.conf"

2. Edit the file "/etc/X11/xorg.conf.d/20-displaylink.conf" only specifying the following:

Section "Module"
    Load "dri3"
EndSection

Section "Device"
    Identifier "Intel"
    Driver "intel"
    Option "DRI" "3"
EndSection

Note: If in the installation of the Displaylink drivers there is a chmod error and interrupts the installation

    a. Edit the displaylink-debian.sh file
    b. Find all of the following matches (without quotes) "displaylink-driver-${version}."
    c. change the dot (.) To the symbol (-) closing the key symbol
    
Example
Before:
 displaylink-driver-${version}.[0-9]*

After
 displaylink-driver-${version}-[0-9]*

More info:
https://en.wikipedia.org/wiki/Direct_Rendering_Infrastructure
https://wiki.archlinux.org/title/intel_graphics   (the commands works with Linux mint mate)

**Comment by lukefromdc** [comment]
Hardware acceleration on marco means using it with Compton, most likely an issue there meant an incompatability with Firefox hardware acceleration. While Compton and MATE are widely used together, we are not the maintainers of Compton and they need to know if this is still going on.

Firefox is now at version 115. Compton may have  changed a lot too. I would suggest testing wtih current firefox and current Compton, and if the issue still exists open an issue with Compton. We can't do anything about it here UNLESS compton and firefox work with some other WM supporting Compton but not in Marco. If that is so I will reopen this
