### ISSUE TITLE
New marco release to fix the surface leak

### ISSUE THREAD

**Issue by pasikarkkainen** [mate-desktop/marco#690]
It'd be nice to have new release(es) of marco to fix the recently fixed surface leak (https://github.com/mate-desktop/marco/commit/8f204678be6d888ad1d2904e28af1aa9f2ad8e11) as that's an annoying bug, which i'm definitely seeing in my environments.

If possible it'd be nice to have the fix backported to 1.24 branch aswell, so that Fedora 34 marco-1.24 rpms can be updated.

Thanks!

**Comment by raveit65** [comment]
Already done since 3 weeks :)
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2bebf0804ehttps://github.com/mate-desktop/marco/commit/76da06f80107bd554f22be3dfe6798a35dc1bb83

**Comment by pasikarkkainen** [comment]
Oh, I totally missed that :) I'll give marco-1.24.2-2.fc34  a go. Thanks a lot!
