### ISSUE TITLE
Enabling "Do not show window content when moving windows" does not let resizing window in half/quarter screen when dragging to a border

### ISSUE THREAD

**Issue by Porrumentzio** [mate-desktop/marco#694]
#### Expected behaviour
Even if the content of the window is not shown when moving it, dragging it to a border should adapt it to a quarter, half or entire screen; always if "Enable window fitting" is enabled.

#### Actual behaviour
When not showing content, the border-resize does not happen.

#### Steps to reproduce the behaviour
1. Enable window fitting (`Mate Tweak > Windows > Window behaviour > Enable  window fitting`)
2. Enable not showing content (`Mate Tweak > Windows > Efficiency > Do not show window content when moving windows`)
3. Drag a window to a border and it won't be resized as expected

#### MATE general version
1.26

#### Package version
1.26

#### Linux Distribution
Manjaro Linux MATE

#### Link to bugreport of your Distribution (requirement)
manjaro.org

**Comment by mbkma** [comment]
That is to be expected, because MATE Tweak (which btw is not part of the MATE Desktop) binds the settings "Do not show window content when moving windows" to the "Reduced resources" option from Marco. So this really is just a description issue from MATE Tweak, you should open a bug report there.
