### ISSUE TITLE
Marco is based on which Metacity version?

### ISSUE THREAD

**Issue by chdslv** [mate-desktop/marco#696]
Marco is based on which Metacity version?

**Comment by lukefromdc** [comment]
Nobody seems to know for sure exactly what version of GNOME 2 (though presumably somewhere after the LAST release GNOME 2.32) was forked to initially create MATE

**Comment by chdslv** [comment]
So, Marco is the window manager that was forked from the Metacity version at that time? Like Metacity version 2.32?

**Comment by mbkma** [comment]
Initial commit for Marco was 02.12.2011. Just look at the git history at both projects (run `gitk` in the cloned repos) and you can figure it out yourself.

**Comment by chdslv** [comment]
Its been a long time, pretty hard to figure that out by myself. If you know, could you enlighten me? Thanks!

**Comment by mbkma** [comment]
Comparing the git histories of both projects it seems like Marco was forked from version 2.34.1 of Metacity.

**Comment by chdslv** [comment]
Thanks.
Is today's Marco, of Mate 1.26 re-forked from the today's Metacity 3.40? Or, is it still the former fork?

**Comment by raveit65** [comment]
No, why we should re-forking our applications?
We have a own development.

**Comment by lukefromdc** [comment]
To my knowledge there has never been a refork of any MATE component, though a lot of useful commits from GNOME components have been backported.
