### ISSUE TITLE
Automatic Opacity Effect

### ISSUE THREAD

**Issue by peneus** [mate-desktop/marco#71]
It was a lot more efficient when I could use this compiz affect on Ubuntu 10.04 (in gnome 2). 

Here is the description: When you move the mouse away from window X to  
window Y, window X becomes transparent so that window Y can be seen if it 
is behind window X.

This is the most important feature I miss from gnome 2. 
##

**Comment by monsta** [comment]
That's why Compiz exists, let's leave complex visual features to it
