### ISSUE TITLE
Crashes with segmentation fault on nvidia 510

### ISSUE THREAD

**Issue by uuigdevt47** [mate-desktop/marco#720]
#### Expected behaviour
To work

#### Actual behaviour
Crashes with Segmentation Fault on Nvidia 510.47.03-6 and xorg-server 21.1.3-2

#### Steps to reproduce the behaviour
Tried using different wm (metacity or openbox) and it worked

#### MATE general version
1.26.0-x

#### Package version
1.26.0-1

#### Linux Distribution
Arch Linux

**Comment by howels** [comment]
Same issue here. Fix is to disable compositing for me:

```
gsettings set org.mate.Marco.general compositing-manager false
```

Not a great solution, but there we are.

**Comment by flexiondotorg** [comment]
This is a bug in xorg-server not Marco:

- https://gitlab.freedesktop.org/xorg/xserver/-/issues/1275
