### ISSUE TITLE
Screenshot has no default directory

### ISSUE THREAD

**Issue by FlailAway** [mate-desktop/marco#725]
#### Expected behaviour
Save the file

#### Actual behaviour
ERROR: Failed to execute child process "mate-screenshot" (No such file or directory)

#### Steps to reproduce the behaviour
Press "Prt_Scr"

#### MATE general version
Operating System: Linux Mint 20.3
Kernel: Linux 5.4.0-109-generic
Architecture: x86-64

#### Package version
What does that mean?

#### Linux Distribution
Mint mate 20.04

#### Link to bugreport of your Distribution (requirement)
What does that mean?

I don't have the "Document" etc., default directories so it may be looking for one of those.

**BUT**, I used dconf-editor (org/mate/screenshot) and it shows the Default as '' that is, 2-apostorphies, as in, nothing, empty.

I disabled "Use default path" and assigned "Downloads" saved, rebooted and still get the error even WITH the path shown as "Downloads."

**Comment by lukefromdc** [comment]
That sound like the mate-screenshot binary not being found. Can you execute mate-screenshot from terminal?

**Comment by FlailAway** [comment]
@lukefromdc: Thanks, that was it. It showed 
"mate-utils not installed"

I did an update then, 
  sudo apt install mate-utils

Fixed: thanks again. No idea why they were not installed originally.
