### ISSUE TITLE
Xorg crash: GLSL 1.30 is not supported

### ISSUE THREAD

**Issue by alkisg** [mate-desktop/marco#734]
Marco 1.26.0-3ubuntu1 in Ubuntu 22.04 with certain graphics cards and applications is causing Xorg crashes with the following message:

```
Failed to compile FS: 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```

Replacing it with xfwm4 or with marco 1.24.0-1ubuntu2 resolves the issue.
Running `marco --no-composite` does not help.

I suspect that it affects all graphics cards/drivers that don't provide GLSL 1.30. One affected graphics card is:

```shell
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02)
	Subsystem: Lenovo Core Processor Integrated Graphics Controller [17aa:3920]
	Kernel driver in use: i915
	Kernel modules: i915
```

One way to reproduce the issue is to run a VNC application fullscreen.
I'm attaching the related Xorg.0.log.old, you can see the crash at its end.

[Xorg.0.log.txt](https://github.com/mate-desktop/marco/files/9573475/Xorg.0.log.txt)

**Comment by kgidarakos** [comment]
This issue affects me too.

**Comment by alkisg** [comment]
Attaching [glxinfo.txt](https://github.com/mate-desktop/marco/files/9597365/glxinfo.txt) from an affected client.

It seems like marco is calling some Xorg function that other display managers do not call; then Xorg crashes. So it might not be a marco issue after all, but a Xorg or glamoregl issue. [This one seems similar](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1336).

Workarounds so far:

- Use `Driver "intel"` in xorg.conf (for those using LTSP, it's X_DRIVER=intel).
- Replace /usr/lib/xorg/Xorg with a shell script wrapper that sets `MESA_GL_VERSION_OVERRIDE=2.1` before executing Xorg.real.

**Comment by alkisg** [comment]
Even though marco could be patched to avoid the problematic Xorg calls, this issue probably needs to be reported and fixed in glamor, not here. Closing.
