### ISSUE TITLE
Fullscreen wine applications are now cropped

### ISSUE THREAD

**Issue by alkisg** [mate-desktop/marco#735]
Up to Ubuntu 20.04 / marco 1.24 / wine 5 things were fine.
Now with Ubuntu 22.04 / marco 1.26 / wine 6, fullscreen wine applications are cropped; others at e.g. half screen size and others at 100x100 pixels size, completely unusable.

[Example application web site](https://www.geoguessr.com/seterra/en/p/sebran) and [direct link to setup-sebran.exe](https://www.geoguessr.com/seterra/download/sebran.exe).

Downgrading to previous marco versions doesn't help.
Replacing marco with xfwm4 or openbox solves the issue.

The stderr message from marco is:

> Window manager warning: Window 0x3a00003 (Sebran) sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense

**Comment by kgidarakos** [comment]
This issue affects me too.

**Comment by alkisg** [comment]
That part of the codebase (window.c) hasn't changed much since the fork from metacity.
The same issue can be reproduced with metacity and gnome-shell (mutter) on both xorg and wayland.
I reported it to metacity as well: https://gitlab.gnome.org/GNOME/metacity/-/issues/33

**Comment by alkisg** [comment]
Alberts prepared a one-line patch for metacity that solves the issue.
The same patch works for marco as well.
Could someone please apply it upstream in marco?
If you wish, you may also import the rest of the changes/code cleanups that Alberts did in his [related branch](https://gitlab.gnome.org/GNOME/metacity/-/commits/wip/muktupavels/issue-33), but the following one-liner is enough to solve the current issue:

```diff
Author: Alberts Muktupāvels
Date:   Mon Oct 3 12:15:01 2022 +0300
    window: do not disable fullscreen for dialogs

diff --git a/src/core/window.c b/src/core/window.c
index 55badf5..51bb870 100644
--- a/src/core/window.c
+++ b/src/core/window.c
@@ -6732,7 +6732,8 @@ recalc_window_features (MetaWindow *window)
       window->has_resize_func = FALSE;
     }
 
-  if (window->type != META_WINDOW_NORMAL)
+  if (window->type != META_WINDOW_NORMAL &&
+      window->type != META_WINDOW_DIALOG)
     {
       window->has_minimize_func = FALSE;
       window->has_maximize_func = FALSE;
```

**Comment by alkisg** [comment]
For the affected Ubuntu 22.04 users, I uploaded a patched marco package in the [Greek schools PPA](https://launchpad.net/~ts.sch.gr/+archive/ubuntu/ppa).

**Comment by alkisg** [comment]
Thank you @raveit65 ! :+1:
