### ISSUE TITLE
Window title disappears when the first character is Chinese

### ISSUE THREAD

**Issue by cloudfish** [mate-desktop/marco#757]
#### Expected behaviour
Marco displays a window title starting with a character >= 3 bytes long.

#### Actual behaviour
Marco does not display a window title starting with a character >= 3 bytes long.

#### Steps to reproduce the behaviour
Open https://zh.wikipedia.org with firefox. The titlebar of firefox window does not contain a title.

#### MATE general version
1.26.1

#### Package version
marco 1.26.2

#### Linux Distribution
Debian

#### Link to bugreport of your Distribution (requirement)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041196

It seems that the fix for #749 caused this. Most Chinese characters are 3 bytes long under UTF-8, and UTF-8 characters can be as long as 4 bytes. So "g_utf8_strlen (title, 2) < 1" will be true if the first character is Chinese.

**Comment by lukefromdc** [comment]
I renamed a video file with a filename so long the title stretched across the window, opened it in firefox (which can play local video) and marco rendered the title. NO title on the named website, though I do not have any fonts relevent to that alphabet installed. Don't know if that issue is font specific.

**Comment by cloudfish** [comment]
I assume if fonts in the system do not support CJK characters, then only the CJK characters will be affected, not the entire title.

You can try opening https://www.debian.org/index.zh-cn.html with firefox. CJK characters will be in the middle of the title, not at the beginning. The title will be rendered correctly.

**Comment by lukefromdc** [comment]
This is what I got in firefox w marco as WM on that site, same as in compiz (which by the way uses part of marco to render decorations  in most builds of the 0.8 branch)
![Debian_in_firefox](https://github.com/mate-desktop/marco/assets/14036792/23bf87b0-6d4b-479d-9550-50ebd8b3f29d)

**Comment by cloudfish** [comment]
> This is what I got in firefox w marco as WM on that site, same as in compiz (which by the way uses part of marco to render decorations in most builds of the 0.8 branch) ![Debian_in_firefox](https://user-images.githubusercontent.com/14036792/253761869-23bf87b0-6d4b-479d-9550-50ebd8b3f29d.jpg)

This result is expected. Font issue should not make the entire title disappear. So if you open zh.wikipedia.org the title bar should still end with "Mozilla Firefox".

The issue does not affect 1.26.1, so maybe commit 319ee4f caused the issue.

**Comment by cwendling** [comment]
@cloudfish thanks for the detailed report, and even locating the problematic commit :)  #758 should fix it.

**Comment by lukefromdc** [comment]
Issue confirmed here, and it affects only marco and not compiz's use of marco for the gtk-window-decorator

**Comment by raveit65** [comment]
What's wrong with the tile of the window (it's not a bar)?
With fedora 38:
![Bildschirmfoto zu 2023-07-19 11-21-42](https://github.com/mate-desktop/marco/assets/961604/bab853c9-2d97-47d3-a33b-44924fc4e851)

**Comment by raveit65** [comment]
Indeed, window decoration title is gone of https://zh.wikipedia.org/ when building from latest master.
