### ISSUE TITLE
focus problem after closing windows

### ISSUE THREAD

**Issue by Anders-Gustavsson** [mate-desktop/marco#769]
#### Expected behaviour

Start some xterm's, after closing one of them the focus should turn to
the previously started (or focused xterm). 

#### Actual behaviour

When an xterm is closed, no other window gets focus.

There is a number of other applications than xterm that gets the same
problem, xmessage, emacs, java applications, xcalc...

The focus mode is default, that is click.

#### Steps to reproduce the behaviour

If not having click as focus mode:

gsettings set org.mate.Marco.general focus-mode click

start xterm:

xterm&
xterm&

and then close one of them.

#### MATE general version

Problem in: 1.26.0

Worked fine in: 1.24.0

#### Package version

Problem in marco version: 1.26.0

Worked fine in marco version: 1.24.0

#### Linux Distribution

Problem in Linux mint 21.3

Worked fine in Linux mint 20.1

#### Link to bugreport of your Distribution (requirement)

As i understand the linux mint documentation, bugs should be reported
in upstream projects.

**Comment by lukefromdc** [comment]
I use click to focus (all I've ever used and the normal default) and was just unable to duplicate this in marco 1.27 from git master

**Comment by Anders-Gustavsson** [comment]
Sorry for reporting this problem that has been fixed. I tried Fedora Linux 39 (MATE-Compiz) that has mate and marco 1.26.2 and it works good. I also compiled the code of marco 1.26.2 and got it to work with linux mint.
