### ISSUE TITLE
ADD marco --shutdown (or --quit) to disable autostart

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/marco#782]
#### Expected behaviour
when I kill marco, I dont want it to autostart again

#### Actual behaviour
autostarts

#### Steps to reproduce the behaviour
kill marco
ps axu | fgrep -i marco

#### MATE general version
1.26

#### Package version
1.26

#### Linux Distribution
Ubuntu Mate

#### Link to bugreport of your Distribution (requirement)
N/A

#### Use Case

wm testing and development

#### Default
defaults to off

### workaround
I uninstall marco for a few hours

**Comment by lukefromdc** [comment]
Removing autorestart from marco would mean users who get a crash may not know how to get their window borders back. This could cause inexperienced users to lose their work logging out or even power cycling to get their window borders back. We are not going to remove the default restart of marco for this reason

If you need to run another window manager  e.g compiz run it with the --replace option. If you need to run with NO window manager, open dconf-editor, navigate to org/mate/desktop/session/required-components/windowmanager
and leave it blank. Setting it to compiz will autostart compiz with the session etc.

**Comment by lukefromdc** [comment]
A --shutdown or --quit option would be rarely used as --replace is normally used with another window manager and running the MATE session with no window manager is an extremely rare use case though I could see doing this (as with caja or mate-panel) to run it under gdb from the commandline for debugging. 

I will not be spending time on coding this, but won't block anyone else coding up such an option either.

**Comment by allanlaal** [comment]
most window managers dont have their own --replace. marco will race and win

**Comment by lukefromdc** [comment]
I know for a fact that compiz and icewm support --replace .
