### ISSUE TITLE
Window title starting with Chinese character doesn't show normally.

### ISSUE THREAD

**Issue by bladez97** [mate-desktop/marco#783]
#### Expected behaviour
- The title text shows correctly on window's title bar

#### Actual behaviour
- The title text disappears when a window's title starts with Chinese  character.
- However if the title only contains Chinese chatacter, but not start with Chinese character, it is fine.
- Installed another WM metacity and tried "metacity --replace" in terminal and the issue is no longer exist.
- Also verified this bug exists in Ubuntu MATE Live ISO enviroment.

#### Steps to reproduce the behaviour
- Start Caja
- Create 2 folders, and name them "中文abc" and "abc中文" in which one of them start with Chinese character
- Open them in two different window
- The window of folder "中文abc" has no text in its title bar.

#### MATE general version
- MATE 1.26.2

#### Package version
- 1.26.2-4build4 

#### Linux Distribution
- Ubuntu mate 24.04.1 LTS

#### Link to bugreport of your Distribution (requirement)
- https://bugs.launchpad.net/ubuntu-mate/+bug/2080025

![Screenshot at 2024-09-10 01-40-35](https://github.com/user-attachments/assets/5c8cc27e-9f72-49fe-847a-2b6698783728)

**Comment by lukefromdc** [comment]
Looks like a commit fixing this is in master and 1.28 and cherrypicked to 1.26, but the last 1.26 release
was before it (in fact right before it) and there has not been another 1.26 release since then.

Right now we have another MATE-wide Travis issue that I don't know how to fix, so someone else on the team will have to  deal with the Travis issue (cannot deploy)  so a new 1.26 release can go out with this fixed

**Comment by lukefromdc** [comment]
This is a duplicate of https://github.com/mate-desktop/marco/issues/757
the commit that fixed it in the 1.26 branch that has not had a release since the commit in question is https://github.com/mate-desktop/marco/commit/a938884530839152c9854dd0d8248b36c3c2e3fd

**Comment by bladez97** [comment]
Thanks for the reply. Will wait for Ubuntu MATE team to fix.

> This is a duplicate of #757 the commit that fixed it in the 1.26 branch that has not had a release since the commit in question is [a938884](https://github.com/mate-desktop/marco/commit/a938884530839152c9854dd0d8248b36c3c2e3fd)
> 
> If they want to, the Ubuntu-MATE team could fix this for now in their package by applying the above commit at the distro level before building marco. So can any other distro still on 1.26, the current branch is 1.28 and contains this fix as well
