### ISSUE TITLE
Alt-` to switch between windows of the same application

### ISSUE THREAD

**Issue by stefano-k** [mate-desktop/marco#90]
Original report: https://github.com/mate-desktop/mate-desktop/issues/73
Original reporter: @ukch

In other shells such as Unity and Cinnamon, pressing alt-` (the button to the left of 1) enables the user to switch between windows of the same application, whereas alt-tab is for switching between applications. However, there seems to be no such functionality in Mate.

**Comment by monsta** [comment]
Well, it's already implemented ("Move between windows of an application, using a popup window"), just the keybinding isn't set by default.

However, the keybinding for switching between windows of an application *immediately* (without showing a popup window) is already set to ```Alt-F6``` by default.

@flexiondotorg @raveit65 @stefano-k @clefebvre 
What do you think guys? Should we set this keybinding by default as well?

**Comment by clefebvre** [comment]
Sure.
It'll please people expecting that shortcut, and it won't bother others.. so yes for me.

**Comment by flexiondotorg** [comment]
+1
