### ISSUE TITLE
Vertical synchronization

### ISSUE THREAD

**Issue by equeim** [mate-desktop/marco#91]
Currently I can remove tearing with marco only using compton, while marco also have its own compositor.
##

**Comment by mdickie** [comment]
I am affected by using Firefox smooth scrolling. I hope this gets solved because I'd like to use marco without compton.

**Comment by monsta** [comment]
Guys, stupid question... is OpenGL absolutely needed for vsync? Can't vsync be implemented w/o it?

**Comment by monsta** [comment]
Ok, let's move to https://github.com/mate-desktop/marco/issues/326, DRI3/Present looks like a solution

**Comment by Sunderland93** [comment]
@monsta 

> OpenGL absolutely needed for vsync?

For use with proprietary Nvidia driver - yes. Also, GLX support is needed for hardware acceleration
