### ISSUE TITLE
Dropping windows on screen edges doesn't maximize them properly

### ISSUE THREAD

**Issue by ikem-krueger** [mate-desktop/marco#95]
I noticed a minor glitch with window snapping.

This is how the window looks when I maximize it via window snapping:

![bildschirmfoto](https://f.cloud.github.com/assets/1711129/2366157/d23cba6c-a6f2-11e3-8c5c-d316ae95522c.png)

This is how the window looks when I maximize it via the maximize button:

![bildschirmfoto-1](https://f.cloud.github.com/assets/1711129/2366156/d23a50ba-a6f2-11e3-9c48-f3b331529382.png)

With the window snapping method, the window is not fully maximized.

**Comment by DarkSnake64** [comment]
Unfortunately, 2 months later this bug is still present in Ubuntu repos.
