### ISSUE TITLE
Make the reduced resources mode more pleasurable for the eyes

### ISSUE THREAD

**Issue by ikem-krueger** [mate-desktop/marco#97]
Enable "reduced resources" and you see a wireframe when you move a window.

What I like to see is only the outer frame of the window, not the inner "wires".

**Comment by monsta** [comment]
Wow, the mentioned PR (https://github.com/mate-desktop/marco/issues/122) removes a lot of code. So do we need it?

**Comment by flexiondotorg** [comment]
The MATE team have decided that we don't wish to make this change.
